Rename stand3 to liedown
OpenRA/OpenRA pull request #11928
Opened 2016-08-31 15:18 UTC by abcdefg30

`liedown` appears to be what `stand3` is.
(I also moved `liedown` next to/right above `standup`.)

Closes #11703.

2016-09-01 05:43 UTC, Mailaender commented
:+1: to giving this a better name, but how does that resolve the issue?

2016-09-01 15:48 UTC, abcdefg30 commented
This kind of makes #11703 a duplicate of #6330 (and thus I'd close #11703).

2016-09-16 19:47 UTC, pchote commented on mods/ra/sequences/infantry.yaml
> +		Length: 16
These should all be Length: 2 and Facings: 8, like the standup animations.

2016-09-16 19:51 UTC, pchote commented on mods/ra/sequences/infantry.yaml
>  	standup-0:
I have no idea why I called this `standup-0` back in befe22e170b1a06143f59da9880cbda3a71f5757, but this has been randomly copy pasta-ed to a few more places.  Can you please rename them to `standup` for consistency while we're here.

2016-09-16 19:51 UTC, pchote requested changes

2016-09-26 13:49 UTC, abcdefg30 commented
Sorry for the delay. Updated.

2016-09-26 14:05 UTC, pchote approved these changes

2016-09-26 14:32 UTC, merged

2016-09-26 14:32 UTC, reaperrr commented
Does this need a changelog entry?

2016-09-26 14:52 UTC, pchote commented
I don't think so.