Added diplomatic stances to JamsRadar
OpenRA/OpenRA pull request #11926
Opened 2016-08-30 19:18 UTC by abc013

2016-08-30 19:33 UTC, GraionDilach commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		public readonly Stance JamsRadarStances = Stance.Ally | Stance.Neutral | Stance.Enemy;
Please make this default to Neutral | Enemy or add an upgrade rule because this regresses third-party mods as-is.

2016-08-30 20:15 UTC, abc013 commented
updated.

2016-08-30 20:27 UTC, GraionDilach commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		public readonly Stance JamsRadarStances = Stance.Ally | Stance.Neutral;
Uhm, you did this wrong. Neutral | Enemy, not Ally | Neutral was my request (you can remove the YAML definition thenafter as well.)

2016-08-30 20:27 UTC, Phrohdoh commented on OpenRA.Mods.Common/Traits/Radar/ProvidesRadar.cs
> +			return self.World.ActorsWithTrait<JamsRadar>().All(a => !a.Actor.Owner.Stances[self.Owner].HasStance(a.Actor.Info.TraitInfo<JamsRadarInfo>().JamsRadarStances)
Instead of looking up the traitinfo again use `a.Trait.JamsRadarStances`.

2016-08-30 20:37 UTC, abc013 commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		public readonly Stance JamsRadarStances = Stance.Ally | Stance.Neutral;
Oops

2016-08-30 20:49 UTC, abc013 commented on OpenRA.Mods.Common/Traits/Radar/ProvidesRadar.cs
> +			return self.World.ActorsWithTrait<JamsRadar>().All(a => !a.Actor.Owner.Stances[self.Owner].HasStance(a.Actor.Info.TraitInfo<JamsRadarInfo>().JamsRadarStances)
Hmm, `a.Trait.JamsRadarStances` does somehow not work.

2016-08-30 20:50 UTC, abc013 commented
@GraionDilach fixed.

2016-08-30 20:51 UTC, pchote commented on OpenRA.Mods.Common/Traits/Radar/ProvidesRadar.cs
> +			return self.World.ActorsWithTrait<JamsRadar>().All(a => !a.Actor.Owner.Stances[self.Owner].HasStance(a.Actor.Info.TraitInfo<JamsRadarInfo>().JamsRadarStances)
You'll need to change `JamsRadar` to store a public reference to the `Info`, and then use `a.Trait.Info.JamsRadarStances` for that to work.

2016-08-30 20:54 UTC, GraionDilach commented on mods/ra/rules/vehicles.yaml
> +		JamsRadarStances: Enemy, Neutral
This became redundant now.

2016-08-30 21:11 UTC, abc013 commented
And changed again.

2016-09-04 15:25 UTC, Phrohdoh commented
👍

2016-09-14 19:38 UTC, abcdefg30 requested changes
This needs the same change as JamsMissiles did: #11983

2016-09-17 08:25 UTC, abc013 commented
Updated.

2016-09-18 15:05 UTC, reaperrr commented
@Phrohdoh There were some changes since your review, could you 'refresh' your +1?

2016-09-18 16:14 UTC, Phrohdoh commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		public readonly Stance JamsRadarStances = Stance.Enemy | Stance.Neutral;
s/What/Which
And this should be named `Stances` (the JamsRadar part is implied).

2016-09-18 16:15 UTC, phrohdoh reviewed
The return statement is quite complex and the `All` doesn't seem right to me, but I can't spend much time trying to make heads or tails of it currently, so won't be able to approve this.

2016-09-18 16:20 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		public readonly Stance JamsRadarStances = Stance.Enemy | Stance.Neutral;
We have `DeflectionStances` in `JamsMissiles`, so `JamStances` here for "consistency"?

2016-09-18 16:20 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		public readonly Stance JamsRadarStances = Stance.Enemy | Stance.Neutral;
Basically you're right, though. It doesn't make much sense to include more than just `Stances`.

2016-09-19 19:58 UTC, obrakmann commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		[Desc("What diplomatic stances are affected.")]
"Which"

2016-09-19 20:00 UTC, obrakmann commented
Looks good except for the typo, :+1: 

> Should I do the same change for `DeflectionStances`?

I'd say no. It's unnecessary churn for now.

2016-09-20 11:15 UTC, abc013 commented on OpenRA.Mods.Common/Traits/Radar/JamsRadar.cs
> +		[Desc("What diplomatic stances are affected.")]
changed.

2016-09-20 11:15 UTC, abc013 commented
Updated.

2016-09-20 17:24 UTC, merged

2016-09-20 17:26 UTC, obrakmann commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1e7b775287054ce66c3d82c807c9f8ac8cacd080)