Improve out-of-memory logging
OpenRA/OpenRA pull request #12014
Opened 2016-09-11 16:06 UTC by RoosterDragon

Add more detail when an `OutOfMemoryException` is thrown (see #9931).

Also ensure that when OpenGL gives an out-of-memory error, we throw an `OutOfMemoryException` so the improved logging is triggered here too.

Example output (with a pretend error in the OpenGL error handler):
```
Red Alert Mod at Version {DEV_VERSION}
on map e90c1d4ea07b7cbb048a1057a1b0be4f11ecbe90 (Desert Shellmap by Scott_NZ).
Date: 2016-09-11 15:59:00Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: OpenGL Error: See graphics.log for details.
GC Memory (post-collect)=97,467,976
GC Memory (pre-collect)=162,268,088
Working Set=276,512,768
Private Memory=310,460,416
Virtual Memory=627,970,048
   at OpenRA.Platforms.Default.OpenGL.CheckGLError() in C:\...\OpenRA\OpenRA.Platforms.Default\OpenGL.cs:line 498
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.Clear() in C:\...\OpenRA\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs:line 217
   at OpenRA.Renderer.BeginFrame(int2 scroll, Single zoom) in C:\...\OpenRA\OpenRA.Game\Renderer.cs:line 109
   at OpenRA.Game.RenderTick() in C:\...\OpenRA\OpenRA.Game\Game.cs:line 601
   at OpenRA.Game.Loop() in C:\...\OpenRA\OpenRA.Game\Game.cs:line 734
   at OpenRA.Game.Run() in C:\...\OpenRA\OpenRA.Game\Game.cs:line 752
   at OpenRA.Program.Run(String[] args) in C:\...\OpenRA\OpenRA.Game\Support\Program.cs:line 132
   at OpenRA.Program.Main(String[] args) in C:\...\OpenRA\OpenRA.Game\Support\Program.cs:line 40
```

2016-09-15 18:33 UTC, pchote commented on OpenRA.Game/Support/Program.cs
> +		static StringBuilder IndentedAppendFormatLine(this StringBuilder sb, int indent, string format, params object[] args)
Shouldn't this be `AppendIndentedFormatLine`?

2016-09-15 18:53 UTC, pchote requested changes
Looks good aside from that one nit, and works as advertised.  :+1: after the fixup.

2016-09-16 06:35 UTC, RoosterDragon commented on OpenRA.Game/Support/Program.cs
> +		static StringBuilder IndentedAppendFormatLine(this StringBuilder sb, int indent, string format, params object[] args)
Yeah that does read better.

2016-09-16 07:43 UTC, pchote approved these changes

2016-09-18 14:38 UTC, merged

2016-09-18 14:48 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/650bfddccc01bedf992d4e6953d0ad9458880b8b...18dcb611786eaf283d1e19ec5ca38e1e9374126a)

2016-09-18 17:21 UTC, pchote commented
Would anyone object to picking this onto prep-1609?