Fix not being able to close the chat window in replays
OpenRA/OpenRA pull request #12036
Opened 2016-09-16 14:36 UTC by obrakmann

Two minor things I have no solution for:

1. You can't use the enter key on the keypad in replays, whereas you can during normal games.
2. Closing the chat in replays causes the button sound to play.

2016-09-16 15:21 UTC, pchote commented
hmm.... I guess both of those limitations come from the way our Button widget keypress handling works.  We could solve these by using a `LogicKeyListenerWidget` instead of the button.

2016-09-16 16:00 UTC, obrakmann commented
That works. Updated.

2016-09-16 17:06 UTC, pchote commented on OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameChatLogic.cs
> +				if ((e.Key == Keycode.RETURN || e.Key == Keycode.KP_ENTER) && e.Modifiers == Modifiers.None)
I just noticed that the regular chat input also binds escape to close.  Please add ` || e.Key == Keycode.ESCAPE` here, and this will be perfect.

2016-09-16 17:07 UTC, pchote requested changes
:+1: after that one fix.

2016-09-16 17:07 UTC, pchote approved these changes

2016-09-16 17:07 UTC, pchote requested changes
mis-click...

2016-09-17 13:05 UTC, obrakmann commented
Added ESC key.

2016-09-18 12:24 UTC, pchote approved these changes

2016-09-18 13:28 UTC, reaperrr commented
:+1:

2016-09-18 13:28 UTC, merged

2016-09-18 13:30 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/afab2dadb3e38be9bcab5764266eec174077f03e...6b6eb3b973c57e5f42ce890a6625b9a72cb64906)