Fix crashing when a spy's "real" owner gets changed
OpenRA/OpenRA pull request #12046
Opened 2016-09-17 17:23 UTC by obrakmann

Fixes #11996

2016-09-17 22:44 UTC, reaperrr approved these changes

2016-09-18 11:11 UTC, Mailaender commented
Works as promised. :+1: You can also remove my workaround now:

```diff
diff --git a/mods/ra/maps/infiltration/rules.yaml b/mods/ra/maps/infiltration/rules.yaml
index 47b0263..ec2da22 100644
--- a/mods/ra/maps/infiltration/rules.yaml
+++ b/mods/ra/maps/infiltration/rules.yaml
@@ -54,9 +54,6 @@ SPY.Strong:
                Types: MissionObjective
        ExternalCaptures:
                CaptureTypes: MissionObjective
-       EditorOnlyTooltip:
-               Description: RenderDebugState.OnOwnerChange will crash
-       -RenderDebugState:
        Passenger:
                GrantUpgrades: mobile
```

2016-09-18 11:36 UTC, obrakmann commented
Removed workarounds.

2016-09-18 12:00 UTC, pchote commented on OpenRA.Mods.Common/Traits/Render/RenderDebugState.cs
> +			return self.EffectiveOwner != null && self.EffectiveOwner.Owner != null ? self.EffectiveOwner.Owner.Color.RGB : self.Owner.Color.RGB;
This should be looking at `EffectiveOwner.Disguised` for consistency with the other checks.

2016-09-18 12:00 UTC, pchote requested changes

2016-09-18 12:46 UTC, obrakmann commented
Changed

2016-09-20 08:14 UTC, pchote approved these changes

2016-09-20 08:15 UTC, merged

2016-09-20 08:17 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/6c079644da99005c086f8ce266ed7f89d549978f