Add several features to LaserZap
OpenRA/OpenRA pull request #12068
Opened 2016-09-20 15:29 UTC by reaperrr

- secondary beam for glow effect
- disable (visual) target-tracking
- support for inaccuracy
- support for blockability

2016-10-02 14:00 UTC, Mailaender commented on OpenRA.Mods.Common/Projectiles/LaserZap.cs
> +		public readonly bool SecondaryBeam = false;
This will need a `TertiaryBeam` etc. so why not add another LaserBeam that doesn't do any damage?

2016-10-02 14:58 UTC, GraionDilach commented on OpenRA.Mods.Common/Projectiles/LaserZap.cs
> +		public readonly bool SecondaryBeam = false;
In his defense, TS/RA2 did have two lasers drawn at once - LaserInnerColor and LaserOuterColor defined that. (TS/RA2 also had LaserOuterSpread though.)

2016-10-03 17:50 UTC, abcdefg30 commented
Looks good to me. :+1: / :white_check_mark:

2016-10-03 17:51 UTC, Mailaender commented on OpenRA.Mods.Common/Projectiles/LaserZap.cs
> +		public readonly bool SecondaryBeam = false;
I see.

2016-10-09 12:01 UTC, obrakmann requested changes
Seems fine to me, 👍 

Please remove the test case.

2016-10-09 12:01 UTC, obrakmann commented on OpenRA.Mods.Common/UtilityCommands/UpgradeRules.cs
> +				if (engineVersion < 20160919)
Please update the date.

2016-10-09 13:11 UTC, reaperrr commented
Removed test case and updated upgrade rule date.

2016-10-09 13:24 UTC, obrakmann approved these changes

2016-10-09 13:24 UTC, merged

2016-10-09 13:28 UTC, obrakmann commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/56ace71e0b1e3b058a6345daa4e0a2aba718a62d)