Display error in Asset Browser instead of crashing
OpenRA/OpenRA pull request #12098
Opened 2016-09-24 16:09 UTC by Phrohdoh

2016-09-24 16:31 UTC, Mailaender commented on OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
> +				Log.Write("debug", "Error reading {0}: {1} {2}", filename, ex.Message, ex.StackTrace);
debug.log is pretty crowded even in the main menu due to the shellmap and we don't really care at which game tick this happened. Maybe use exception.log or invent your own new channel.

2016-09-24 16:32 UTC, Phrohdoh commented on OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
> +				Log.Write("debug", "Error reading {0}: {1} {2}", filename, ex.Message, ex.StackTrace);
A fair point.

I'll use `asset-browser.log`.

2016-09-24 16:39 UTC, Mailaender commented
:+1:

2016-09-24 16:42 UTC, Mailaender commented
You will need to adapt https://github.com/Phrohdoh/OpenRA/blob/ab-err-label/mods/cnc/chrome/assetbrowser.yaml as well.

2016-09-24 16:42 UTC, Mailaender requested changes
You will need to adapt https://github.com/Phrohdoh/OpenRA/blob/ab-err-label/mods/cnc/chrome/assetbrowser.yaml as well.

2016-09-24 16:45 UTC, Phrohdoh commented
I have updated cnc's assetbrowser.

2016-09-24 16:46 UTC, Mailaender approved these changes

2016-09-24 17:57 UTC, abcdefg30 commented on mods/cnc/chrome/assetbrowser.yaml
> +							Text: Error displaying {{filename}} check debug.log
Is there a special reason why you didn't just go for `{filename}`?

2016-09-24 19:25 UTC, abcdefg30 commented
Don't we want to disable the palette selector as well (because we already disable the color picker)?

2016-09-24 22:41 UTC, Phrohdoh commented on mods/cnc/chrome/assetbrowser.yaml
> +							Text: Error displaying {{filename}} check debug.log
Probably something to do with named values but looking at this again I think my mind was still in Python mode.

2016-09-24 23:28 UTC, abcdefg30 commented
Never mind my last comment. This should be good to go now.

2016-09-25 18:55 UTC, abcdefg30 commented on mods/cnc/chrome/assetbrowser.yaml
> +							Text: Error displaying {filename} check debug.log
This now needs to reference `assetbrowser.log`.

2016-09-25 19:02 UTC, abcdefg30 approved these changes
Thanks a lot! That bug was really annoying, but this PR with https://github.com/OpenRA/ra2/pull/302 plays nicely.

You can remove the testcommit now.
👍 / ✅ once you changed `debug.log` to `assetbrowser.log`.

2016-09-25 20:54 UTC, Phrohdoh commented
@abcdefg30 done.

2016-09-25 20:54 UTC, Phrohdoh commented on mods/cnc/chrome/assetbrowser.yaml
> +							Text: Error displaying {filename} check debug.log
Fixed.

2016-09-26 11:15 UTC, merged

2016-09-26 11:19 UTC, abcdefg30 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1e7b775287054ce66c3d82c807c9f8ac8cacd080...364c9a81046ac443436bfd807019a6967afae257)