Tweak aircraft resupply behaviour.
OpenRA/OpenRA pull request #12102
Opened 2016-09-25 14:54 UTC by pchote

This implements two changes:

1.  When the "return to base" hotkey is used all aircraft will return to base, but only those that can be resupplied will land on helipads.  This avoids the annoying dance (particularly in TD, where helipads are only used for repairing) where multiple helicopters will touch-and-go on the pad, wasting time that could be used resupplying those that actually need it.

2.  @e1d1s1 has been arguing (#11979, #11982) that aircraft continuing their attacks after resupplying is a gameplay regression, and i'm now inclined to agree.  This adds an `AbortOnResupply` flag to disable this feature, and enables it by default.

2016-09-25 15:00 UTC, pchote commented
@obrakmann had the following to say about 1. in IRC:

>[20:29:32]	&lt;antares79&gt; I looked at your land-foo branch as well. It doesn't behave the way I feared it would (although I'm not sure why). I'd be ok with it being in the playtest 
> [20:32:51]	&lt;antares79&gt; pchote: I guess the extra ResupplyAircraft invocation can safely go as well. I don't see it being useful

2016-09-25 17:48 UTC, reaperrr commented
> This adds an AbortOnResupply flag to disable this feature, and enables it by default.

:+1: I was thinking about filing a ticket for that before you filed this PR.

2016-09-25 17:48 UTC, reaperrr approved these changes

2016-09-26 16:13 UTC, obrakmann commented on OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
> +				landingProcedures.Add(NextActivity);
Please re-write this in such a way that calling this activity from the Lua API won't throw away the queue.

2016-09-26 16:24 UTC, obrakmann commented on OpenRA.Mods.Common/Activities/Air/HeliReturnToBase.cs
> +					!heli.Info.AbortOnResupply ? NextActivity : null);
same here

2016-09-26 16:31 UTC, obrakmann requested changes
The rest looks ok.

2016-09-26 16:50 UTC, pchote commented
Done.

2016-09-26 17:00 UTC, obrakmann approved these changes

2016-09-26 17:03 UTC, merged

2016-09-26 17:06 UTC, obrakmann commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c74f14a314b7bf2b1f11b7b5957b5bb7baf39742)

2016-09-27 07:21 UTC, e1d1s1 commented
Mechanics still cannot heal helos unless they are rearming.

Mousing over a pad and issuing a "land" command (triple down arrow symbol) with a mouse click has the effect of a touch and go. At the very least, this command should lead to the helo landing in order to get mechanic repairs.

"F" command has the effect of all helos clumping to a point near a single helipad, and sometimes jittering/dancing about the point. If you have 3 pads and 3 helos, they should spread out accordingly. If you have more helos than pads, it might make more sense for them to line up at neatly at the rally point the same as when they spawn.

A compromising solution would be to continue your new behavior of rearm - takeoff if the helos return to base of their own accord (out of ammo), but a command of F or mouse click land command should force the helo down on the pad.