Add support for applying a target flash to actors through lua
OpenRA/OpenRA pull request #12112
Opened 2016-09-26 15:26 UTC by abcdefg30

Allows to code stuff like https://youtu.be/afzfD0AGTPQ?t=5m32s.

2016-09-26 15:48 UTC, Phrohdoh commented on OpenRA.Mods.Common/Scripting/Properties/GeneralProperties.cs
> +		[Desc("Render a target flash on the actor. If set, 'asPlayer'",
Are these strings joined together with a space or directly concatenated?
If the latter you'll want to insert a space at the end of the first string or at the beginning of the second.

2016-09-26 15:52 UTC, abcdefg30 commented on OpenRA.Mods.Common/Scripting/Properties/GeneralProperties.cs
> +		[Desc("Render a target flash on the actor. If set, 'asPlayer'",
They should be two different lines, iirc (as in ", == \n").

2016-10-11 01:57 UTC, pchote requested changes

2016-10-11 01:57 UTC, pchote commented on OpenRA.Mods.Common/Scripting/Properties/GeneralProperties.cs
> +		public void FlashTarget(int duration = 4, Player asPlayer = null)
This doesn't accept a target argument\ to flash, so "FlashTarget" isn't a great name.  How about just "Flash"?

2016-10-11 09:05 UTC, abcdefg30 commented
Updated.

2016-10-21 01:03 UTC, pchote approved these changes
Works as advertised, and seems like a reasonable API addition to make.

2016-10-22 20:53 UTC, merged

2016-10-22 20:55 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9a804f47725982845d9633d5b6fd92c1335ad5ae...66976c0cd3f116f3ed068b1581edd12f725e9903)