[TS] Content: Add support for Firestorm Asset installations
OpenRA/OpenRA pull request #12113
Opened 2016-09-26 15:49 UTC by LipkeGu

This PR is basically a copy of #11787 but enables the Installation and Download of "stripped down" Firestorm Assets and Music.

2016-09-26 16:05 UTC, pchote commented on mods/ts/installer/downloads.yaml
> +tibsun: C&C Tiberian Sun
Please keep the displayed names as they are.  The naming (a) makes it clear that the original games were released as freeware, and (b) keeps consistency between the mods.

2016-09-26 16:05 UTC, pchote requested changes

2016-09-26 16:16 UTC, LipkeGu commented on mods/ts/installer/downloads.yaml
> +tibsun: C&C Tiberian Sun
updated

2016-09-26 16:25 UTC, pchote commented on mods/ts/installer/downloads.yaml
> +		^Content/ts/firestorm/isotemp.mix: firestorm/isotemp.mix
Please extract out just the unique files from inside these mixes too.

2016-09-26 16:25 UTC, pchote requested changes

2016-09-26 18:36 UTC, LipkeGu commented on mods/ts/installer/downloads.yaml
> +		^Content/ts/firestorm/isotemp.mix: firestorm/isotemp.mix
updated

2016-09-26 19:04 UTC, LipkeGu commented
![fona](https://cloud.githubusercontent.com/assets/2057932/18848009/bcc5f0c6-842c-11e6-8d10-e6e36669697a.png)

2016-09-26 20:07 UTC, LipkeGu commented
updated

2016-09-27 15:24 UTC, LipkeGu commented
Can anyone share the tibsun.mix and expand01.mix from orign-installations?

2016-09-29 14:49 UTC, LipkeGu commented
@Mailaender I gave you Write Access to this Branch so you can work with this entire Branch... Reaper or Jugglernaut.

2016-09-29 17:11 UTC, Mailaender commented
Thanks for taking this task over and for the invitation, but I won't just interfere here.

2016-10-04 16:19 UTC, LipkeGu commented
updated

2016-10-11 02:33 UTC, pchote reviewed
This all looks correct, but I haven't verified whether this includes _all_ the unique firestorm content.  @ABrandau can you double check this?

Please see the nits below.

2016-10-11 02:33 UTC, pchote commented on mods/ts/installer/origin.yaml
> +				Length: 2037606
You've accidentally removed the end-of-file newline here.

2016-10-11 02:33 UTC, pchote commented on mods/ts/installer/tibsun.yaml
> +
This change can be dropped too.

2016-10-11 02:33 UTC, pchote commented on mods/ts/installer/downloads.yaml
> +	URL: http://81.169.246.181/openra/ts/ts-expand.zip
Can you please add these to https://github.com/OpenRA/OpenRAWeb/pull/316?  You'll need to create a new mirror txt file. Once that is merged we can set these properly.

2016-10-11 02:33 UTC, pchote commented
:+1: after the nits have been fixed (assuming no other nits work their way in as part of that).

2016-10-11 15:29 UTC, LipkeGu commented
Updated and switched to MirrorList for the time until the mirrors will be updated the links are stored here

firestorm files: http://81.169.246.181/openra/ts/ts-expand.zip
firestorm Music: http://81.169.246.181/openra/ts/ts-fsmusic.zip

2016-10-11 23:09 UTC, ABrandau commented
Dawnbridges loads fine but the quick install function didn't work for me, seems it downloaded some files and then discarded them, created a loop, I had to use the advanced install option to get the Firestorm data.

2016-10-12 03:25 UTC, Mailaender commented
> Most work and thanks goes to @Mailaender

Actually most work and thanks goes to @ABrandau: https://github.com/ABrandau/OpenRA/tree/FS-Files-Inclussion

> Updated and switched to MirrorList for the time until the mirrors will be updated

https://github.com/OpenRA/OpenRAWeb/pull/316 has been merged. Hope this helps.

2016-10-12 15:58 UTC, Iamgoofball commented
I've got the Origin collection US edition if you still need those mixes

2016-10-12 17:37 UTC, Mailaender commented
The purpose of this pull request is not to generate those mix files, but find a procedure so anyone can do it himself with a simple graphical user interface. You can help test this patch and give your :+1: if it works for you.

2016-10-13 20:15 UTC, LipkeGu commented
>Dawnbridges loads fine but the quick install function didn't work for me, seems it downloaded some files >and then discarded them, created a loop, I had to use the advanced install option to get the Firestorm >data.

it is currently not validated that the orign US mixes are valid, we need hashes can you send me the sha1 hash of expand01 or the file expand01 file itself?

the files gets extracted not copied

2016-10-20 23:14 UTC, reaperrr commented on mods/ts/sequences/trees.yaml
> +	idle: bigblue2
Why not use bigblue3?

2016-10-20 23:18 UTC, reaperrr commented on mods/ts/installer/tibsun.yaml
> +
@LipkeGu You haven't adressed this yet.

2016-10-23 13:25 UTC, pchote requested changes

2016-10-23 13:25 UTC, pchote commented on mods/ts/mod.yaml
>  	QuickDownload: basefiles
You need to package a new quickinstall zip that contains all the essential content (base + firestorm, without music), and then reference it here.

2016-10-23 13:25 UTC, pchote commented on mods/ts/mod.yaml
>  	QuickDownload: basefiles
This is why the quick install button doesn't work.

2016-10-29 13:23 UTC, pchote commented
Any progress here @LipkeGu?

2016-11-17 17:13 UTC, docholiday commented
Hi there, the firestorm files and music seem to be down (I always get a timeout). Could you please make them available again?

2016-11-26 13:38 UTC, reaperrr commented
Superseded by #12429.

2016-11-26 13:38 UTC, closed without merging