TS polishing pass: More depth sorting and starting units
OpenRA/OpenRA pull request #12135
Opened 2016-09-30 04:01 UTC by reaperrr

- Fixes depth sorting of editor actors (spawnpoint, waypoint, camera)
- Fixes depth sorting and offsets of several civilian structures
- Increases number of starting units for medium by 1 and for heavy by 2

2016-10-02 02:06 UTC, Mailaender approved these changes

2016-10-04 19:15 UTC, LipkeGu commented
closes #12119

2016-10-05 12:29 UTC, MustaphaTR commented
I'm not sure if i'm happy with the starting units changes in this PR, i think it should be like following:

GDI Light: e1, e1, e2, e2, jumpjet, smech
GDI Heavy: e1, e1, e1, e2, e2, jumpjet, smech, smech, mmch
Nod Light: e1, e1, e3, e3, cyborg, bggy
Nod Heavy: e1, e1, e1, e3, e3, cyborg, bggy, bike, ttnk

2016-10-14 15:43 UTC, reaperrr commented
Updated.

Heavy starting forces now match what @MustaphaTR suggested, Medium now match what he suggested for Light, and on Light the e2 and e3 were replaced with a single Wolverine/Buggy respectively (Grenadiers are superior to Bazookas in direct combat, so these were quite unbalanced before).

2016-10-15 03:04 UTC, pchote commented on mods/ts/sequences/civilian.yaml
> +		Offset: 12, -30, 36
Why are you setting a larger z offset than y offset in these cases?

2016-10-15 10:35 UTC, reaperrr commented on mods/ts/sequences/civilian.yaml
> +		Offset: 12, -30, 36
The bottom-right edges were cut off (invisible) with the previous values. If there's a better way to fix that, I'm all ears/eyes.

2016-10-15 11:58 UTC, pchote commented on mods/ts/sequences/civilian.yaml
> +		Offset: 12, -30, 36
The depth sprite is probably not centered relative to the artwork, try moving that to the right instead.  If ^ is the case then adding a uniform offset to Z may indeed fix the right hand side, but makes the imbalance on the left even larger, causing potential clipping problems there instead.

2016-10-15 12:39 UTC, reaperrr commented
Updated, used `DepthSpriteOffset` to further improve temperate civ building offsets.

2016-10-15 16:21 UTC, pchote requested changes
city17 is missing a couple of px off the lamp posts on the side, and gakodk could do with a fix too.  Just in case you're doing this the hard way, you can use the map editor to quickly look for cut off pixels (compare the placement preview with the placed actor).

You should also try using 4d2aebe2b822de5afaa128ace12c91fbd922fab2 (ingame, won't work in the editor) to view the relative positions of the depth mask to the actor.  The bright stripe should be aligned with the front corner of the actor, which you'll see isn't the case for a few of civ structures.

2016-10-22 01:18 UTC, reaperrr commented
> city17 is missing a couple of px off the lamp posts on the side

Are you sure? I couldn't see a difference, and the depth sprite position looks right to me.

Anyway, improved the 4x2 buildings and added fixes for the Kodiak, Montauk, Hospital, deployed ICBM and the 5 larger `aban*` snow buildings.

2016-10-23 14:23 UTC, reaperrr commented
@pchote I gave city17 another good, hard look, but I really can't spot a single pixel difference between the preview and placed building. If it was really that building, I'll need a screenshot, otherwise I'll assume it was either a different building or I already fixed it by accident somehow.

I did spot some grave z-sorting issues with deployed sensor arrays, though, so I'll add a fix for that.

2016-10-23 15:06 UTC, reaperrr commented
Updated, added deployed sensor array z-sorting fix.

2016-10-23 15:27 UTC, pchote commented
> or I already fixed it by accident somehow.

I can easily reproduce it on your old branch (which is still available behind 4d2aebe), but not on the current version.

2016-10-23 16:03 UTC, pchote approved these changes

2016-10-23 16:04 UTC, pchote approved these changes
The depth changes look good enough to merge now. :+1:

A future PR might want to add the iso depth sprite to billboards and the dam.  Some of the civ structures with dirt and junk around them could also use some tweaks, but I expect the behaviour here to match the original game, so I won't ask for that here.

2016-10-23 16:05 UTC, pchote commented
I've attached a map with all the editor-placeable actors, which I used with a rebased  4d2aebe for testing.

[depthtest.zip](https://github.com/OpenRA/OpenRA/files/546445/depthtest.zip)

2016-10-23 16:06 UTC, merged