Move production description from Tooltip to Buildable. #12045
OpenRA/OpenRA pull request #12141
Opened 2016-10-01 16:14 UTC by tysonliddell

Fixes #12045.

2016-10-01 20:46 UTC, reaperrr commented on mods/ts/rules/civilian-structures.yaml
> -# TODO: should use terrain lighting instead, depends on https://github.com/OpenRA/OpenRA/issues/3605
This probably slipped in after running the upgrade rules, please revert this removal.

2016-10-01 20:51 UTC, reaperrr commented on OpenRA.Mods.Common/Traits/Buildable.cs
> +		[Desc("Description moved from Tooltip.")]
Please restore the [Translate], you can simply put it on the line above.

2016-10-01 20:52 UTC, reaperrr commented on OpenRA.Mods.Common/Traits/Buildable.cs
> +		[Desc("Text shown in the production tooltip.")]
I think you should just fixup this commit into the first.

2016-10-01 20:54 UTC, reaperrr commented
I haven't tested this yet, but code and yaml looks good to me once the minor things I pointed out are dealt with.

2016-10-02 03:02 UTC, tysonliddell commented
Issues pointed out by reaperrr have been fixed up.

2016-10-02 16:08 UTC, reaperrr commented
One remaining issue and one "optional, but would be nice" thing:
- you forgot or accidentally discarded the changes to TS' `gdi-structures.yaml`.
- while it lacks one on bleed, it would be nice if you could add a simple `Produces structures.` desc to the D2K construction yard while you're at it.

:+1: after that.

2016-10-02 22:03 UTC, tysonliddell commented
Fixed up both additional points by reaperrr

2016-10-03 00:54 UTC, reaperrr approved these changes

2016-10-15 15:04 UTC, pchote requested changes
Sorry for the delay in looking at this, it looks good to merge but needs a rebase.  Let us know on IRC if you need help, or if you run into problems one of us can do the rebase and then push directly to your branch.

2016-10-15 15:04 UTC, pchote commented on OpenRA.Mods.Common/UtilityCommands/UpgradeRules.cs
> +                if (engineVersion < 20161001)
Can you please bump the date here while you're at it?

2016-10-15 15:05 UTC, pchote approved these changes

2016-10-16 01:21 UTC, tysonliddell commented
Rebased and date in UpgradeRules.cs updated.

2016-10-16 03:39 UTC, merged

2016-10-16 03:42 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bb10efb20aed29091ff036b9d9d3dbdb6edb8842