Fix yaks trying to attack invalid targets
OpenRA/OpenRA pull request #12160
Opened 2016-10-03 12:20 UTC by abcdefg30

Fixes #12128.
You can test this by placing a lot of camo pillboxes.

I removed the `yak.Wait(DateTime.Seconds(5))` as it just seems to make the yak stay in air without moving.

2016-10-03 13:07 UTC, Phrohdoh commented on OpenRA.Mods.Common/Scripting/Properties/CombatProperties.cs
> +		public bool IsValidTarget(Actor targetActor)
Shouldn't the `Attack` machinery be making this check instead of exposing this to scripters?

2016-10-03 13:17 UTC, abcdefg30 commented on OpenRA.Mods.Common/Scripting/Properties/CombatProperties.cs
> +		public bool IsValidTarget(Actor targetActor)
This was exactly the problem. The "Attack machinery" dropped the attack order, as the target was invalid, but the script retried and retried and retried to attack the target, which caused the error shown in #12128.

2016-10-04 00:20 UTC, pchote requested changes

2016-10-04 00:20 UTC, pchote commented on OpenRA.Mods.Common/Scripting/Properties/CombatProperties.cs
> +		public bool IsValidTarget(Actor targetActor)
This name is ambiguous, and used in the opposite way to the version used in the core code!

Please rename this to something like `CanTarget` to make it clearer.

2016-10-04 08:05 UTC, abcdefg30 commented
Updated.

2016-10-08 15:55 UTC, obrakmann commented
For some reason I can't create a PR against your repo, yours doesn't show up in the dropdown list. Could you please add this patch: https://github.com/OpenRA/OpenRA/commit/5eb244f7bc31b3d04f94a552b0dd4a3800742e36? Thanks.

2016-10-13 19:08 UTC, obrakmann approved these changes
Looks fine to me, 👍 

I'll PR my fix myself.

2016-10-14 16:55 UTC, reaperrr commented
:+1:

2016-10-14 16:55 UTC, merged

2016-10-14 16:58 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/b6b9b4cb6cfbb7974635b113821390e2e2028119...edb23e307db51538c7cb3258cd6223679215b4f7)