Allow only 2 Harvester at a refinery
OpenRA/OpenRA pull request #12178
Opened 2016-10-04 21:58 UTC by LipkeGu

Allow only 2 Harvester at a refinery

2016-10-04 22:05 UTC, pchote requested changes

2016-10-04 22:05 UTC, pchote commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +					if (occupancy >= 2)
This really should be pulled out to a trait parameter, it will be different for different mods.

2016-10-05 10:01 UTC, GraionDilach commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +					if (occupancy >= 2)
#3089 will disagree when this goes above than 2. I couldn't find the cause of that issue, but using xx== xxx= xx== foundations on the TS/RA2 refineries couldn't help. Although I guess it's related to the fact that sometimes when two harvesters arrive to the same refinery, one docks in to dump, then the other nudges it aside and the jamming maybe happens when a latecomer forces the already-at-docking position one to nudge away to a position which is already taken by the other latecomer.

2016-10-05 11:08 UTC, LipkeGu commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +					if (occupancy >= 2)
When you have tested it you will note that Harvesters will wait on the Field until the refinery is free for the next Harvester. the changes i have made minutes ago will filter out blocked refineries.

2016-10-05 11:12 UTC, LipkeGu commented
updated

2016-10-05 22:09 UTC, LipkeGu commented
updated

* Unhardcode occupancy and document it
* Unhardcode Targetline colors for harvesting / delivering
* Unhardcode Distance Cost and document it

* ClosestProc: Select closest free refinery

2016-10-05 22:13 UTC, pchote submitted a review, later dismissed

2016-10-05 22:13 UTC, pchote commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +		public readonly string DeliveringColor = "Gold";
FieldLoader understands `Color`, so there is no need for these to be strings.

2016-10-05 22:13 UTC, pchote commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +		public readonly int DistanceCost = 12;
This is an *occupancy* cost *modifier*, and not a distance or a raw cost.

2016-10-05 22:13 UTC, pchote commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +		internal bool ProcHasSpace(int occupancy)
Why are these `internal`?

2016-10-05 23:04 UTC, LipkeGu commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +		internal bool ProcHasSpace(int occupancy)
I took the Scheme from HackyAI should i make them private?

2016-10-05 23:06 UTC, LipkeGu commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +		public readonly int DistanceCost = 12;
In the Line commit it was named "distance multipler" i will rename it

2016-10-05 23:07 UTC, LipkeGu commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +		public readonly string DeliveringColor = "Gold";
Ok then i will Set mit to Color

2016-10-06 06:46 UTC, LipkeGu commented
updated

2016-11-27 15:45 UTC, reaperrr commented
@pchote I'm 'dismissing' your review since the PR was updated in the meantime, and it might put off other reviewers thinking there are unadressed requests.

2017-01-29 17:21 UTC, pchote commented
Superseded by #12645.

2017-01-29 17:21 UTC, closed without merging