Fix for #11505
OpenRA/OpenRA pull request #12232
Opened 2016-10-15 15:09 UTC by entropai

Fix for #11505 checks for valid stance now. Updated OnInside for additional disposing validation (othervise engineer would just enter and dispose)

2016-10-15 16:34 UTC, pchote submitted a review, later dismissed

2016-10-15 16:34 UTC, pchote commented on OpenRA.Mods.Common/Activities/Enter.cs
> +					var shouldDispose = OnInside(self);
This will also need to cover the suicide case: I suggest calling it `completed` or `valid` or similar.

2016-10-15 16:34 UTC, pchote commented on OpenRA.Mods.Common/Activities/CaptureActor.cs
> +			return false;
This should then return true.

2016-10-15 16:34 UTC, pchote commented on OpenRA.Mods.Common/Activities/CaptureActor.cs
> +			return false;
style nit: newline above,  since that is the end of a block.

2016-10-15 16:34 UTC, pchote commented on OpenRA.Mods.Common/Activities/Demolish.cs
> +            return false;
and likewise here.

2016-10-15 16:34 UTC, pchote commented on OpenRA.Mods.Common/Activities/EnterTransport.cs
> +            return false;
and here.

2016-10-23 12:59 UTC, pchote requested changes
Sorry for taking so long to get back to this.  The code changes look correct, although I haven't yet tested them.  Can you please use `git rebase -i` to squash all the commits together?  Ask in IRC if you need help on how to do that.

2017-01-02 19:07 UTC, reaperrr commented
Superseded by #12535.

2017-01-02 19:07 UTC, closed without merging