Move production icon sequence from Tooltip to Buildable
OpenRA/OpenRA pull request #12258
Opened 2016-10-18 20:03 UTC by reaperrr

Makes more sense, and saves us some `Tooltip` look-ups which also allows to make the latter upgradable more easily and regression-risk-free.

All yaml changes were done via upgrade rule, but because *all TD husk and barb wire/wood fence icon definitions were bogus* (never caught due to lack of `SequenceReference`), only the removals were staged for the C&C mod.

Prerequisite for #11984.

2016-10-21 00:29 UTC, pchote requested changes

2016-10-21 00:29 UTC, pchote commented on OpenRA.Mods.Common/UtilityCommands/UpgradeRules.cs
> +					if (tooltipChild != null || (tooltipChild = node.Value.Nodes.FirstOrDefault(n => n.Key == "DisguiseToolTip")) != null)
Reassigning `tooltipChild` inside the condition check is a bit dirty.  Can you change the line above to the following instead?
```csharp
var tooltipChild = node.Value.Nodes.FirstOrDefault(n => n.Key == "Tooltip")
    ?? node.Value.Nodes.FirstOrDefault(n => n.Key == "DisguiseToolTip");
```

2016-10-21 00:29 UTC, pchote commented on OpenRA.Mods.Common/Traits/Buildable.cs
> +		[Desc("Sequence of the actor that contains the cameo.")]
The original games called the icons "cameo"s, but we don't except for here and the legacy sequence importer (where we can't really avoid it).  Can you please change "cameo" &rarr; "production icon" or "sidebar icon" here?

2016-10-21 01:40 UTC, reaperrr commented
Updated.

2016-10-22 14:33 UTC, pchote approved these changes

2016-10-22 18:16 UTC, abcdefg30 commented on OpenRA.Mods.Common/UtilityCommands/UpgradeRules.cs
> +					var tooltipChild = node.Value.Nodes.FirstOrDefault(n => n.Key == "Tooltip")
Wouldn't it be simpler to use `var tooltipChild = node.Value.Nodes.FirstOrDefault(n => n.Key == "Tooltip" || n.Key == "DisguiseToolTip")`?

2016-10-22 18:24 UTC, abcdefg30 commented
Looks good to me otherwise. :+1: / :white_check_mark:

2016-10-22 18:30 UTC, reaperrr commented
Updated upgrade rule as suggested and updated engineVersion to today.

2016-10-22 18:33 UTC, Phrohdoh commented on OpenRA.Mods.Common/Traits/Buildable.cs
> +		[SequenceReference] public readonly string Icon = "icon";
`IconSequence` maybe.
This doesn't have to be changed because you're just moving code around, obviously.

2016-10-22 18:36 UTC, reaperrr commented on OpenRA.Mods.Common/Traits/Buildable.cs
> +		[SequenceReference] public readonly string Icon = "icon";
Basically I agree, but yeah I'd like to leave that for a separate PR, to get this dependency for #11984 out of the way asap.

2016-10-22 18:39 UTC, reaperrr commented
Updated, fixed the missing `;`.

2016-10-22 19:10 UTC, merged

2016-10-22 19:11 UTC, abcdefg30 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0d377ec6f40172897f9476162c0ff0b5a3b17a69...13d9557032d068cada727efbbede68f3a0ee673e)