More explicit interface cleanups
OpenRA/OpenRA pull request #12284
Opened 2016-10-22 16:34 UTC by reaperrr

Follow-up to #12268.

This one might need at least a bit of testing for potential regressions on sprite bodies, sprite turrets and armaments, though in my own testing I didn't encounter any issues.

To make up for it, the diff is a lot smaller this time.

- moves `INotifyDamageStateChanged` to mod code
- makes explicit interface implementation mandatory for the above and `INotifyBuildComplete`
- adresses a few more cases that previously made implicit interfaces overridable, preventing explicit implementations
- some more misc 'collateral' explicit implementations

2016-10-26 19:15 UTC, obrakmann approved these changes
Looks fine to me, 👍

2016-10-29 13:48 UTC, pchote requested changes

2016-10-29 13:48 UTC, pchote commented on OpenRA.Mods.Common/Traits/Armament.cs
> +		protected virtual void Initialize(Actor self)
Can we please keep the original names here?  Renaming them just adds confusion.

2016-10-29 13:48 UTC, pchote commented on OpenRA.Mods.Common/Traits/Armament.cs
> +			Initialize(self);
It would be worth a comment here explaining that the implementation is split into a protected method to allow subclassing.

2016-10-29 13:48 UTC, pchote commented on OpenRA.Mods.Common/Traits/Render/WithSpriteTurret.cs
> +		protected virtual void ReplaceSequenceWhenAiming(Actor self)
Here too (in subclasses it may have nothing to do with aiming).

2016-10-30 18:31 UTC, reaperrr commented
Updated as requested.

2016-10-30 18:40 UTC, pchote approved these changes

2016-10-30 18:40 UTC, merged

2016-10-30 18:41 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8351f8b5961e0157872325f1a4e30a69a3a12342