Fix error label not updating and split message into multiple labels
OpenRA/OpenRA pull request #12297
Opened 2016-10-23 20:57 UTC by Phrohdoh

`{filename}` was being replaced in the string upon first error so it did not exist later to be replaced again by any following errors.

![screen shot 2016-10-23 at 3 50 32 pm](https://cloud.githubusercontent.com/assets/4861023/19629364/6d3d2372-9939-11e6-90b4-fb652ada210b.png)

2016-10-23 21:01 UTC, Phrohdoh commented on OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
> +		bool IsErrorLabelVisible
This isn't public so should be `isErrorLabelVisible`.
Adding `changes requested` label because of this.

2016-10-23 21:13 UTC, abcdefg30 commented on OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
>  				if (errorLabelWidget != null)
You also need to `null` check `errorLabelFilename` somewhere around here.

2016-10-23 21:53 UTC, Phrohdoh commented
Do we actually need `ERROR_FILENAME` at this point?
This is only visible on the interface where the currently selected file is quite obvious.

2016-10-23 22:07 UTC, Phrohdoh commented
> OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs:L53: [SA1300] property names begin with an upper-case letter: isErrorLabelVisible.

😠

2016-10-24 14:28 UTC, Phrohdoh commented
@OpenRA/engine-hackers Opinions on changing the stylecop warning above (SA1300)?
I see no reason for a private member to be PascalCase, regardless of property, field, etc status.

2016-11-01 19:42 UTC, obrakmann commented
> Do we actually need ERROR_FILENAME at this point?

Not necessarily. I'd be fine with removing it. There are filenames that are too long to fit in the selection box on the left, though, as seen on your screenshot.

> I see no reason for a private member to be PascalCase, regardless of property, field, etc status.

Most of our properties usually are at least partly publicly accessible. That said, I'm fine with either.

2016-11-17 19:44 UTC, Phrohdoh commented
Fixed the case of the identifier.

2016-11-17 20:37 UTC, abcdefg30 commented on OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
> +					errorLabelFilename.GetText = () => WidgetUtils.TruncateText(filename, errorLabel.Bounds.Width, errorFont);
You check for `null` everywhere else, so why not here as well?

2016-11-17 20:48 UTC, abcdefg30 commented
Looks good to me. :+1: / :white_check_mark: after the nit has been addressed and the commits have been squashed.

2016-11-18 11:52 UTC, reaperrr commented
>  and the commits have been squashed.

2016-12-12 17:49 UTC, pchote requested changes
A simpler way to do this is to put both LabelWidgets inside a ContainerWidget in the yaml, then you separate out your concerns of visibility (on the container) vs label content (on the label itself) and avoid having to link visibility of multiple widgets together.

2017-01-29 17:36 UTC, pchote commented
Superseded by #12646.

2017-01-29 17:36 UTC, closed without merging