Fix the AmbientSound still playing when the actor is not in world
OpenRA/OpenRA pull request #12345
Opened 2016-11-03 17:01 UTC by abcdefg30

Also fixes the origin of the sound not being updated for moving actors.
Imho we should really remove the "hack" when interval is zero. It's just a mess, sounds awful and blocks expanding the features of that trait. You could also use the length of the sound track as interval anyways.

2016-11-05 19:38 UTC, pchote requested changes

2016-11-05 19:38 UTC, pchote commented on OpenRA.Mods.Common/Traits/Sound/AmbientSound.cs
> +			Game.Sound.StopSound(currentSound);
Please pull out a common `StopSound` method instead of duplicating this here and in Tick.

2016-12-19 22:11 UTC, abcdefg30 commented
Finally updated.

2016-12-23 12:11 UTC, pchote requested changes

2016-12-23 12:11 UTC, pchote commented on OpenRA.Mods.Common/Traits/Sound/AmbientSound.cs
> +				StopSound();
Why are you doing this twice? (here and `INotifyRemovedFromWorld.RemovedFromWorld`).  You should be able to remove one of these cases.

2016-12-23 12:11 UTC, pchote commented on OpenRA.Mods.Common/Traits/Sound/AmbientSound.cs
> +					// Otherwise the sound never gets stopped when the actor is on the move
This is kind of bogus.  If you cancel and restart the sound when the actor moves you will get serious s-s-s-stutt-stu-stutte-stuttering.

2017-01-30 22:44 UTC, pchote commented
I'm going to need these fixes plus some other changes to this trait for #11415, so i'm going to take this over and fix it myself.

2017-01-30 22:44 UTC, closed without merging

2017-02-01 21:32 UTC, pchote commented
Superseded by #12672.