Add a boolean expression parser
OpenRA/OpenRA pull request #12378
Opened 2016-11-12 23:54 UTC by pchote

This adds a quick and dirty (but still relatively efficient) parser for strings that define boolean expressions over runtime-defined variables.  It supports AND/OR/XOR/NOT and parentheses.  This will be used in future PRs that overhaul and simplify our prerequisite and upgrade declarations.

This comes with unit tests that verify correctness, so I'm hoping this will be a quick an easy review.

2016-11-13 01:36 UTC, Phrohdoh commented on OpenRA.Game/Support/BooleanExpression.cs
> +					throw new InvalidDataException("Unexpected character `!` at index {0}".F(tokens[i].Index));
Is there a concrete list of expected token types at the point of these exceptions?
If so those would be nice to include.

2016-11-13 02:12 UTC, pchote commented
Rewritten to use the postfix formulation as requested by @chrisforbes in IRC.  I've kept the original recursive version at [pchote/original-boolexpr](https://github.com/pchote/OpenRA/tree/original-boolexpr) for comparison.

2016-11-13 03:35 UTC, chrisforbes approved these changes

2016-11-13 03:35 UTC, chrisforbes commented on OpenRA.Test/OpenRA.Game/BinaryExpressionTest.cs
> +			AssertFalse("false || !true && !false");;
Stray semicolon here.

2016-11-13 03:35 UTC, chrisforbes commented on OpenRA.Test/OpenRA.Game/BinaryExpressionTest.cs
> +		[TestCase(TestName = "Precidence")]
Precedence (everywhere)

2016-11-13 03:54 UTC, pchote commented
Fixed.

2016-11-13 05:12 UTC, chrisforbes approved these changes

2016-11-15 19:44 UTC, phrohdoh requested changes
Please fix `!!false`.

2016-11-15 21:46 UTC, pchote commented
* Fixed `!!false` (adding plumbing for left vs right associativity) and added unit tests
* Added `==` operator and unit tests
* Renamed `^` to `!=`

2016-11-15 22:05 UTC, phrohdoh approved these changes
LGTM

2016-11-16 15:39 UTC, merged