Add TS Firestorm installation
OpenRA/OpenRA pull request #12429
Opened 2016-11-26 13:38 UTC by reaperrr

Supersedes #12113.

Fixed minor issues, added a quickinstall package and temporarily added alternative mirror lists.

Note: The mirrored packages will stay online at least until we have some additional mirrors, but the mirror list files of openra.net need to be updated before this is merged.

2016-11-26 17:33 UTC, Mailaender commented
Thanks! I uploaded the packages at http://openra.ppmsite.com/ and at the same time sent you the FTP password. http://www.bareftp.org/ had trouble in the past. Hopefully I didn't uploaded corrupted data again.

2016-11-27 12:36 UTC, pchote commented on mods/ts/rules/trees.yaml
> +		Name: Fona
Is "Fona" even a real word?

2016-11-27 12:39 UTC, pchote submitted a review, later dismissed

2016-11-27 12:39 UTC, pchote commented on mods/ts/rules/trees.yaml
> +		Name: Fona
Please use inheritance instead of repeating this 15 times.  Lets please also give it a better name if possible.

2016-11-27 12:39 UTC, pchote commented on mods/ts/rules/trees.yaml
> +	SeedsResource:
Is this supposed to seed blue tib, or is it static?

2016-11-27 13:04 UTC, reaperrr commented on mods/ts/rules/trees.yaml
> +	SeedsResource:
It actually is supposed to spawn tib, but at very low rate.

In any case, we can use inheritance here, too.

2016-11-27 13:14 UTC, reaperrr commented
Updated.

2016-11-27 18:22 UTC, Mailaender commented on mods/ts/rules/trees.yaml
> +		Name: Fona
> Is "Fona" even a real word?

I guess that happens when Nevada citizens pronounce "fauna". :-)

2016-11-27 18:30 UTC, reaperrr commented on mods/ts/rules/trees.yaml
> +		Name: Fona
Though "fauna" would still be at least questionable, since it refers to the animal part of "flora and fauna".

2016-11-27 18:43 UTC, Mailaender commented on mods/ts/rules/trees.yaml
> +		Name: Fona
Yeah, probably 90s character length limitations then.

2016-11-27 18:52 UTC, reaperrr commented on mods/ts/rules/trees.yaml
> +		Name: Fona
Well, with Westwood you never know. They might just have mixed them up, in addition to the spelling. Or it's meant to indicate that these 'plants' are more like immobile aliens of sorts.

2016-12-06 07:06 UTC, LipkeGu commented
I was a time away due to prsonal problems thanks that anyone keeps it on... sorry

2016-12-14 13:09 UTC, reaperrr commented
Depends on https://github.com/OpenRA/OpenRAWeb/pull/330

2016-12-14 13:11 UTC, pchote commented
This is on my short list of PRs I want to review and merge, but I haven't quite got to it yet, sorry.

2016-12-17 13:30 UTC, pchote requested changes
Looks good, just a couple of minor TODOs:

2016-12-17 13:30 UTC, pchote commented on mods/ts/installer/downloads.yaml
> +	MirrorList: http://tdx.ppmsite.com/openra-ts/fs-mirrors.txt
You can now change these to the proper urls.

2016-12-17 13:30 UTC, pchote commented on mods/ts/installer/firestorm.yaml
> +	IDFiles:s
Stray `s`?

2016-12-17 15:05 UTC, reaperrr commented
Updated.

2016-12-17 15:07 UTC, pchote approved these changes

2016-12-18 15:03 UTC, GraionDilach approved these changes
:+1:

2016-12-18 15:07 UTC, merged