Upgrades overhaul part 4a: UpgradeActorsNear -> ProximityExternalCondition
OpenRA/OpenRA pull request #12449
Opened 2016-12-02 16:34 UTC by pchote

Depends on #12406.

2016-12-09 23:48 UTC, pchote commented
Rebased and ready for review.

2016-12-11 19:46 UTC, obrakmann requested changes

2016-12-11 19:46 UTC, obrakmann commented on OpenRA.Mods.Common/Traits/Upgrades/UpgradeActorsNear.cs
> +	public class ProximityExternalConditionInfo : ITraitInfo
Why didn't you rename the file as well?

2016-12-11 19:46 UTC, obrakmann commented on OpenRA.Mods.Common/Traits/Upgrades/UpgradeActorsNear.cs
> +					tokens[produced] = um.GrantCondition(produced, info.Condition);
Shouldn't you also set the `external` flag here?

2016-12-11 19:46 UTC, obrakmann commented on OpenRA.Mods.Common/UtilityCommands/UpgradeRules.cs
> +				if (engineVersion < 20161202)
Don't forget to update this eventually.

2016-12-11 19:46 UTC, obrakmann commented on mods/ra/maps/allies-03a/rules.yaml
> +		Conditions: jail
You need to do this for the medics as well here, and for both medics and hacke6 in 3b.

2016-12-12 14:29 UTC, pchote commented
Fixed and rebased.

2016-12-12 18:07 UTC, obrakmann approved these changes

2016-12-12 19:29 UTC, reaperrr commented on OpenRA.Mods.Common/Traits/Upgrades/ProximityExternalCondition.cs
> +				if (um != null && um.AcceptsExternalCondition(produced, info.Condition))
I assume this is intentional, but I'm struggling to get my head around why this doesn't need a `ContainsKey` check, could you elaborate a bit?

2016-12-12 19:38 UTC, reaperrr commented on OpenRA.Mods.Common/Traits/Upgrades/ProximityExternalCondition.cs
> +				if (um != null && um.AcceptsExternalCondition(produced, info.Condition))
Okay, thanks.

2016-12-12 19:39 UTC, reaperrr commented
👍

2016-12-12 19:39 UTC, merged

2016-12-12 19:41 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f2bc3962fcf89a42e0989239f847006b46accafa...6894f77f04517a6684ad581fdea1a8fbe92fe7cf)