Slim down D2k weapon yamls
OpenRA/OpenRA pull request #12515
Opened 2016-12-28 13:01 UTC by reaperrr

This downsizes the weapon yaml files and makes it a bit easier to apply wider-scale changes like #12513 later.

2017-01-15 20:44 UTC, pchote requested changes
Some minor regressions to fix, otherwise looks good.

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/largeguns.yaml
> +	Inherits: ^Cannon
This changes `Inaccuracy` from undefined (i.e. 0) to 380.

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Rocket
This changes `HorizontalRateOfTurn` from 1 to 0.

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Missile
This changes `TrailPalette` from undefined to `effect75alpha`.  Probably a good thing (I haven't tested)?

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/missiles.yaml
> -		Inaccuracy: 96
This changes the inaccuracy to 384.

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Missile
This changes `TrailPalette` from undefined to `effect75alpha`.

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Missile
This adds a `MinRange: 1c0` that didn't exist before.  Probably a good thing.

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/smallguns.yaml
> -	Delay: 5
This removes the delay completely (it isn't defined in `M_HMG`).

2017-01-15 20:44 UTC, pchote commented on mods/d2k/weapons/smallguns.yaml
>  HMG_muzzle:
My comparison shows that these are missing the `InstantHit` projectile, so I guess you need to rebase.

2017-01-15 22:12 UTC, reaperrr commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Rocket
They weren't tracking in the original, this is intentional.

2017-01-15 22:16 UTC, reaperrr commented on mods/d2k/weapons/smallguns.yaml
>  HMG_muzzle:
Ah, right, forgot about that.

2017-01-15 22:17 UTC, reaperrr commented on mods/d2k/weapons/smallguns.yaml
> -	Delay: 5
For weapons, just `Delay` is a bogus property. I haven't checked where this came from, but in all likelyness a rebase error.

2017-01-15 22:21 UTC, pchote commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Rocket
Ah, I see.  Would it make sense to change these to an arcing Bullet like we use for non-guided projectiles in RA and TD?

2017-01-19 21:35 UTC, reaperrr commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Missile
Intentional, yes. They were transparent in the original.

2017-01-19 21:35 UTC, reaperrr commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Missile
See above.

2017-01-19 21:36 UTC, reaperrr commented on mods/d2k/weapons/missiles.yaml
> +	Inherits: ^Rocket
I guess it wouldn't hurt.

2017-01-19 21:49 UTC, reaperrr commented on mods/d2k/weapons/missiles.yaml
> -		Inaccuracy: 96
Fixed.

2017-01-19 21:55 UTC, reaperrr commented
Rebased and updated.

Made some changes:
- unguided rockets now use Bullet
- reduced missile `MinRange` to `0c512`, otherwise they'd miss diagonally passing vehicles and adjacent infantry on closer subcells.
- Removed explosion sound from gun turret cannon, because the sound was annoying and the original didn't have it, either.

2017-01-21 16:48 UTC, pchote approved these changes

2017-01-21 23:06 UTC, abcdefg30 commented
Looks good to me. :+1: / :white_check_mark:

2017-01-21 23:06 UTC, merged