Implement experience multipliers.
OpenRA/OpenRA pull request #12572
Opened 2017-01-12 18:02 UTC by GraionDilach

Requested by Crystallized Doom basically, but it was something I also wanted to add on my own anyway.

Implement two interfaces for experience multiplying both on giver (for things like increasing ranked-up actor's experience worth) and receiver side (for things like Generals's USA Advanced Training upgrade).

2017-01-12 18:15 UTC, reaperrr commented
> OpenRA.Mods.Common/Traits/GivesExperience.cs:L62: [SA1118] The parameter spans multiple lines. If the parameter is short, place the entire parameter on a single line. Otherwise, save the contents of the parameter in a temporary variable and pass the temporary variable as a parameter.

2017-01-12 18:22 UTC, GraionDilach commented
Okay, now that is a StyleCop error I haven't seen before. Fixed now.

2017-01-15 15:02 UTC, pchote requested changes
:+1: after fixing a couple of minor style nits.

2017-01-15 15:02 UTC, pchote commented on OpenRA.Mods.Common/Traits/GivesExperience.cs
> +				var killerexpmodifier = new[] { info.ActorExperienceModifier }
Style nit: camelCase for variable names.

The LINQ can also be simplified a bit:
```csharp
var killerExperienceModifier = e.Attacker.TraitsImplementing<IGainsExperienceModifier>()
	.Select(x => x.GetGainsExperienceModifier())
	.Append(info.ActorExperienceModifier);

```

2017-01-15 15:02 UTC, pchote commented on OpenRA.Mods.Common/Traits/GivesExperience.cs
> +			Util.ApplyPercentageModifiers(exp, self.TraitsImplementing<IGivesExperienceModifier>().Select(x => x.GetGivesExperienceModifier()));
This line is a bit longer than i'd like.  Please pull out a 
```csharp
var experienceModifier = self.TraitsImplementing<IGivesExperienceModifier>()
	.Select(x => x.GetGivesExperienceModifier())
```

2017-01-15 19:33 UTC, GraionDilach commented
Updated.

2017-01-19 20:42 UTC, RoosterDragon commented
:+1:

2017-01-19 20:42 UTC, merged

2017-01-19 20:43 UTC, RoosterDragon commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/32de3e91d0ace986f902bce38f65cc827d05449c)