Replace "Debug" prefix with "Battlefield Control" for win/loss messages.
OpenRA/OpenRA pull request #12643
Opened 2017-01-29 16:53 UTC by pchote

This also introduces a `SuppressNotifications` flag that maps can use to disable the default messages if they want to display something different using Lua.

2017-01-29 17:04 UTC, pchote commented
Added the other messages from #12387, which I had forgotten about.

2017-01-29 18:53 UTC, obrakmann requested changes
Looks otherwise fine, 👍

2017-01-29 18:53 UTC, obrakmann commented on OpenRA.Mods.Common/Traits/Player/ConquestVictoryConditions.cs
> +				return;
You'll probably want to move that to below the `foreach`, otherwise it would be suppressing more than just the notifications.

2017-01-29 19:00 UTC, pchote commented on OpenRA.Mods.Common/Traits/Player/ConquestVictoryConditions.cs
> +				return;
Could have sworn that i'd done that... anyway, fixed.

2017-01-29 19:21 UTC, obrakmann approved these changes

2017-01-31 19:28 UTC, GraionDilach approved these changes
LGTM. :+1:

2017-02-01 10:25 UTC, chrisforbes approved these changes

2017-02-01 19:18 UTC, merged

2017-02-01 19:19 UTC, RoosterDragon commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d303f7b826f7d4d4a50aecbb5277744895cb2693)