Fix the ProneOffsets of TakeCover
OpenRA/OpenRA pull request #12684
Opened 2017-02-03 23:47 UTC by abcdefg30

On current bleed the bullets of prone infantry are instantly blocked. Also see #12683.

2017-02-04 11:23 UTC, pchote requested changes
There are quite a few issues with the new offsets in the shipping mods.  I haven't checked TS.

2017-02-04 11:23 UTC, pchote commented on mods/cnc/rules/infantry.yaml
> +		ProneOffset: 400,0,-256
This looks quite wrong ingame.

2017-02-04 11:23 UTC, pchote commented on mods/cnc/rules/infantry.yaml
> +		ProneOffset: 400,0,-256
This looks quite wrong ingame.

2017-02-04 11:23 UTC, pchote commented on mods/d2k/rules/infantry.yaml
> +		ProneOffset: 300,0,-224
This looks quite wrong ingame.

2017-02-04 11:23 UTC, pchote commented on mods/ra/rules/infantry.yaml
> +		ProneOffset: 500,0,-341
This is too far forward too.  Make sure that you use the combat debug overlay and compare the muzzle position before and after going prone.

2017-02-04 11:23 UTC, pchote commented on mods/ra/rules/infantry.yaml
> +		ProneOffset: 500,0,-341
This is quite wrong, and I just noticed that the standing fire offsets are wrong too:

![screen shot 2017-02-04 at 11 19 11](https://cloud.githubusercontent.com/assets/167819/22618079/ef70374c-eacb-11e6-8af7-557c7b25e9c6.png)
"It burns when I pee!"

2017-02-04 11:23 UTC, pchote commented on mods/ra/rules/infantry.yaml
> +		ProneOffset: 0,0,-555
This is off too.

2017-02-04 11:52 UTC, reaperrr commented
I'm beginning to wonder whether we should add a boolean to completely disable the terrain height check or a lenience threshold to `Bullet` afterall, as this feature right now it seems to only increase regression risk for 2D mods.

2017-02-04 11:54 UTC, pchote commented
It is only regressing things that were already bogus, so while it is painful for everyone my preference is to fix the bogus things.

2017-02-04 14:17 UTC, abcdefg30 commented
While I often don't agree with your nits, I tried to adjust the values even further and hope it's ok for you now.

2017-02-05 11:11 UTC, pchote commented
We have a visualization specifically for setting up these firing offsets, so I don't think there is a good excuse for not having these set up properly.

Consider the d2k grenadier:
![grenadier](https://cloud.githubusercontent.com/assets/167819/22625578/9d1b3f2e-eb92-11e6-914f-2e4de71826f7.png)

The square end of the indicator should line up with the end of the barrel (in this case the position of the infantry's hand at the end of the throw).  The low resolution makes it kind of hard to guess, but the current position in this PR (white indicator) is quite clearly off from my best guess (red indicator).

I'd say that the current position is about 2px too far from the center of the actor, and about 4px too low.  D2k uses 32 WDist per pixel, so that means that the `x` offset needs to be reduced by ~64 and the `z` offset increased by ~128.  Tweaking the offset to `128,0,-96` does indeed look much better ingame.  There is an ambiguity between the `y` and `z` offsets when looking to the sides and the `x` and `z` offsets when looking north/south, but that can be resolved by checking the infantry from the four main facings.

2017-02-05 12:19 UTC, GraionDilach commented
>We have a visualization specifically for setting up these firing offsets

I wouldn't call it that way. Yes, it shows the current used offsets, but you still have to guesswork the actual values AND you have to restart the game for every guess. If DebugCombatOverlay would have an interface to change the currently selected unit's firing indicator position with dev commands alone, then I'd say that is correct.

2017-02-05 12:22 UTC, pchote commented
Sure, but it's more precise than just guesswork: the relationship between WDist and screen pixels are known, so it shouldn't take more than a couple of iterations to set up each actor if you're able to visualize the multiple 2d views -> 3d coordinates in your head.

2017-02-05 12:26 UTC, GraionDilach commented
When the modder ends up with a loading time over a minute, turret offsets, different voxel scales (not talking about RenderVoxels here but the proper Scale in voxel header) even those couple of iterations would take a good while. The relationship between WDist and screen pixels are only known easily in gen1 mods, it's more complex in isometric.

2017-02-05 13:34 UTC, pchote commented
That's better discussed in its own issue, because this PR doesn't involve long loading times, turret offsets, or voxel scales.

2017-02-08 19:16 UTC, abcdefg30 commented
Rebased and updated.

2017-02-12 16:00 UTC, pchote approved these changes

2017-02-12 19:30 UTC, reaperrr approved these changes

2017-02-12 19:31 UTC, merged

2017-02-12 19:35 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c1197e2c261d84b4d85f9f3d408107d6e824d31f...2774d81adc66ad2df1e1f7d81ed25313405169e1)