Fix GiveUnitCrateAction being limited to MobileInfo
OpenRA/OpenRA pull request #12730
Opened 2017-02-09 12:16 UTC by abcdefg30

You can now also spawn aircraft and crates.

2017-02-09 12:53 UTC, reaperrr commented
This should also allow aircraft as starting units. Nice!

2017-02-09 13:06 UTC, abcdefg30 commented
Good idea! Added it.

2017-02-09 13:45 UTC, pchote commented on OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
> +				var ios = actorRules.TraitInfo<IOccupySpaceInfo>();
IPositionable inherits IOccupySpace, so this should not be required.

2017-02-09 13:46 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
> +				var ios = actorRules.TraitInfo<IOccupySpaceInfo>();
We use the `Info` classes and `IPositionableInfo` doesn't inherit `IOccupiesSpaceInfo` afaik.

2017-02-09 13:49 UTC, pchote commented on OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
> +				var ios = actorRules.TraitInfo<IOccupySpaceInfo>();
That is a bug that needs to be fixed.

2017-02-09 14:06 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
> +				var ios = actorRules.TraitInfo<IOccupySpaceInfo>();
Fixed.

2017-02-09 16:42 UTC, GraionDilach approved these changes
:+1:

2017-02-09 16:45 UTC, GraionDilach requested changes
Wait... no, you should drop IOccupySpaceInfo from CrateInfo, AircraftInfo and co. now.

2017-02-09 19:10 UTC, abcdefg30 commented
Fixed.

2017-02-09 19:13 UTC, GraionDilach approved these changes
:+1:

2017-02-09 19:16 UTC, pchote commented on OpenRA.Mods.Common/Traits/Air/Aircraft.cs
> +		// Used to determe if an aircraft can spawn landed
> determe

2017-02-09 19:17 UTC, pchote commented on OpenRA.Mods.Common/Traits/Mobile.cs
> -		IFacing, ISync, IDeathActorInitModifier, INotifyAddedToWorld, INotifyRemovedFromWorld, INotifyBlockingMove, IActorPreviewInitModifier
erm, why are you removing `ISync`?

2017-02-09 21:04 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/Mobile.cs
> -		IFacing, ISync, IDeathActorInitModifier, INotifyAddedToWorld, INotifyRemovedFromWorld, INotifyBlockingMove, IActorPreviewInitModifier
`ConditionalTrait<MobileInfo>` implements `ISync` already.

2017-02-09 21:05 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/Air/Aircraft.cs
> +		// Used to determe if an aircraft can spawn landed
Woops, fixed.

2017-02-12 12:59 UTC, reaperrr commented
Spawning `heli` either as starting unit or crate action in RA doesn't work for me. There isn't any crash, but the heli just doesn't appear, either.

2017-02-12 16:12 UTC, abcdefg30 commented
> Spawning `heli` either as starting unit or crate action in RA doesn't work for me. There isn't any crash, but the heli just doesn't appear, either.

You're probably missing the correct `LandableTerrainTypes` definitions in yaml.

2017-02-12 16:26 UTC, reaperrr commented
> You're probably missing the correct LandableTerrainTypes definitions in yaml.

Ok, that works.
In the future I'd like to see support for aircraft starting mid-air, so the terrain doesn't matter, but for this PR it's good enough.

2017-02-12 16:27 UTC, reaperrr approved these changes

2017-02-12 16:27 UTC, merged

2017-02-12 16:30 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/79f8f3f9af0d1e1b1314d5c386bdd5c3396794c7...5cc60976fd73e0c093a4615ff80f93858edcbedb)