Add atreides05
OpenRA/OpenRA pull request #12785
Opened 2017-02-15 21:28 UTC by abcdefg30

Depends on #12784.
I also still need to get the colors for Smugglers and Mercenaries (which I'll do tomorrow).

2017-02-15 23:18 UTC, Micr0Bit approved these changes
theres one thing i dont like ... that units dive into the shroud on top and bottom edge of the map

but i assume that has nothing to do with the mission itself ? 

regardless, i finished the mission without any technical problems :+1:

2017-02-16 04:41 UTC, MustaphaTR commented
I used DDDD00 for mercenaries and 542209 for smugglers in my older maps (and Ord4 for smugglers too).

2017-02-16 11:25 UTC, MustaphaTR requested changes

2017-02-16 11:25 UTC, MustaphaTR commented on mods/d2k/maps/atreides-05/atreides05-AI.lua
> +HarkonnenHeavyVehicleTypes = { "combat_tank_h", "missile_tank" }
AI doesn't have an IX Lab in this mission. So it shouldn't be able to build Missile Tank.

2017-02-16 14:30 UTC, MustaphaTR commented
We can't build combat tank from Starport.

Also i like the fact that Contrabants contain Ordos Tanks not Atreides. This wasn't the case in original even tho it was possible.

I feel like it would be better if Combat Tank we can buy from Smugglers was Ordos too, it is a Smugglers Starport. We can still build atreides ones from HFac. But that's just my idea.

2017-02-16 14:47 UTC, MustaphaTR commented on mods/d2k/maps/atreides-05/atreides05.lua
> +			unit.AttackMove(HarkonnenAttackLocation)
Mercenaries attack the starport base first, if there is still a base, in original game, not main base.

2017-02-16 22:49 UTC, abcdefg30 commented on mods/d2k/maps/atreides-05/atreides05-AI.lua
> +HarkonnenHeavyVehicleTypes = { "combat_tank_h", "missile_tank" }
Oh, ops. Thanks fixed.

2017-02-16 22:50 UTC, abcdefg30 commented
> I feel like it would be better if Combat Tank we can buy from Smugglers was Ordos too, it is a Smugglers Starport. We can still build atreides ones from HFac. But that's just my idea.

Good idea. I added that.

> I used DDDD00 for mercenaries and 542209 for smugglers in my older maps (and Ord4 for smugglers too).

Also thanks. I think they fit.

2017-02-17 05:29 UTC, MustaphaTR commented on mods/d2k/maps/atreides-05/rules.yaml
> +		CanHover: true # The firgate would teleport to land otherwise
Frigate is misspelt on comment.

2017-02-20 14:16 UTC, MustaphaTR commented
Needs rebase.

2017-02-20 14:41 UTC, MustaphaTR commented
This walls and gun turret is lacking concrete below:
![concrete](https://cloud.githubusercontent.com/assets/7933210/23129432/55b056ba-f78b-11e6-88a0-f6d0df133e43.png)

2017-02-20 15:34 UTC, abcdefg30 commented
Rebased and updated.

2017-02-20 15:41 UTC, MustaphaTR commented
AI in original mission do train infantry. I tested with Debug Menu in Gruntmods Edition. Looks like it is missing here. Don't forget to add `upgrade.barracks` too.

2017-02-20 17:32 UTC, MustaphaTR commented
If i sell starport, Defend Starport mission doesn't fail.

2017-02-20 17:43 UTC, MustaphaTR commented
Sardaukar is visible and buildable if you have hi-tech fac. after i capture Harkonnen Barracks/capture the CYard and build a Barracks.

2017-03-01 17:34 UTC, HenrytheSlav commented
Please add the .lua files to [OpenRA.sln](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.sln#L101).

2017-03-18 13:12 UTC, reaperrr commented
#12784 was merged.

2017-03-18 15:26 UTC, abcdefg30 commented
Rebased and updated.

2017-03-18 18:47 UTC, MustaphaTR approved these changes
:+1:

2017-04-04 15:34 UTC, ltem approved these changes
:+1: Quite a challenge :)
One small nit...

2017-04-04 15:37 UTC, ltem commented on mods/d2k/maps/atreides-05/atreides05.lua
> +	KillHarkonnen = player.AddSecondaryObjective("Annihilate all other Harkonnen units and reinforcements.")
A line break would be nice here

2017-04-04 21:24 UTC, abcdefg30 commented
Rebased and updated.

2017-04-05 19:39 UTC, ltem approved these changes

2017-04-06 12:37 UTC, MustaphaTR approved these changes

2017-04-12 06:57 UTC, MustaphaTR commented
@reaperrr , can you take a look to this when you have time. It already have 2 approvals but waiting for merge for a while.

2017-04-12 17:25 UTC, reaperrr approved these changes

2017-04-12 17:26 UTC, merged

2017-04-12 17:27 UTC, reaperrr commented
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/dedef53bdb8c57553a81d1f9eff055ddd7388494...d067edd38d9db0c63dd56f7609c49eb18538117f)