Fix contrail gets rendered between loading in and loading out position
OpenRA/OpenRA pull request #12882
Opened 2017-03-03 17:01 UTC by abc013

Closes #12877.

Another option would be to create a new `ContrailRenderable` in `AddedToWorld`, right?

2017-03-03 17:12 UTC, pchote commented
> Another option would be to create a new `ContrailRenderable` in `AddedToWorld`, right?

Indeed, and this would be the better option.

2017-03-05 12:20 UTC, abc013 commented
Updated.

2017-03-06 17:13 UTC, abcdefg30 commented on OpenRA.Mods.Common/Effects/Contrail.cs
>  			trail = new ContrailRenderable(self.World, color, info.TrailWidth, info.TrailLength, 0, info.ZOffset);
Hm, I think you could remove this now.

2017-03-08 13:33 UTC, abc013 commented on OpenRA.Mods.Common/Effects/Contrail.cs
>  			trail = new ContrailRenderable(self.World, color, info.TrailWidth, info.TrailLength, 0, info.ZOffset);
oh, updated it.

2017-03-08 23:22 UTC, GraionDilach approved these changes
:+1:

2017-03-18 13:30 UTC, reaperrr commented
When giving a Minigunner a Contrail, I got this:
https://gist.github.com/reaperrr/148110d46f831133f96614c23f40a6cd

2017-03-18 13:33 UTC, reaperrr requested changes
NRE needs fixing.

2017-03-19 08:17 UTC, abc013 commented
You got it directly after the game started, right?

2017-03-19 08:28 UTC, abc013 commented
Everything should work now. 
The problem was that i removed [this line](https://github.com/OpenRA/OpenRA/pull/12882/files#diff-e29caa227c349dfcbce4dda50b7282aaR59).

2017-03-19 15:29 UTC, reaperrr approved these changes

2017-03-19 22:03 UTC, abcdefg30 approved these changes

2017-03-19 22:03 UTC, merged

2017-03-19 22:04 UTC, abcdefg30 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1a9afe8f752a3c3a94fe7a8075496815c458cf14...13977f5171a13d9428f563ba4cd87348545b5808)