Reorganize Windows game launcher to support per-mod launchers.
OpenRA/OpenRA pull request #12966
Opened 2017-03-14 17:52 UTC by pchote

This sets up our windows launcher and packaging to support per-mod launchers for both https://github.com/OpenRA/OpenRAModTemplate and our official mods once we drop the mod chooser.  This is the Windows equivalent of #12824 / https://github.com/OpenRA/OpenRALauncherOSX/pull/2.

https://github.com/pchote/OpenRA/commit/a16576a464b74d1bfcc3cd7e4fde24111d2f47bd shows how this will work for per-mod launchers in a future pr (which is currently blocked by #12909 and some other installer changes).  For now this continues to build a mod-independent OpenRA.exe launcher.

A test installer built using our normal packaging scripts can be found [here](https://www.dropbox.com/s/i7zomvw2su2dbdf/OpenRA-test-20170314.exe?dl=0).  The appveyor test builds (which work quite differently to our normal packaging) may take a couple of test/fix cycles to get working, so hold tight if they are failing when you see this.

2017-03-27 12:37 UTC, reaperrr approved these changes
Looks good to me, and both provided test builds as well as my own compile worked.

2017-04-11 10:31 UTC, abcdefg30 requested changes
Looks like the removal/moving of `GameMonitor.cs` got lost somewhen during the process.

2017-04-11 10:31 UTC, abcdefg30 commented on packaging/windows/WindowsLauncher.cs.in
> +			public IntPtr hIcon; // original type: HICON
Comments usually go on their own line, starting with a capital letter. (Same for the two other comments below.)

2017-04-11 16:19 UTC, pchote commented
Fixed and rebased.

2017-04-11 23:21 UTC, abcdefg30 requested changes
So, with this `make all` doesn't create `OpenRA.exe` and `OpenRA.Game.exe` anymore. Am I missing something here?

2017-04-12 07:45 UTC, pchote commented
Not creating OpenRA.exe is intentional:
1.  We have a launch-game.cmd that is more appropriate, including a mod selector instead of requiring a separate exe to be compiled per mod.
2.  We don't build any other platform specific launchers, why should windows be special?
3.  Building the launchers is non-trivial, and i'm strongly against having to maintain multiple different scripts to do this without a very good reason.

This does create `OpenRA.Game.exe`...?  I just tested this again to be certain, using `make.cmd` on a clean checkout.

2017-04-12 17:30 UTC, reaperrr commented
> This does create OpenRA.Game.exe...? I just tested this again to be certain, using make.cmd on a clean checkout.

It works here as well.

@abcdefg30 Maybe you overlooked it because it doesn't have the RA icon anymore?

2017-04-13 13:31 UTC, abcdefg30 approved these changes
Weird. I must have messed something up. Did a clean checkout and it works now.

2017-04-13 13:34 UTC, merged