Grenadier death explosion fixed
OpenRA/OpenRA pull request #12960
Opened 2017-03-13 19:30 UTC by 14thFortnight

During his "empty ammo" state the Grenadier uses the incorrect weapon for his death explosion. I explained it more in-depth during the commit:

- When the Grenadier throws his grenade he enters a state of being "empty" for a while (until his ammo is reloaded and he can throw again). If he is killed and explodes upon death during this "empty state" the Explodes trait will use "EmptyWeapon" instead of "Weapon".

- EmptyWeapon has however not been set to anything in infantry.yaml and therefore defaults to "UnitExplode" - an explosion that is over 12 times stronger than "UnitExplodeSmall" and covers a larger area.

- What this commit does is make sure the Grenadier's death explosion will always have the same strength. My reasoning is that it was probably never intended for the bang to be so strong in the first place, especially since it happens when the unit has no ammo loaded.

This is something I disovered when making the so-called ["overhaul"](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19940) and thought it would be perfect as a test commit since it's such a simple fix yet can have such a big impact on gameplay. Using GitHub is relatively unfamiliar for me so I'm still learning the ropes.

2017-03-13 19:45 UTC, pchote commented
This was discussed and rejected in #10114 / #12728.  This started as a bug, but has been promoted to a feature for reasons that I don't completely agree with.

2017-03-13 20:23 UTC, 14thFortnight commented
I see, it would probably be a good idea to change the yaml to this instead:

`Weapon: UnitExplode
EmptyWeapon: UnitExplode`

That way everybody will know the explosion strength is intentional and it will be consistent regardless whether the unit has attacked or not. I was 100% sure I had found a bug/oversight and at first I thought there was a bug with the trait itself as well since when I force-attacked my own guys into killing Grenadiers they would explode normally with UnitExplodeSmall. Took a while before I realized it was because they had not attacked and wasn't considered empty by the game.

I think I won't be the last to think this is a bug unless the yaml is changed to make intentions super clear. Are we sure everybody still want them to use UnitExplode? After a quick look the only other thing in the game that seems to be using UnitExplode is "^AmmoBox" in default.yaml, crashing aircrafts and V2 Rocket.

Wait a minute, empty harvesters and empty minelayers also use UnitExplode. Do we want that? Meanwhile a fully loaded harvester get the OreExplosion which deals almost no damage.

Also, V2 Rocket uses V2Explode when loaded and UnitExplode when empty. That means when the V2 Rocket is empty the explosion AOE is 25% larger and does 11% more damage, surely something that doesn't make sense. Meanwhile the Artillery has explosions defined for both loaded (ArtilleryExplode) and unloaded (UnitExplodeSmall).

2017-03-13 20:52 UTC, 14thFortnight commented
After reading the issues you linked to it seems like MustaphaTR resurrected the discussion after reading about it in [this forum post](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=299646#299646) (judging by the dates).

Seems like SoScared wants them to be more vulnerable after attacking and not so vulnerable before starting their attack. So then the yaml should be:
`Weapon: UnitExplodeSmall`
`EmptyWeapon: UnitExplode`
Exactly like it is today, just more clear that it is intentional and not a bug. I could make a new commit with those changes. Maybe overlook the V2 Rocket/Harvester/Minelayer explosions as well?

Personally I'd rather have it the other way around and see if it really changes gameplay all that much in the next patch. That cat and mouse play that was talked about in #12728 gets mitigated by the 50% random chance that the death explosion even occurs in the first place, wouldn't it bring more strategic consistency if the explosions deals a reasonable amount of damage instead and has a 100% chance of occurring? Then if it turns out too weak or too strong you can just tweak the damage of the death explosion or grenades vs wood armor. As it is now because of the 50% explosion chance it's a lottery, something that is much harder to balance.

2017-03-13 20:56 UTC, 14thFortnight commented
Sorry for triple posting, still learning the ropes at GitHub. Want to try pinging @SoScared, did I do that right? Haha, let's see if he turns up to leave a comment.

2017-03-14 09:34 UTC, 14thFortnight commented
After actually testing and checking "^Vehicle" that V2 Rocket inherits from it has the Explodes trait with "EmptyWeapon: UnitExplodeSmall" defined after all. So an empty V2 Rocket does very little damage compared to a loaded V2 Rocket after all and both Artillery and V2 Rocket uses UnitExplodeSmall when destroyed while empty. But there doesn't seem to be a reason why Artillery is defining its EmptyWeapon explosion since it inherits from ^Tank, which inherits from ^Vehicle so it should already have UnitExplodeSmall as EmptyWeapon like all other vehicles.

I noticed that I can't get the minelayer's empty explosion to trigger, seems like it is always considered loaded even when it has 0 mines? Could this be because it has no Armament trait? The unit does only define "Weapon" in their Explodes traits so the "EmptyWeapon" defined in ^Vehicle should be inherited.

The minor issue of a fully loaded Harvester dealing less damage (0) than an empty Harvester when exploding still remains.

2017-03-18 13:22 UTC, SoScared commented
Could you quickly summarize the change to precisely what it does which skips the hows and whys? It's not that I'm lazy but I tend to minimize speculation and hypothesizing as much as possible when it comes to pull requests. Better to save that for Issues and forums posts imo.

2017-03-18 15:53 UTC, SoScared commented
I'm personally not invested in the grenadier change but I know there are a lot of people who are given how ingrained grenadiers has become in the early-game - hence my opinion on #10114 and #12728. If this issue is urgent in relation to the next playtest/release I recommend calling in more active RA players/reviewers. @Smittytron, @ChristianDK, @abcdefg30

2017-03-18 16:04 UTC, FrameLimiter commented
Summary:
Giving the grenadier EmptyWeapon: UnitExplodeSmall is overriding the default value of UnitExplodes (which is what makes them die in a large chain reaction).
I don't like this change as I think it'll make the grenadier too strong when used in large numbers.

2017-03-18 16:16 UTC, abcdefg30 commented
I'd vote for giving it a try in one of the playtest *after* the next release. I don't see grenadiers used often, maybe this makes them better. The should still die easily against rifles after all.

2017-03-18 18:42 UTC, Smittytron commented
I don't mind testing with a smaller explosion.

The main reason to not change anything here is that grenadiers seem to be in a 'happy' place right now in terms of game balance. That said, they typically go unused outside of the early game. I don't know if changing explosions would encourage later use but that would probably be good for gameplay; I just don't see grens becoming overpowered if usable in the mid/late game.

The primary thing to look out for is the grenadier rush vs the pp/rax/ref/wf opener. It shouldn't be easy to hold off a  large rush with the above opener, but it shouldn't be impossible either. As long as changing the explosion size doesn't make grenadiers impossible to hold off I don't see a problem with it.

On a separate note, if grens end up with a smaller explosion I would like to see the explosion chance at 100% instead of the current 50%. The less RNG the better.

2017-04-02 13:53 UTC, pchote commented
> Seems like SoScared wants them to be more vulnerable after attacking and not so vulnerable before starting their attack. So then the yaml should be:
`Weapon: UnitExplodeSmall`
`EmptyWeapon: UnitExplode`
Exactly like it is today, just more clear that it is intentional and not a bug.

Can you please do this?  We can then merge this PR and hopefully put this discussion and confusion finally to rest.

2017-04-12 10:06 UTC, CH4Code requested changes

2017-04-12 10:06 UTC, CH4Code commented on mods/ra/rules/infantry.yaml
> +		EmptyWeapon: UnitExplodeSmall
Please change this in a new commit (or squash the commits if you can do it) to `EmptyWeapon: UnitExplode` as pchote requested.

2017-04-17 10:18 UTC, pchote commented
Progress here seems to have stalled, so considering that this a minor documentation issue I'm going to close it.

2017-04-17 10:18 UTC, closed without merging

2017-09-02 18:56 UTC, Smittytron commented
We tested grens with the small explosion on my playtest to see if they'd become too hard to stop early. Explosion on death chance was set to 100%. Even at 100% it is a noticeable buff, but nothing that a proper defense can't handle. I would give my thumbs up to reopening this with the 100% explosion chance.

2017-09-02 19:17 UTC, reaperrr commented
Note that we could easily introduce a dedicated `GrenadierExplode` weapon to fine-tune the damage without regressing anything else.