Overhaul launch-game.sh
OpenRA/OpenRA pull request #12992
Opened 2017-03-18 19:16 UTC by pchote

Another step towards being able to remove the mod launcher:

- Adds mod chooser popup if zenity available
- Adds at least OSX and hopefully general POSIX support
- Improved text-mode output when zenity not available.

I have used http://www.shellcheck.net/ to check for portability and confirmed that this works as expected under linux (with gnome 3) and macOS.

2017-03-18 19:46 UTC, ltem commented
It works also under linux with XFCE. 

However if I cancel the Zenity window it will still still start with the `ra`-mod. I would expect that it stops the start procedure or is this on purpose?

2017-03-18 20:10 UTC, pchote commented
Good catch!  Fixed.

2017-03-18 21:19 UTC, ltem commented
It works as expected but if I run it without a mod I get this message. 
```zsh
$ ./launch-game.sh
/usr/bin/zenity
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```
StackOverflow has a post about it [Link](http://stackoverflow.com/questions/29883211/gtkdialog-mapped-without-a-transient-parent#29883565), but no idea if this is wanted.

2017-04-01 16:47 UTC, obrakmann commented on launch-game.sh
> +MODLAUNCHER=$(python -c "import os; print(os.path.realpath('$0'))")
Not a fan of adding another dependency here for this rather mundane task.

2017-04-01 16:47 UTC, obrakmann commented on launch-game.sh
> +		elif [ "$TITLE" = "Tiberian Sun" ]; then MODARG='Game.Mod=ts'
Do we want to add that already?

2017-04-01 16:47 UTC, obrakmann commented on launch-game.sh
> +		TITLE=$(zenity --forms --add-combo="" --combo-values="Red Alert|Tiberian Dawn|Dune 2000|Tiberian Sun" --text "Select mod" --title="" || echo "cancel")
How would this handle custom mods?

2017-04-01 16:51 UTC, pchote commented on launch-game.sh
> +MODLAUNCHER=$(python -c "import os; print(os.path.realpath('$0'))")
gnu readlink is *already* an extra dependency, and doesn't work on OSX or other systems that use BSD readlink.

2017-04-01 16:52 UTC, pchote commented on launch-game.sh
> +		TITLE=$(zenity --forms --add-combo="" --combo-values="Red Alert|Tiberian Dawn|Dune 2000|Tiberian Sun" --text "Select mod" --title="" || echo "cancel")
It doesn't and isn't supposed to.  That is [launch-mod.sh](https://github.com/OpenRA/OpenRAModTemplate/blob/master/launch-mod.sh)'s job.

2017-04-01 16:53 UTC, pchote commented on launch-game.sh
> +		elif [ "$TITLE" = "Tiberian Sun" ]; then MODARG='Game.Mod=ts'
This script is for launching the game on a dev/self-compiled version of OpenRA.  That includes TS, so why wouldn't we want to add this?

2017-04-01 17:35 UTC, obrakmann approved these changes
👍 then

2017-04-01 17:35 UTC, obrakmann commented on launch-game.sh
> +		elif [ "$TITLE" = "Tiberian Sun" ]; then MODARG='Game.Mod=ts'
Oh, I thought we were using it for the xdg shortcuts, but it seems the Makefile writes its own copy.

2017-04-03 01:24 UTC, atlimit8 requested changes
Just a couple of nits.

2017-04-03 01:24 UTC, atlimit8 commented on launch-game.sh
> +	if which zenity
`if which zenity>/dev/null`
The output of `which` is just noise.

2017-04-03 01:24 UTC, atlimit8 commented on launch-game.sh
> +	if which zenity
`if which zenity>/dev/null` here as well.

2017-04-09 10:33 UTC, pchote commented
Fixed and rebased.

2017-04-09 12:09 UTC, atlimit8 approved these changes

2017-04-09 12:13 UTC, merged

2017-04-09 12:16 UTC, atlimit8 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/305ea7566986989b3242af00a7c8a3aeac4fba0d...702b2d087f6e4f43261fc5dbbe85a3e6d3e470d7)