Color picker update - built-in mod colors and a user palette
OpenRA/OpenRA pull request #13072
Opened 2017-04-07 03:05 UTC by drogoganor

Hi,

I had a go at updating the color picker. Now it has: 

- A set of preset color swatches for RA1 and TD, (defined in mod.yaml: TeamColorPresets: C4B060, 4494E4, ....)

- A user-defined palette defined in settings.yaml (Player: CustomColors: 3B99CA, A33BCA, ....)

![openra color picker](https://cloud.githubusercontent.com/assets/1639681/24783881/69daa73c-1b92-11e7-8972-703ef7709b2f.jpg)

This is my first time contributing to this project so hopefully I have done it correctly and haven't broken any rules.

I'd also like to know what preset colors were available in d2k, TS, and RA2 so I can add them into the mod.yaml for each of these mods. Does anyone happen to know?

Cheers

2017-04-07 04:53 UTC, atlimit8 requested changes
You should not have separate commits for fixing the commits you want merged. You can squash commits and amend (to amend to previous commits, use `git rebase -i`). Every commit is added when a PR is merged and the fix-ups would just be noise.

Aside from tabs/spaces, StyleCop actually complains about a number of things in the Travis continuous integration test.

Judging from all the StyleCop errors and the StyleCop fix-up commit, it appears that you may not have StyleCop/your code editor configured correctly.

You can run `make check` from the command line in the top directory of your OpenRA clone to find StyleCop format errors.

StyleCop errors from travis-ci log:
```
OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L27: [SA1512] A single-line comment must not be followed by a blank line. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L38: [SA1512] A single-line comment must not be followed by a blank line. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L80: [SA1515] A single-line comment must be preceded by a blank line or another single-line comment, or must be the first item in its scope. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L88: [SA1508] A closing curly bracket must not be preceded by a blank line.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L27: [SA1005] The comment must start with a single space. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L37: [SA1005] The comment must start with a single space. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L38: [SA1005] The comment must start with a single space. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L80: [SA1005] The comment must start with a single space. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L81: [SA1005] The comment must start with a single space. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L84: [SA1005] The comment must start with a single space. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L67: [SP2000] Invalid spacing at the end of the line.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L97: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L97: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L98: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L98: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L99: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L99: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L100: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L100: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L101: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L101: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L102: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L102: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L103: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L103: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L104: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L104: [SA1001] Invalid spacing around the comma.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L69: [SP2000] Invalid spacing at the end of the line.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L93: [SP2000] Invalid spacing at the end of the line.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L123: [SP2000] Invalid spacing at the end of the line.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L191: [SP2000] Invalid spacing at the end of the line.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L205: [SP2000] Invalid spacing at the end of the line.

OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs:L225: [SP2000] Invalid spacing at the end of the line.
```

Thanks for contributing.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +		    if (clearCustomPaletteButton != null)
Here is a reason to use tabs; the indentation for `if` here does not lined up with the rest.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs
> +        //protected bool CtrlPressed = false;
Why do you have commented-out code?
If you are unsure about adding code then ask.
If you want to include the commented-out stuff, you can put it in a separate commit here or in a separate branch.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +		        Color.FromArgb(112,44,36),      // 702C24
StyleCop complains about the commas on lines 97 through 104.

Should be:
```c#
		        Color.FromArgb(196, 176, 96),     // C4B060
		        Color.FromArgb(68, 148, 228),     // 4494E4
		        Color.FromArgb(236, 0, 0),        // EC0000
		        Color.FromArgb(0, 196, 0),        // 00C400
		        Color.FromArgb(252, 136, 0),      // FC8800
		        Color.FromArgb(112, 112, 112),    // 707070
		        Color.FromArgb(68, 144, 124),     // 44907C
		        Color.FromArgb(112, 44, 36),      // 702C24
```

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +
The spaces on empty line 69 should be removed.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +
The spaces on empty line 93 should be removed.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +
The spaces on empty line 123 should be removed.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +
The spaces on empty line 191 should be removed.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +
The spaces on empty line 205 should be removed.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
> +
The spaces on empty line 225 should be removed.

2017-04-07 04:53 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs
> +
The spaces on empty line 67 should be removed.

2017-04-07 05:05 UTC, drogoganor commented on OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs
> +
Thanks for the comprehensive comments. I'll sort these out and give it another go.

2017-04-07 05:23 UTC, atlimit8 commented on OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs
> +    }
I missed `OpenRA.Mods.Common/Widgets/ColorPaletteSwatchWidget.cs:L88: [SA1508] A closing curly bracket must not be preceded by a blank line.` Line 87 should be deleted.

2017-04-17 10:37 UTC, pchote commented
Any progress here @drogoganor?

It looks like you're having some issues with rebasing, feel free to drop in to the IRC channel if you need some help.

2017-04-17 22:57 UTC, drogoganor commented
Hi,

Yes I am actually struggling with rebasing, I am not skilled enough with 
git.

I wasn't sure if my current situation could be fixed? In any case I 
might drop into IRC and ask about it.

Cheers,

David

On 17/04/2017 8:37 PM, Paul Chote wrote:
>
> Any progress here @drogoganor <https://github.com/drogoganor>?
>
> It looks like you're having some issues with rebasing, feel free to 
> drop in to the IRC channel if you need some help.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/OpenRA/OpenRA/pull/13072#issuecomment-294447882>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABkFAfIC3hnwecFbQNtVvb5iR1mWAgMNks5rw0DmgaJpZM4M2Z8O>.
>

2017-04-26 18:01 UTC, pchote commented
Yeah, it's actually quite simple to fix if you know how.
Drop by IRC and someone should be able to help.  IRC is mainly active during european evenings, so if nobody is around just try again later.

2017-05-01 13:55 UTC, GraionDilach commented
This will fix #10591.

2017-05-13 12:59 UTC, pchote commented
@drogoganor are you still interested in working on this feature?
If not, we can move it to the future milestone for someone else to pick up when they have time and interest.

2017-05-15 22:52 UTC, drogoganor commented
Hi, I'm afraid I'll have to ask you to put it on the future milestone. 
I've been really busy lately and it seems it won't let up. Sorry.


On 13/05/2017 10:59 PM, Paul Chote wrote:
>
> @drogoganor <https://github.com/drogoganor> are you still interested 
> in working on this feature?
> If not, we can move it to the future milestone for someone else to 
> pick up when they have time and interest.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/OpenRA/OpenRA/pull/13072#issuecomment-301246693>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABkFAVIOz6MhYWtshcO2t7aaYnWN2MQNks5r5akbgaJpZM4M2Z8O>.
>

2017-05-15 23:52 UTC, abcdefg30 commented
No problem. Just let us know if you want to work on this again.

2017-05-15 23:52 UTC, closed without merging