Add a setting to disable DPI scaling on Windows systems
OpenRA/OpenRA pull request #13127
Opened 2017-04-14 14:48 UTC by obrakmann

Closes #13099.

2017-04-14 18:41 UTC, pchote requested changes
Should be good after this:

2017-04-14 18:41 UTC, pchote commented on OpenRA.Platforms.Default/Sdl2GraphicsDevice.cs
> +			else if (Platform.CurrentPlatform == PlatformType.Windows && !Game.Settings.Graphics.DisableWindowsDPIScaling)
You'll need to disable the `SetProcessDPIAware` above too.

2017-04-14 19:20 UTC, obrakmann commented
Updated.

2017-04-15 12:26 UTC, reaperrr approved these changes

2017-04-17 16:45 UTC, pchote approved these changes
:+1: does the job as advertised.

Two points worth noting:
* When this setting is enabled and Window's built in scaling is used cursors will not be scaled.  This is consistent with all our releases before HiDPI support was added.
* Windows's "Disable DPI scaling on high DPI displays" compatability option only acts on the system provided scaling.  The setting in this PR must be enabled for that checkbox to work as expected.

2017-04-17 16:46 UTC, merged

2017-04-17 16:50 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/bf00831cc347c6df09d521b4c884560edae069b7 and pushed to prep-1703.