Added ReloadSound and ReloadSoundDelay to weapon declarations.
OpenRA/OpenRA pull request #13204
Opened 2017-04-28 08:59 UTC by IceReaper

This allows a sound to be played when an actor reloads.

2017-04-28 15:53 UTC, chrisforbes commented on OpenRA.Mods.Common/Traits/Armament.cs
> +				if (Weapon.ReloadSound != null)
The report case above checks for both null and the list being nonempty. You should probably do the same here, or prove that the above code is being excessively paranoid.

2017-04-28 17:34 UTC, GraionDilach commented on OpenRA.Mods.Common/Traits/Armament.cs
> +					ScheduleDelayedAction(Weapon.ReloadSoundDelay, () =>
Shouldn't this be placed into Tick instead (like around line 160) with triggering when FireDelay reaches 0?

2017-04-30 11:18 UTC, reaperrr commented
> OpenRA.Mods.Common/Traits/Armament.cs:L254: [SA1111] The closing parenthesis or bracket must be placed on the same line as the last parameter in the parameter list.
OpenRA.Mods.Common/Traits/Armament.cs:L254: [SA1009] Invalid spacing around the closing parenthesis.

You can catch these style errors locally by running make.cmd -> check (or the Linux equivalent).

2017-04-30 11:25 UTC, GraionDilach commented
My previous note also got no 4response - GH marked it outdated because of reorganization.

2017-04-30 12:45 UTC, GraionDilach approved these changes
:+1:

2017-04-30 20:32 UTC, pchote requested changes

2017-04-30 20:32 UTC, pchote commented on OpenRA.Game/GameRules/WeaponInfo.cs
> +		public readonly string[] ReloadSound = null;
Please rename these to something like `AfterFireSound` and `AfterFireSoundDelay`.  These are separate to the reloading logic in the `AmmoPool`s, so the current names are misleading.

2017-04-30 20:32 UTC, pchote commented on OpenRA.Mods.Common/Traits/Armament.cs
> +				if (Weapon.ReloadSound != null && Weapon.ReloadSound.Any())
Use `ScheduleDelayedAction` here to avoid duplicating the boilerplate for ticking down and checking instant vs delayed playback.

2017-04-30 21:08 UTC, GraionDilach commented on OpenRA.Mods.Common/Traits/Armament.cs
> +				if (Weapon.ReloadSound != null && Weapon.ReloadSound.Any())
ScheduleDelayedAction here is wrong, because it will ignore if the actual armement trait ends up disabled between firing and the sound being played.

2017-04-30 21:09 UTC, pchote commented on OpenRA.Mods.Common/Traits/Armament.cs
> +				if (Weapon.ReloadSound != null && Weapon.ReloadSound.Any())
ScheduleDelayedAction only ticks down if the trait is enabled.  See the Tick method.

2017-04-30 21:14 UTC, GraionDilach commented on OpenRA.Mods.Common/Traits/Armament.cs
> +				if (Weapon.ReloadSound != null && Weapon.ReloadSound.Any())
Damn, I still keep mixing it with that other DelayedAction function.

Carry on then.

2017-04-30 21:21 UTC, pchote approved these changes

2017-04-30 21:22 UTC, pchote commented
@GraionDilach: Can you confirm that your :+1: still holds after the changes?

2017-04-30 23:03 UTC, GraionDilach approved these changes
Yes now. :+1:

2017-04-30 23:05 UTC, merged

2017-04-30 23:06 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/87bf984915ab01b9469985198ec1090713b052fb