TD Supply Truck
OpenRA/OpenRA pull request #13231
Opened 2017-05-03 11:14 UTC by anjew175

Adds supply truck to TD
closes #12849

2017-05-03 16:23 UTC, GraionDilach commented on mods/cnc/rules/campaign-maprules.yaml
> +
Revert this line.

2017-05-03 16:24 UTC, GraionDilach commented on mods/cnc/rules/structures.yaml
> +
Empty spaces in line.

2017-05-03 16:24 UTC, GraionDilach commented on mods/cnc/rules/structures.yaml
> +
Same here.

2017-05-03 16:24 UTC, GraionDilach commented on mods/cnc/rules/structures.yaml
> +
And here.

2017-05-03 16:25 UTC, GraionDilach commented on mods/cnc/rules/campaign-maprules.yaml
> +
IOW there's a tab here.

2017-05-04 03:33 UTC, MustaphaTR requested changes

2017-05-04 03:33 UTC, MustaphaTR commented on mods/cnc/rules/structures.yaml
> +	AcceptsDeliveredCash:
This and one on FACT.NOD is not required. They already Inherit that from FACT.

Actually you can just put it on ^Building under defaults.yaml and remove it on ^Defence and others that don't need it as done in RA mod. No need to specify it on each building.

2017-05-06 09:15 UTC, pchote submitted a review, later dismissed
Adding the supply truck fills a known gameplay hole, so the premise of this PR is fine with me.

However, in addition to the issues raised by @GraionDilach and @MustaphaTR I have two more:

* This is a low tech unit, so the build icon should be in the top row of the palette (low BuildPaletteOrder).
* The palette didn't convert very well, the artwork looks glitchy ingame:
![screen shot 2017-05-06 at 10 10 10](https://cloud.githubusercontent.com/assets/167819/25771270/facefa86-3244-11e7-83cd-4863ca101331.png) ![screen shot 2017-05-06 at 10 09 59](https://cloud.githubusercontent.com/assets/167819/25771269/f07adc30-3244-11e7-9698-d09ffa96ca26.png)

2017-05-06 09:22 UTC, GraionDilach commented
Is this the RA1 Truck? If yes, maybe it would make more sense using the original artwork with the RA pal instead of converting the artwork to TD.

2017-05-06 09:32 UTC, pchote commented
I don't want to have to pull in the RA palette (yet another non-free binary file in our repo) and bloat the palette definitions just for one unit.

2017-05-06 23:34 UTC, GraionDilach commented
Converting palette between TD and RA requires 2-pass methods (!) which I presume is above @anjew175 's level (yes, that's required simply because of the different position of the remap gradient). And I have noidea how the result will look like.

2017-05-22 21:00 UTC, anjew175 commented
Has been updated to adhere to requested changes

2017-07-12 12:21 UTC, ltem commented
The code looks fine (Note: it won't spawn a moneycrate on death) but the artwork looks still glitchy on the desert terrain.

![screens](https://user-images.githubusercontent.com/20945684/28117300-2541e07e-670d-11e7-9165-6bf5c4c57b03.png)

2017-07-15 23:47 UTC, reaperrr commented
Rebased and updated the sprite to work on all terrain:
![truk-tem](https://user-images.githubusercontent.com/2857877/28243411-9dda4126-69c8-11e7-9f30-9a606e16784e.png)
![truk-des](https://user-images.githubusercontent.com/2857877/28243412-9fdbaadc-69c8-11e7-9595-f9e6b8ee5242.png)

2017-07-16 00:03 UTC, GraionDilach approved these changes
:+1: then.

2017-07-16 09:14 UTC, ltem approved these changes
Looks good.

2017-07-16 10:07 UTC, pchote approved these changes

2017-07-16 10:07 UTC, merged

2017-07-16 10:09 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/49a06a019743b9d9ed11625fac07a5e15950592a

2017-07-16 11:59 UTC, anjew175 commented
Thank you for doing up the sprites @reaperrr 
Look great.

I had no idea sprites could look good on one terrain and shit on another

2017-07-16 12:37 UTC, reaperrr commented
> I had no idea sprites could look good on one terrain and shit on another

Unlike RA, TD currently uses the terrain-specific palettes for units and buildings, too. That's fine for TD sprites because Westwood designed the sprites to not use tileset-specific colors, but when converting unit shps from RA to TD or vice-versa using the normal palettes, XCC Mixer simply uses the closest match it can find, or first perfect match, and quite often that's a terrain color index. I have some custom modified palettes here where these tileset colors are replaced with pink, so XCC Mixer won't use those indexes when converting to shp.