Add Starting Building support
OpenRA/OpenRA pull request #13265
Opened 2017-05-09 14:02 UTC by MustaphaTR

Fixes #13264.

I'm not sure if a seperate SupportBuildings: tag is required or i could add support to have buildings in to `SupportActors:`, i couldn't manage to do the latter so gone with first.

I added some MPStartUnits with buildings to `ra` mod as testcase.

2017-05-09 14:22 UTC, CH4Code commented
very nice, thank you! - I have allready use scenarios for this function :)

2017-05-09 17:08 UTC, pchote commented
Like I mentioned in IRC, I feel that this is a not a good approach, and will only cause us problems.

Randomly placing buildings works *just* well enough for people to want to use it, but not well enough for those people not to then open bug reports about the cases where it fails (e.g. placing defenses in the wrong place, blocking off other units, failure modes on maps where there isn't enough space to place structures).

If we're going to implement this feature then I would very strongly prefer that we do it in a way where we have options for fixing problems like these - e.g. having predefined base templates, or hints defined in the map file.

2017-05-09 18:11 UTC, MustaphaTR commented
I, unfortuanately, have no interest in coding a proper Starting Building support, mostly because this is sufficent for me. And i don't think anyone else has either.

> placing defenses in the wrong place

If you mean small structures going unavailable places, well that is a case with units too, and is mapmaker's problem for now. We already have an issue for that: #12057

If you mean some people may want defences to go to side where enemies are rather than backlines, i may code that, i think.

> failure modes on maps where there isn't enough space to place structures

Well, this currently doesn't spawn them and add a message to Debug.log, as we already do for Starting Units.

Also another thing i can do for this PR to add seperate `*SupportRadius:` and a `SupportBuildingsFacing:` tags. As one may want spawn defence Turrets not randomly faced, but units are or make units spawn further so they'll be out of the base for example.

2017-05-09 21:13 UTC, GraionDilach commented
This definitely needs atleast a domaincheck. Working against the closed tiles on a map-by-map basis is what major polished RA2 mods are doing through BRIDGE_OVERLAY btw.

2017-05-11 17:48 UTC, Iamgoofball commented
if this shit's just thrown onto the map randomly you can bet at some point in the future there'll be a bug report about someone having to sell their buildings and move them because they got placed inside a cliff or water or blocking a path

2017-05-11 18:47 UTC, MustaphaTR commented
No, this has a check for if the place is buildable. So starting buildings are only placed to where they can be normally placed and not placed (with an error logged into debug.log, but no crash) if no space for it available in desired range defined by *SupportRange tags.

2017-05-13 18:01 UTC, chrisforbes requested changes
Consensus seems to be that this needs more work. @GraionDilach can you pick this up if the original author has run out of steam?

2017-05-13 18:20 UTC, GraionDilach commented
I'm not that interested in this, sorry.

2017-06-23 10:20 UTC, reaperrr commented
Closing but moving to Future milestone due to lack of progress.

2017-06-23 10:20 UTC, closed without merging