Fix GetSupportDir not returning an absolute path
OpenRA/OpenRA pull request #13525
Opened 2017-06-17 16:44 UTC by obrakmann

Current bleed crashes with a misleading exception when using a Support dir. This fixes it.

```
Exception of type `System.ArgumentException`: Second path fragment must not be a drive or UNC name.
Parameter name: path2
  at System.IO.Path.InternalCombine (System.String path1, System.String path2) [0x00058] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () [0x00000] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00009] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00000] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.IO.Directory.InternalGetFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in <a07d6bf484a54da2861691df910339b1>:0 
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x0001c] in <a07d6bf484a54da2861691df910339b1>:0 
  at OpenRA.ExternalMods..ctor (System.String launchPath) [0x00099] in /home/oliver/devel/openra/git/OpenRA.Game/ExternalMods.cs:58 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x003e6] in /home/oliver/devel/openra/git/OpenRA.Game/Game.cs:342 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in /home/oliver/devel/openra/git/OpenRA.Game/Support/Program.cs:134 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /home/oliver/devel/openra/git/OpenRA.Game/Support/Program.cs:40 
```

2017-06-17 19:33 UTC, rob-v approved these changes
👍 
btw at least on Windows there is small issue, not causing an error though, as e.g. File.Exists(Open) works also with such path with double \\ e.g.:
C:\Users\rob\Documents\OpenRA\\\\settings.yaml

ResolvePath is called with Path.Combine("^", "settings.yaml") or "^testpath". ResolvePath removes only ^: SupportDir + path.Substring(1) and SupportDir contains \ at the end. 
IMO Path.Combine shouldn't be used with ^, simply "^settings.yaml", "^ModMetadata" or \ should be removed in ResolvePath.

2017-06-18 07:52 UTC, rob-v reviewed
small issue/suggestion

2017-06-18 07:52 UTC, rob-v commented on OpenRA.Game/Platform.cs
> +				return Directory.GetCurrentDirectory() + Path.DirectorySeparatorChar + "Support" + Path.DirectorySeparatorChar;
Better to use: 
return Path.Combine(GameDir, "Support") + Path.DirectorySeparatorChar;

2017-06-18 07:58 UTC, rob-v requested changes
(I didn't know how to remove Approve other way than by 'Request changes')

2017-06-18 10:33 UTC, obrakmann commented on OpenRA.Game/Platform.cs
> +				return Directory.GetCurrentDirectory() + Path.DirectorySeparatorChar + "Support" + Path.DirectorySeparatorChar;
Good call. Changed.

2017-06-18 11:19 UTC, rob-v approved these changes
👍

2017-06-18 18:46 UTC, reaperrr approved these changes

2017-06-18 18:46 UTC, merged

2017-06-18 18:48 UTC, reaperrr commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a66d5e4578552498262a15a512dde322cf3ad85e...ff35e07d63e3b3bdab63db644e1b83079432791e