Upgraded PixelDouble to selectable PixelScale
OpenRA/OpenRA pull request #13532
Opened 2017-06-21 10:47 UTC by IceReaper

This replaces the pixel doubling with a selectable scale. I also added x4 as an option, to make the game look good on 4K screens, or for mods which have tiles in <= 16 pixel size, or a combination of both.

2017-06-22 03:00 UTC, ROCKNROLLKID commented
Me and my 4K screen love you for this <3.

2017-06-29 17:40 UTC, reaperrr commented on OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs
> +using OpenRA.Mods.Common.Traits;
This isn't used, probably a left-over from earlier revisions, so it should be removed.

2017-06-29 17:41 UTC, reaperrr approved these changes
👍

2017-06-29 17:55 UTC, pchote commented
Sorry, but I'm going to have to :-1: this at a conceptual level:
* The fractional pixel scales are very buggy on certain common hardware configurations and are only exposed for use in the map editor and (begrudgingly) spectators where their usefulness arguably outweigh the issues.  They absolutely should not be enabled for regular gameplay.
* The hotkey is very useful to zoom in for fine targeting, then again to go back to normal.  Players now have to press the key 4 times to zoom in!

This also breaks the display mode dropdown in the settings menu, and has the wrong button size there.

2017-07-02 21:21 UTC, atlimit8 requested changes
Maybe a set max zoom (2x or 4x) option and/or min zoom (1x or 2x) option and keep the hotkey for toggling between two zoom levels (min & max). Only integral (whole number) zoom levels should be allowed; 3x would be acceptable since the hotkey would be limited to two zoom levels.

I agree with @pchote. Unless this becomes like my aforementioned proposal, handling the issues mentioned by @pchote, I oppose merging this.

2017-09-14 22:16 UTC, reaperrr commented
There hasn't been any activity in over 2 months, so I'm closing this as part of a PR queue clean-up.

2017-09-14 22:16 UTC, closed without merging