Add GrantConditionOnAmmo
OpenRA/OpenRA pull request #13869
Opened 2017-08-20 11:13 UTC by jrb0001

2017-08-20 12:30 UTC, Mailaender requested changes

2017-08-20 12:30 UTC, Mailaender commented on OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnAmmo.cs
> +	[Desc("Applies a condition to the actor at specified damage states.")]
This is probably copy pasta from `GrantConditionOnDamageState.cs` and not what this actually does.

2017-08-20 13:35 UTC, jrb0001 commented on OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnAmmo.cs
> +	[Desc("Applies a condition to the actor at specified damage states.")]
fixed.

2017-08-20 13:36 UTC, Mailaender submitted a review, later dismissed

2017-08-20 13:53 UTC, pchote commented on OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnAmmo.cs
> +			var variables = ReadOnlyDictionary.AsReadOnly(new Dictionary<string, int>()
Creating these objects every tick isn't great for memory churn.  Please create these once in the ctor, and then update the values each tick.

2017-08-20 13:57 UTC, pchote commented on OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnAmmo.cs
> +					{ "amount", ammoPools.Sum(x => x.GetAmmoCount()) },
Can you please also add a comment `// TODO: Update these to account for disabled traits once AmmoPool is made conditional`

2017-08-22 17:34 UTC, jrb0001 commented on OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnAmmo.cs
> +			var variables = ReadOnlyDictionary.AsReadOnly(new Dictionary<string, int>()
done.

2017-08-22 17:34 UTC, jrb0001 commented on OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnAmmo.cs
> +					{ "amount", ammoPools.Sum(x => x.GetAmmoCount()) },
done.

2017-08-25 22:43 UTC, pchote commented
Could you outline some of the ways that you plan to use the `Expression`?

2017-08-25 22:57 UTC, pchote commented
The discussion in #13057 is particularly relevant here: under the proposed system `AmmoPool` would directly expose `Count` and `Capacity` variables that could be used directly in other conditions, instead of requiring a mediating trait.

2017-08-26 10:55 UTC, jrb0001 commented
The problem with integer conditions is that they rely on granting a condition multiple times iirc. This is a huge performance hit if ammopools have thousands of ammo.

I use the expression to grant a condition if the ammo pool is empty although I might also need it for other values.

2017-08-26 10:58 UTC, jrb0001 commented
rebased.

@Mailaender It looks like GitHub decided to dismiss your review automatically.

2017-08-26 11:00 UTC, Mailaender commented
I haven't really tested it to be honest. It was just a quick skim.

2017-08-26 11:02 UTC, pchote commented
> The problem with integer conditions is that they rely on granting a condition multiple times iirc. This is a huge performance hit if ammopools have thousands of ammo.

No, they expose their values directly.

2017-08-26 11:06 UTC, jrb0001 commented
hmm, then how do I grant such a condition? `ConditionManager.GrantCondition(Actor self, string condition, int duration = 0)` doesn't allow it.

2017-08-26 11:08 UTC, pchote commented
The plumbing doesn't exist yet.  That is what #13057 is for.

2017-08-26 11:11 UTC, jrb0001 commented
Then it should be obvious that there is no other way to solve it at the moment. And the history of that PR tells me that it won't be merged in the near future. Do you want me to close my PR?

2017-08-26 13:23 UTC, pchote commented
Like with #13847, I think it would be unwise to merge a temporary workaround when we have a general solution that would supersede it if not for lack of manpower.  It would be much better if you could help towards getting that implemented.

2017-08-26 17:50 UTC, jrb0001 commented
Ok, I will keep it downstream until the integer conditions are completely done and there is an official solution. I can implement it properly but there is no point in working on it until the plumbing PR is merged.

2017-08-26 17:50 UTC, closed without merging

2017-11-22 22:02 UTC, reaperrr commented
@jrb0001 We decided to add a local stacked conditions implementation to `AmmoPool` as temporary solution in #13538, I guess that might already be enough for some of the use-cases this PR wanted to adress.

2017-11-23 17:17 UTC, jrb0001 commented
The use-case was to grant conditions based on the ammo level. Even though only full and empty were needed, I attempted to implement a generic solution. #13538 should contain the required changes but it doesn't expose the ammo limit afaik.

2017-11-23 17:32 UTC, GraionDilach commented
You're wrong - gladly, my request about exactly that was encouraged, see https://github.com/OpenRA/OpenRA/pull/13538#pullrequestreview-69615367.