Fix the map editor crashing on invisible actors
OpenRA/OpenRA pull request #14122
Opened 2017-10-06 10:13 UTC by abcdefg30

Testcase: Open `allies03b` in the map editor or place a powerproxy in any map before opening the map editor.

We also don't use the returned value of `Add`, so I removed that.

2017-10-06 17:09 UTC, reaperrr submitted a review, later dismissed

2017-10-08 12:30 UTC, pchote requested changes

2017-10-08 12:30 UTC, pchote commented on OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
> +		void Add(string id, ActorReference reference, bool initialSetup = false)
Making this `void` breaks the symmetry with `Remove`, and means you need to do gymnastics if you want to add an actor and then immediately do something with the `EditorActorPreview`.

Can you instead just skip the screenMap addition on empty bounds?

2017-10-08 17:37 UTC, abcdefg30 commented
Updated.

2017-10-14 09:07 UTC, pchote approved these changes

2017-10-14 11:35 UTC, reaperrr approved these changes

2017-10-14 11:35 UTC, merged

2017-10-14 11:41 UTC, reaperrr commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6bcd9e7e19e1b863b59bc9edd21d0de8c98e9e8b...f7e813b3422a2360e65d50b83aeb35fdc0b44c98