Add Github issue template
OpenRA/OpenRA pull request #14811
Opened 2018-02-11 14:26 UTC by ltem

Closes #13774.

This PR adds an issue template to the repo and should be used as a guideline for bug reports and enhancement requests.

If somebody is interested to see the template in action, I created a test-repo [Link](https://github.com/ltem/template_test/issues/new).

2018-02-18 20:01 UTC, Unit158 requested changes
Looks good, just the way comments are used is not consistent, so that should probably be fixed

2018-02-18 20:01 UTC, Unit158 commented on .github/ISSUE_TEMPLATE.md
> +When submitting a feature or enhancement request:
This should probably be in a comment. (Down to the Issue Summary)

2018-02-18 20:01 UTC, Unit158 commented on .github/ISSUE_TEMPLATE.md
> +2. Step
I'd say these should be outside of a comment (remove the comment tags?)

2018-02-24 19:16 UTC, ltem commented
Updated

2018-02-24 23:08 UTC, Unit158 commented
:+1:

2018-02-24 23:08 UTC, Unit158 approved these changes

2018-02-25 14:16 UTC, reaperrr approved these changes

2018-02-25 14:16 UTC, merged