Change menu cancel buttons to back
OpenRA/OpenRA pull request #15410
Opened 2018-07-29 01:20 UTC by Smittytron

Closes #15398 

The only change I'm unsure of is the save map button. It can be argued that save map is a prompt instead of part of the menu navigation, and thus makes more sense as 'cancel'. We're splitting hairs either way so I went ahead and pushed it as requested by @FrameLimiter 

If anyone has the same hang-up I can take the save map change out.

2018-07-29 05:14 UTC, chrisforbes commented on mods/cnc/chrome/editor.yaml
> -			Text: Cancel
Nak to this one.

2018-07-29 05:15 UTC, chrisforbes submitted a review, later dismissed
Actually, no, nak to this whole thing.

2018-07-29 16:59 UTC, chrisforbes requested changes
If you change the save map panel button back, 👍

2018-07-30 00:38 UTC, Smittytron commented
Updated

2018-08-05 03:11 UTC, chrisforbes submitted a review, later dismissed

2018-09-28 22:33 UTC, pchote approved these changes

2018-09-28 22:33 UTC, merged

2018-09-28 22:34 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/06460dbf2f8f1fd766554c600088da140c99d0c7