Some CrateSpawner related changes
OpenRA/OpenRA pull request #15589
Opened 2018-09-05 15:58 UTC by MustaphaTR

First commit fixes the small issue with owners i noted at #15586.

Second commit adds an actor init to pass which CrateSpawner trait spawned the crate, so multipile CrateSpawner traits can have their max-min values separetly calculated.

Third commit makes the trait conditional. While not much useful under World actor. I use CrateSpawner under Player actor and i used conditions so i can add additional crates per player in No Bases mode i added to my mod. GrantConditionOnPrerequisite unfortunately doesn't work on World actor. If it did, we could remove the dedicated lobby option logic under CrateSpawner and use LobbyPrerequisiteCheckbox instead. On my engine i moved the crate lobby option stuff to MapOptions: trait but i still think best way of doing it is LobbyPrerequisiteCheckbox, so haven't touched it here. I can update this PR if someone can help me with that.

2018-09-29 09:41 UTC, MustaphaTR commented
Rebased.

2018-09-30 13:50 UTC, abcdefg30 requested changes
From IRC: Using crate types would be better than using an init.

2018-09-30 13:52 UTC, pchote commented
The reason I suggested crate types is that it can then take into account manually placed crates on the map / from lua / etc.

2018-10-04 12:13 UTC, MustaphaTR commented
As i said on IRC: 

> pchote, abcdefg30 : about that CrateSpawner PR, while it would be good to somehow allow preplaced crates to count towards the trait. I don't think checking the types is a good idea. If i define CrateSpawner on an normal/Player actor, i would expect it to apply Min/Max per player/actor/trait which wouldn't be the case if it was done with types.

2018-10-04 13:43 UTC, MustaphaTR commented
If we are gonna multipile with player count, i don't think we need to move the trait to player actor. 

Another idea i have is to have a seperate manager trait to check the amount of crates on the map and CreateSpawner trait spawns them accordingly.

As i said in the main comment, getting GrantConditionOnPrerequisite on world actor could really help here by getting rid of Specific Lobby options and use LobbyPrerequisiteCheckbox instead.

2019-03-09 12:37 UTC, pchote commented
@MustaphaTR are you planning to continue with this? If not, can you please close it?

2019-04-21 12:00 UTC, pchote commented
Closing as stale.

2019-04-21 12:00 UTC, closed without merging