Resizable game window support.
OpenRA/OpenRA pull request #15719
Opened 2018-10-20 09:26 UTC by IceReaper

### WIP!

This PR implements resizable window support. The basic functionality is tested on windows and linux (someone with a mac might verify if this works there too!).

It currently lacks the default widgets to adopt the resize method and reposition its children if necessary, so some widgets might break their bounds while resizing.
Fell free to contribute with widget implementations!

2018-10-25 21:58 UTC, pchote commented
It would be good if we could get some people to test this and note all the places that break in the default mods.  This doesn't require coding knowledge, just the ability to compile and run this PR.

2018-10-25 22:03 UTC, pchote requested changes
A couple of specific comments, and one general one: i'm pretty sure that `ChromeLogic` objects will need to know when the window changes to be able to adjust bounds that it managed directly.  Can you please add plumbing for a `WindowSizeChanged` notification (there are already calls for `BecameHidden` / `BecameVisible`).

2018-10-25 22:03 UTC, pchote commented on OpenRA.Game/Widgets/Widget.cs
>  			substitutions.Add("PARENT_LEFT", parentBounds.Left);
The parent position and bounds may be defined in terms of the window size, so aren't these also going to change?

2018-12-06 16:21 UTC, SoScared commented
This is great. How about support for adjustable widgets too? 😃

2019-03-09 12:53 UTC, pchote commented
This was found to break rendering on HiDPI displays and had to be reverted from the KKnD mod.

Theres not much more we can do here until the logic is rewritten, so closing.

2019-03-09 12:53 UTC, closed without merging