Allow VoiceAnnouncement to not trigger on game start.
OpenRA/OpenRA pull request #15797
Opened 2018-11-06 19:45 UTC by IceReaper

The removal of INotifyBuildComplete made units announce always, even on map start. Mods having announce voices for all units upon production will cause a lot of announcements on game start, which was captured before by above interface, which did not trigger on those. This PR adds a property to toggle whether an unit announces upon map start or not.

2018-11-07 09:47 UTC, pchote commented on OpenRA.Mods.Common/Traits/Sound/VoiceAnnouncement.cs
> +			if (skipNext)
Can you check against something that is actually related to MapInit instead? `self.World.WorldTick == 0` should work.

2018-11-14 06:47 UTC, reaperrr submitted a review, later dismissed

2018-11-17 09:49 UTC, pchote commented
```
[09:55:00] | <IceReaper> Regarding #15797 Any idea how to implement the same with FreeActor ?
```

IMO the best approach for both this and map spawning would be to implement a `GrantConditionWhenProduced` trait that grants a condition on an actor when it is produced through a specific production type (using a `ProductionTypeInit` that is added to the actor via the `DoProduction` init dict).

2018-11-17 09:57 UTC, pchote requested changes

2018-11-17 09:57 UTC, pchote commented on OpenRA.Mods.Common/Traits/Sound/VoiceAnnouncement.cs
> +			if (!Info.AnnounceWhenSpawnedByMap && self.World.WorldTick == 0)
Checking against WorldTick is likely to cause issues in the future, so I would prefer we did this using conditions instead.

2018-12-05 01:32 UTC, pchote commented
I filed #15797 implementing my request above, so closing as superseded.

2018-12-05 01:32 UTC, closed without merging