Added Standard Resolution Dropdown List in Settings
OpenRA/OpenRA pull request #16151
Opened 2019-02-01 23:56 UTC by newyork167

Adds a dropdown to the settings screen with a list of common/standard resolutions in differing aspect ratios.

2019-02-03 12:52 UTC, matjaeck commented
I'm wondering if we want a general setting for resolution and then just say open it in full screen or windowed.

2019-02-03 13:08 UTC, pchote commented
Full-screen resolution controls depend on #10382, which still needs some serious work to complete.

2019-02-04 20:36 UTC, newyork167 commented
For the logicArgs in the settings yaml, how do you guys feel about this kind of setup?
![image](https://user-images.githubusercontent.com/1368137/52235610-9d3f0500-2892-11e9-911f-fe2cf1b174dc.png)

2019-02-04 20:48 UTC, matjaeck commented
Please paste code snippets by using the formatting explained at https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code.

2019-02-04 20:53 UTC, pchote commented
If you go with a simpler yaml syntax:
```yaml
SupportedResolutions:
    1024, 768: 1024x768 - 4:3
    1920, 1080: 1920x1080 - 16:9
    ...
```

then you can use the following snippet to automatically parse it into a dictionary:
```csharp
MiniYaml yaml;
if (logicArgs.TryGetValue("SupportedResolutions", out yaml))
{
	var resolutions = (Dictionary<int2, string>)FieldLoader.GetValue("SupportedResolutions", typeof(Dictionary<int2, string>), yaml, null);
	// Do things with resolutions
}
```
You can invert the `int2` and `string` if you want to keep the same ordering as in the current code, but IMO having the int2 on the key makes more sense.

Note that our minimum supported resolution is 1024x720, so you should remove all the options smaller than this.

2019-03-09 22:30 UTC, pchote commented
Any progress here @newyork167?

2019-03-19 18:33 UTC, newyork167 commented
> Any progress here @newyork167?

Sorry @pchote work has kept me busy the last few weeks. I've pushed some changes reflecting your new settings format, let me know what you think.

2019-03-24 16:30 UTC, Mailaender commented
You could also use call `SDL_GetDisplayMode()` in a loop, `SDL_GetNumDisplayModes()` times according to https://wiki.libsdl.org/MigrationGuide

2019-04-27 23:27 UTC, abcdefg30 commented on OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
> +				useCustomResolutionOnClick();
I don't think this is needed when you don't perform any extra options. (I.e. It should be save to remove line 177, and lines 179-182.)

2019-04-27 23:27 UTC, abcdefg30 commented on OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
> +				{
Please drop the braces around this single-line statement.

2019-04-28 06:44 UTC, abcdefg30 requested changes
Sorry for the delayed review. A few things:
- You will also need to adjust `cnc`'s `settings.yaml` chrome file.
- Is it intentional, that the dropdown shows the current custom resolution when you uncheck the checkbox? (That way you can get entries that are not in the list.)
- Have you looked at Mailaender's suggestion on how to generate the list? Is that something we want to do? (I think it might be worth a shot.)

Looks good to me otherwise.

2019-12-05 00:54 UTC, reaperrr commented
There hasn't been any progress in quite a while, so I'll close this to clean up the PR queue and move it to Future milestone. Hopefully someone will pick this up.

2019-12-05 00:54 UTC, closed without merging