Implement Harvester>BaleUnloadAmount
OpenRA/OpenRA pull request #16226
Opened 2019-02-21 12:33 UTC by MustaphaTR

Altho it is no longer using the Harvester/Refinery/Resource logic, i added this to Generals Alpha at the point it did. So everything was dropped off the collectors at once.

Testcase makes RA Harvester drop all 20 bales it has at once.

2019-02-22 15:37 UTC, reaperrr commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +		[Desc("How much bales can i dump at once.")]
typo: should be 'it' instead of 'i'.

2019-02-22 15:41 UTC, reaperrr submitted a review, later dismissed
Looks good to me

2019-02-22 21:10 UTC, pchote requested changes

2019-02-22 21:10 UTC, pchote commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +				var count = contents[type] - Info.BaleUnloadAmount < 0 ? contents[type] : Info.BaleUnloadAmount;
This can simplify to `var count = Math.Min(contents[type], Info.BaleUnloadAmount);`

2019-02-22 21:10 UTC, pchote commented on OpenRA.Mods.Common/Traits/Harvester.cs
> +				contents[type] = contents[type] - count;
`contents[type] -= count`?

2019-03-03 12:25 UTC, ZxGanon commented
I tested it ingame and it works fine. 

Only problem would be that Ore Trucks in RA1 dont play their complete animation when dumping.

2019-03-03 12:26 UTC, ZxGanon submitted a review, later dismissed

2019-03-04 22:41 UTC, reaperrr commented
> Only problem would be that Ore Trucks in RA1 dont play their complete animation when dumping.

That's just the test-case, or rather how our docking animation is set up.
Not this PR's fault.

👍 after test case is removed.

2019-03-08 20:52 UTC, MustaphaTR commented
Removed the testcase.

2019-03-09 12:18 UTC, pchote approved these changes

2019-03-09 12:19 UTC, merged

2019-03-09 12:20 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/df42a4b088162e205666add7c8318d0e768df8c2