Work around C17s not being able to deliver units
OpenRA/OpenRA pull request #16574
Opened 2019-05-21 13:57 UTC by abcdefg30

Currently no units are delivered since the plane never lands. Might close #16239.

2019-05-21 14:36 UTC, GraionDilach commented
You can test the ticket with selling the airstrip after the production finished but before the plane landing.

2019-05-21 14:42 UTC, abcdefg30 commented
Then it appears to be already fixed on bleed.

2019-05-22 21:52 UTC, pchote requested changes
The D2k starport suffers from the same bug. Can you please fix that here too?

2019-05-22 21:52 UTC, pchote commented on mods/cnc/rules/aircraft.yaml
> +		LandableTerrainTypes: Clear,Rough,Road,Beach,Tiberium,BlueTiberium
Can you please add spaces after the commas while you're here?

2019-05-22 21:52 UTC, pchote commented on mods/cnc/rules/aircraft.yaml
> +		LandableTerrainTypes: Clear,Rough,Road,Beach
And here.

2019-05-23 12:27 UTC, abcdefg30 commented
Updated.

2019-05-23 17:44 UTC, pchote commented
#16239 was filed based on playtest-20190209, well before the landing changes. Removed the reference from the PR description that would have automatically closed the issue.

2019-05-23 17:53 UTC, pchote commented
This fix reveals a second regression: If a second plane arrives while the first is landing it will be blocked, and do a loop before landing. We can introduce an `OccupiesSpace` flag on `AircraftInfo` that disables the `ActorMap` influence adding/removing.

2019-05-23 19:28 UTC, pchote commented
A third landing terrain type regression was noted in #16481.

> > idle yaks will not respond to queued orders (we had this issue before)
> 
> This issue is present in bleed as well and was regressed by #16365. the problem is that `LandWhenIdle` defaults to true even for aircraft that have no valid terrain for landing, so the aircraft gets stuck in a holding pattern until canceled. This should be handled in a separate fixup PR.

2019-05-23 19:33 UTC, tovl commented
The last issue was already fixed in #16509 . Also, the work-arounds proposed here would heavily conflict with that PR. Expect a proper fix to be added soon to that PR or a follow up.

2019-05-24 16:55 UTC, abcdefg30 commented
> This fix reveals a second regression: [...]

This was not unexpected, as I said on IRC yesterday.

2019-06-04 18:26 UTC, pchote approved these changes
This bug is blocking meaningful testing of the AI, so we need a fix ASAP.
We can revert parts of this again in #16509 once that is ready.

2019-06-04 20:24 UTC, ghost approved these changes
Fixes the bug.

2019-06-04 22:54 UTC, merged

2019-06-04 22:58 UTC, reaperrr commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/22a1dc65c33c8b716c4a0d07e9b038e580914ca7...1c02a9a5777f5cd190aaf8adb68d96c196f6f124