Add support power palette order
OpenRA/OpenRA pull request #16645
Opened 2019-06-06 23:05 UTC by dragunoff

As suggested in #16383 and discussed on discord around the same time. This is very similar to `BuildPaletteOrder`. The order is as follows:

Index | RA | TD | d2k
---: | :--- | :--- | :---
10 | Spy Plane | Airstrike | Airstrike
20 | Paradrop | Ion Canon | Fremen
30 | Parabombs | Nuke | Saboteur
40 | Iron Curtain | | Nuke
50 | Chronoshift | | 
60 | Adv. Chronoshift | | 
70 | Nuke | | 
80 | Sonar Pulse | | 
90 | GPS | | 

I have not ordered the TS powers because not all have been implemented yet.

2019-06-07 07:23 UTC, teinarss requested changes

2019-06-07 07:23 UTC, teinarss commented on OpenRA.Mods.Common/Widgets/SupportPowersWidget.cs
> +			var powers = spm.Powers.Values.Where(p => !p.Disabled).OrderBy(p => p.Info.SupportPowerPaletteOrder);
```
			var powers = spm.Powers.Values.Where(p => !p.Disabled).OrderBy(p => p.Info.SupportPowerPaletteOrder);
```

This should prolly be added to this also https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/ObserverSupportPowerIconsWidget.cs#L104

2019-06-07 07:37 UTC, abcdefg30 reviewed
Is there a specific reason you didn't apply this to TS?

2019-06-07 07:46 UTC, pchote commented
> I have not ordered the TS powers because not all have been implemented yet.

2019-06-07 07:58 UTC, abcdefg30 commented
Derp, I can't read any more apparently.

2019-06-07 09:17 UTC, dragunoff commented
Rebased and updated with requested changes.

2019-06-08 10:03 UTC, pchote reviewed
Minor code style nit, otherwise LGTM.

2019-06-09 14:03 UTC, dragunoff commented
Rebased and addressed style nits.

2019-06-09 14:37 UTC, ghost approved these changes
LGTM.

2019-06-09 15:12 UTC, Orb370 commented
The original reason I brought this up is because Chronoshift/Iron Curtain are time sensitive superpowers but often their hotkeys are different depending on what faction you are, and inconsistent depending on unlock order.

I think both superpowers should be *first*, that way no matter what other superpowers you have at least your hotkey will stay consistent.

2019-06-09 15:27 UTC, dragunoff commented
This is what I'm proposing here (allies, soviets, double tech):
![изображение](https://user-images.githubusercontent.com/1355810/59160856-9e539d80-8ae3-11e9-8ef8-b151535501cd.png)

@Orb370 If I understand you correctly you are suggesting that IC and chrono be at the top because they are the most time sensitive powers and should always be available via a hotkey (as there are only 4 hotkeys)?

2019-06-09 15:35 UTC, Orb370 commented
Yes. But also for people who play different factions, IC/Chrono will be on 3 different hotkeys depending on the faction. Ukraine, Russia, and Any Allied Faction respectively.

If it's always at the top then it doesn't matter what faction you are playing.

2019-06-09 15:40 UTC, matjaeck commented
> Yes. But also for people who play different factions, IC/Chrono will be on 3 different hotkeys depending on the faction. Ukraine, Russia, and Any Allied Faction respectively.
> 
> If it's always at the top then it doesn't matter what faction you are playing.

Not quite. The order of the powers does not directly correlate with the hotkey slots: If you only have one power, that power will always be in slot one. The support power slot hotkey always relates to the actual available powers, and only then to their order. So it is very possible that the hotkey for your powers change during the game (i.e. building an airfield before the nuke).


Would it make sense to start with the strongest power, something like this?

Index | RA | 
-- | -- |
10 | Nuke |
20 | Iron Curtain |
30 | Adv. Chronoshift |  
40 | Chronoshift |
50 | Parabombs |
60 | Paradrop | 
70 | Spy Plane |
80 | Sonar Pulse | 
90 | GPS |

2019-06-09 15:44 UTC, Orb370 commented
That is why I suggest moving them to the front. That way, it always slots into #1, regardless of what support powers you have.

Nukes have a long cooldown, take a long time to reach their target, and are a fire and forget. I think the original ordering is fine as far as that is concerned. I don't think I'd ever lose/win a game if I delayed my nuke by several seconds, but a IC/Chronoshift delayed by even a fraction of a second can make the difference.

2019-06-09 15:50 UTC, ghost requested changes
I think @Orb370 has a point here. When we move the nuke and ic/chrono up they will always be on the same hotkeys once they are build, which does make things easier.

2019-06-09 16:03 UTC, pchote commented
:+1: to putting IC/Chrono first, then nuke, then everything else.

2019-06-09 16:05 UTC, dragunoff commented
I agree with @Orb370. IC/Chrono usage is very time senstive and having a consistent hotkey (except in doble tech scenarios) can help with that. So  something like this: 

Index | RA
-- | --
10 | Iron Curtain
20 | Chronoshift
30 | Adv. Chronoshift
40 | Parabombs
50 | Paradrop
60 | Spy Plane
70 | Nuke
80 | Sonar Pulse
90 | GPS

Which results in this in-game (doble tech, allies, soviet):
![изображение](https://user-images.githubusercontent.com/1355810/59161222-aa8e2980-8ae8-11e9-8bea-edac354a2c7e.png)

* Getting both chronoshift and adv. chronoshift would be a very rare case so the second chronoshift here can be mostly igrnored.
* Nuke is near the bottom because games often don't reach that stage and if it had a higher priority it would disrupt the order when it becomes available. And as mentioned already - it has a long cooldown and usually the player has enough time to choose the target w/out a hotkey. Up for debate of course.

2019-06-09 16:34 UTC, matjaeck commented
To me it would make more sense to have the nuke / ic / chrono all in the first slots (IMO ordered by strenth and have the nuke in slot 1) but you got a point with

> if it had a higher priority it would disrupt the order when it becomes available

So I'm fine with both ways.

2019-06-09 22:52 UTC, dragunoff commented
Updated with the new order for RA as discussed.

2019-06-09 23:46 UTC, ghost approved these changes
Looks good with IC at start and nuke at bottom.

2019-06-15 07:55 UTC, abcdefg30 approved these changes

2019-06-15 07:55 UTC, merged

2019-06-15 07:56 UTC, abcdefg30 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f349a3644cec739bc18822b0544f7497cc88c976...222ff88239d56858be6b2329eb6f7a287e9296b1)