Add priority levels to production exits
OpenRA/OpenRA pull request #17183
Opened 2019-10-05 16:21 UTC by pchote

This PR adds the ability to specify multiple priorities for exits, with lower priorities only being considered if all higher priority exits are blocked.

This is used to fix the exit behaviour for TS barracks: each defines two normal exits (0,2 and 1,2 for GDI; 2,2 and 3,2 for Nod) and all the remaining perimeter cells as fallback.

<img width="576" alt="Screenshot 2019-10-05 at 17 13 25" src="https://user-images.githubusercontent.com/167819/66257700-59d7c600-e794-11e9-90ae-e81bd65b6954.png">

Fixes #10843.
Supersedes #17105.

2019-10-15 13:01 UTC, Mailaender commented on OpenRA.Mods.Common/Traits/Buildings/RallyPoint.cs
> +			var exits = priorityExits != null ? priorityExits.ToArray() : new ExitInfo[0];
What does the `new ExitInfo[0]` do?

2019-11-05 15:32 UTC, teinarss submitted a review, later dismissed

2019-11-17 20:28 UTC, ghost submitted a review, later dismissed

2019-11-19 20:21 UTC, tovl requested changes
It would be a good idea to add fallback exits to RA kennels as well, so we can close #16792.

2019-11-19 20:42 UTC, matjaeck commented
Purist comment:
![kennel](https://user-images.githubusercontent.com/37185497/69184544-59617780-0b15-11ea-990a-b99eb8c04689.gif)

2019-11-20 20:22 UTC, matjaeck commented
FWIW, my comment above was not meant to be an objection against adding fallback exits to the kennel. It's probably good enough.

2019-12-01 00:31 UTC, pchote commented
Rebased and updated Kennel exits:

<img width="346" alt="Screenshot 2019-12-01 at 00 28 44" src="https://user-images.githubusercontent.com/167819/69907715-dcb28100-13d1-11ea-80cb-de456cfd09e8.png">

The primary exit is to the bottom-left (-1,1). If this is blocked it will prefer (-1,0) and (0,1) before falling back again to the other 5 cells.

2019-12-01 18:04 UTC, tovl approved these changes
It might look better if the spawn point for the kennel exits (0, -1), (1, -1) and (1, 0) was placed more to the upper right. This is not a blocker though.

2019-12-05 16:15 UTC, tovl commented
@matjaeck @teinarss do you consider your +1 still valid?

2019-12-05 17:00 UTC, teinarss approved these changes

2019-12-05 17:01 UTC, merged

2019-12-05 17:07 UTC, teinarss commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/707636bce28b633585913c730b27bb3c68782095...60b6ac76d199e42fea75ef59a888bebd73d7500f