Add TransformsIntoTransforms to enable queued MCV redeploy.
OpenRA/OpenRA pull request #17615
Opened 2020-01-25 20:52 UTC by pchote

Fixes #17602.

2020-02-12 09:01 UTC, pchote commented
This has been sitting open on the milestone with no activity for quite a while now. Can we please get some movement here, even if that happens to be an "I don't think we should take this for the playtest"?

2020-02-15 10:31 UTC, Mailaender commented
Sorry, I can't test this as the ALT key is somehow blocked in KDE even in full screen mode and the conyard won't undeploy at all. See https://github.com/OpenRA/OpenRA/issues/15879 for making it a remappable key.

2020-02-15 10:59 UTC, pchote commented
@Mailaender try https://bbs.archlinux.org/viewtopic.php?id=109085

2020-02-15 11:14 UTC, Mailaender submitted a review, later dismissed
Works as promised.

2020-02-18 18:24 UTC, teinarss requested changes

2020-02-18 18:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/Buildings/TransformsIntoTransforms.cs
> +		Transforms[] transforms;
Not needed.

2020-02-18 18:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/Buildings/TransformsIntoTransforms.cs
> +		public readonly bool RequiresForceMove = false;
Not used.

2020-02-18 18:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/Buildings/TransformsIntoTransforms.cs
> +using OpenRA.Activities;
Not used.

2020-02-18 18:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/Buildings/TransformsIntoTransforms.cs
> +using OpenRA.Mods.Common.Orders;
Not used.

2020-02-18 18:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/Buildings/TransformsIntoTransforms.cs
> +		}
Not used after the change above.

2020-02-18 19:09 UTC, pchote commented
Fixed (first and third pushes) and rebased (second push).

2020-02-19 21:26 UTC, abcdefg30 submitted a review, later dismissed
Works as advertised. One thing however: When undeploying you can now issue deploy orders. However, when deploying you can also issue deploy orders (to immediately undeploy again) which are not executed. Not supporting immediate undeploy would not be an issue imho if the command bar icon for deploying was disabled.

2020-02-20 08:36 UTC, pchote commented
Hmm... this may require more thought then. I had always considered blocking immediate undeploy as a protection against accidental double keypresses so its not clear whether we want to support that. Keeping the current assymetric state of the PR also isn't great.

Would it be confusing if we only allowed this queued redeploy if the actor has moved to a different location?

2020-02-20 08:44 UTC, pchote commented
> However, when deploying you can also issue deploy orders (to immediately undeploy again) which are not executed.

Are you sure about this? https://github.com/OpenRA/OpenRA/pull/17615/files#diff-77ec43bbb0b6febb3e3e53220fef3002R37-R42 is supposed to make sure that you can only issue deploy orders when *un*deploying - the initial deploy animation should be handled by the make animation rather than Transforms.

2020-02-20 08:54 UTC, WhoCaresora commented
I don't see the interest of queuing order when deploying. the only case i see is more an exploit to make enemy's units re target something else. for me it should only be done on undeploying case.

The cases that comes in mind to deploy and mcv : 

- To have build radius and by extension placing a building. -- Queuing immediate undeploy would not gives you time place a single structure
- To have additional construction speed -- you want your mcv in conyard as long as possible
- changing mcv armor into conyard concrete -- You might want your mcv in conyard until the zone is safe.
- Make units attacking the mcv re-targeting onto something else and still continue to flee : I consider this as a game mechanic abuse and i would not encourage it by making it faster/more efficient.

2020-02-20 10:08 UTC, Punsho commented
> Hmm... this may require more thought then. I had always considered blocking immediate undeploy as a protection against accidental double keypresses so its not clear whether we want to support that. Keeping the current assymetric state of the PR also isn't great.
> 
> Would it be confusing if we only allowed this queued redeploy if the actor has moved to a different location?
A normal deploy order while deploying should definitely not queue an undeploy. If it was a case it would become a source of frustration to many people. However allowing shift-f to queue an undeploy should be done for the sake of consistency and player expectations. Though it is not necessary to do now as there are no ingame incentives for this action apart from providing temporary construction radius (what would be clunky and rarely the desired action)

2020-02-20 20:55 UTC, pchote commented
Fixed. The commandbar button now stays disabled unless shift is held to queue the redeploy.

2020-02-22 15:16 UTC, teinarss approved these changes

2020-02-23 18:16 UTC, pchote commented
I count two :+1:s here. @abcdefg30 did you want to take another look here or shall I merge this?

2020-02-24 11:56 UTC, abcdefg30 approved these changes

2020-02-24 11:56 UTC, merged

2020-02-24 11:59 UTC, abcdefg30 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a03d7bc235b3cf7d8fcb0588fbb190508c740dd0...824d9682500c26697974aaf185a2b7ad45f98877)