Add extra MCV placement logic
OpenRA/OpenRA pull request #17649
Opened 2020-02-06 00:51 UTC by NotoriousPyro

AI MCVs now place new MCVs near new tiberium fields, away from enemies buildings and its own previous con yards. Similar to a real player.

This modifies the previous logic, to:

1. Get a new random base center that is near a resource field, outside of the centered area of a previous random con yard location. Thus making the AI build outside of previous MCV locations.
2. The normal logic then is used (which selects a random location in the area based on step 1).
3. The MaxBaseRadius around the newly selected location is checked for enemies. If none exist we continue, otherwise we return null.
4. The MaxBaseRadius around the newly selected location is checked for previous construction yards or MCVs. If none exist in that location we continue, otherwise we return null.

Here are a few screenshots of a tweaked AI I created to produce the additional MCVs:
![image](https://user-images.githubusercontent.com/706132/73895994-602c9a80-4879-11ea-8506-8e8f617891ca.png)

![image](https://user-images.githubusercontent.com/706132/73896351-a8988800-487a-11ea-9179-f9144142c191.png)

![image](https://user-images.githubusercontent.com/706132/73896014-6fabe380-4879-11ea-8e52-9922cfe03d69.png)

2020-02-06 11:24 UTC, teinarss requested changes

2020-02-06 11:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
> +			CPos baseCenter = GetRandomBaseCenter(distanceToBaseIsImportant);
use `var` here.

2020-02-06 11:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
> +			WDist newBaseRadius = new WDist(Info.MaxBaseRadius * 1024);
Same here.

2020-02-06 11:24 UTC, teinarss commented on OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
> +			resourceTypeIndices = new BitArray(tileset.TerrainInfo.Length);
You can join these two `var resourceTypeIndices = new BitArray(tileset.TerrainInfo.Length);`

2020-02-06 13:44 UTC, NotoriousPyro commented
Ah, yes I seem to have missed that as part of the coding standards. I will make these changes later.

2020-02-06 20:59 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
> +			if (distanceToBaseIsImportant == false)
This can simplify to `if (!distanceToBaseIsImportant)`.

2020-02-06 21:21 UTC, NotoriousPyro commented
I have added that change, and also a change to make the MCV placement avoid any enemy units not only buildings, as the AI was trying to place MCVs next to squads.

2020-02-13 19:49 UTC, NotoriousPyro commented
I think I may have accidentally included a merge from one of my other branches into this PR...

2020-02-13 20:05 UTC, NotoriousPyro commented
I'll reopen this commit when I've fixed it up in a separate branch.

2020-02-13 20:05 UTC, closed without merging