Fix AutoTarget regression
OpenRA/OpenRA pull request #17754
Opened 2020-03-01 20:13 UTC by pchote

This PR fixes #17751 by reverting #17619.

The original issue was introduced by #16797 making aircraft call TickIdle, so a much simpler "fix" for #17476 (i.e. restore the previous behaviour) is to simply disable the idle scanning from RA yak and Mig.

2020-03-01 23:54 UTC, pchote commented
Ping @netnazgul and @Punsho to confirm that this fixes both the old and new issues.

2020-03-02 08:46 UTC, PunkPun requested changes
It fixes both, however helicopters also do chase if they acquire a target on defend stance and it moves out of range. 

It is not critical to address it here and right now but planes do not honour attack everything stance, they do not give chase

2020-03-02 10:05 UTC, pchote commented
That is also the behaviour on release, and the goal here is to focus on the regression with as little risk as possible.

2020-03-02 10:17 UTC, pchote commented
That is also the behaviour on release, and the safest option here is to not try and change that.

It looks like `FlyAttack` has always ignored the `allowMove` flag, but its not yet clear how difficult or risky that will be to fix.

2020-03-02 16:49 UTC, abcdefg30 approved these changes

2020-03-02 17:20 UTC, netnazgul commented
Original issue with tanks (and Longbows) is fixed.

Aircrafts do not return to rearm when given an attack order and out of ammo, is this intended or another regression?

2020-03-02 18:58 UTC, pchote commented
> Aircrafts do not return to rearm when given an attack order and out of ammo, is this intended or another regression?

We clarified on discord that this was referring to attack-move, which is intentional behaviour and already in the current release.

2020-03-02 18:59 UTC, netnazgul approved these changes

2020-03-02 20:31 UTC, matjaeck commented
> > Aircrafts do not return to rearm when given an attack order and out of ammo, is this intended or another regression?

> We clarified on discord that this was referring to attack-move, which is intentional behaviour and already in the current release.

Changed in #17573, first comment is related to the discussion in #16668.

2020-03-02 21:22 UTC, merged

2020-03-02 21:23 UTC, abcdefg30 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/d7e75fdb93d93e71357f67dbab464d8e1328efa1...f11dcbd94ca6315cfd7699f90937033ca468c6cf)