Merge Destroy- and CreateResource warheads
OpenRA/OpenRA pull request #18012
Opened 2020-05-01 11:08 UTC by reaperrr

Not only does this mean one less warhead to maintain, it also now allows to reliably remove pre-existing resources before spawning new ones, without having to fiddle with delays or order of warheads to ensure the freshly added resources aren't immediately removed again.

2020-05-02 20:22 UTC, atlimit8 requested changes
It looks like you forgot the `s` in the rule and then applied it.

2020-05-02 20:22 UTC, atlimit8 commented on OpenRA.Mods.Common/UpdateRules/Rules/MergeResourceWarheads.cs
> +				crwh.ReplaceValue("ModifyResource");
It is `RemoveResources` in `ModifyResourceWarhead`.
```suggestion
				crwh.ReplaceValue("ModifyResources");
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/cnc/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/cnc/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/cnc/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/cnc/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/explosions.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/explosions.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/explosions.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/explosions.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/explosions.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/explosions.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ra/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ts/weapons/otherweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-02 20:22 UTC, atlimit8 commented on mods/ts/weapons/superweapons.yaml
> +		RemoveResource: true
```suggestion
		RemoveResources: true
```

2020-05-08 10:41 UTC, reaperrr commented
Leaving the singular vs plural issue aside, I'm beginning to wonder whether it would be smarter to tackle the TODOs while I'm at it, otherwise we'd have to replace the boolean again in a future refactor. I have other stuff in the pipeline that's higher priority for me though, so this will probably stay stale for a while.

2020-10-03 19:14 UTC, reaperrr commented
Will probably take some time until I get back to this, closing for now.

2020-10-03 19:14 UTC, closed without merging