Replace TraitContainer AllEnumerator.
OpenRA/OpenRA pull request #18357
Opened 2020-07-04 19:00 UTC by anvilvapre

Replace TraitContainer.All() that uses the custom AllEnumerator with
TraitContainer.ApplyToAllX() that takes an action as argument.

The AllEnumerator.Current function show up in profiling reports since it is
used each tick multiple times for multiple traits. The function is 'heavy'
because it creates TraitPair<T>'s temporary objects for each actor
trait combination.

In the past about 20k ITick trait pairs were present during an average
multi player game.

Using an Apply function that takes an action avoid the need to create
these temporary objects.

To be able to still use 'DoTimed' somewhat efficiently the measurement
was moved to inside the trait container method.

Results in a 25% performance improvement in accessing all traits of
a certain type.

Apply function could be used for other TraitContainer functions as well
for further improvements.

The apply function is currently only used in the main loop to
call ITick and IRenderTick.

Test result for calling on a dummy trait on 20k actors a 1000 times:
  1315 ms traitcontainer.AllEnumerator (current)
   989 ms traitcontainer.Apply (this commit)

Thank you for your contribution to OpenRA!

Please be aware that we do not have enough project maintainers to match the rate of contributions, so it may take several days before somebody is able to respond to your Pull Request.

You can help speed up the review process by following a few steps:

* Make sure that you have read and understand the OpenRA Coding Standard (see https://github.com/OpenRA/OpenRA/wiki/Coding-Standard).
* Write quality commit messages (see https://chris.beams.io/posts/git-commit/).
* Only commit changes that directly relate to your Pull Request.  Use your Git interface to unstage any unrelated changes to project files, line endings, whitespace, or other files.
* Review the code diff view below to double check that your changes satisfy the above three points.
* Use the `make test` and `make check` commands to check for (and fix!) any issues that are reported by our automated tests.
* If you are changing shared mod or engine code, make sure that you have tested your changes in all four default mods.
* Respond to review comments as soon as you reasonably can.  Reviewers will usually prioritize Pull Requests that are still fresh in their minds.  Make sure to leave a comment when you push new changes, otherwise GitHub does not automatically notify reviewers!
* Leave a polite comment asking for reviews if a week or more has passed without feedback.

If you need any help you can ask in the #openra IRC channel on freenode (most active during European evenings).

2020-07-05 09:50 UTC, reaperrr commented on OpenRA.Game/TraitDictionary.cs
> +			long longTickThresholdInStopwatchTicks, Action<long, long, Actor, T> thresholdExeedAction)
Should be Ex**c**eed.

2020-07-05 18:11 UTC, teinarss commented
Did some benchmarking on this change, ticktime.
![image](https://user-images.githubusercontent.com/19173272/86539312-bf134000-befb-11ea-9c48-1159ff08447a.png)

2020-07-05 18:29 UTC, anvilvapre commented
How did you do this?

How do i read the graph? More frequently a tick takes less time? Up to let's say 2 at best 5ms?

2020-07-26 09:22 UTC, teinarss commented
Sorry for the late answer, i'm using these scripts to run and generate the graph and data. https://github.com/teinarss/openrabenchmark

2020-10-18 14:54 UTC, pchote commented
I somehow lost track of this in the backlog of PRs, sorry. The tick histogram suggests that this is definitely worthwhile to proceed with. Can you please rebase this against latest bleed and squash the fixups?

@RoosterDragon since you've recently popped your head up again, do you have any thoughts on this PR?

2020-10-18 16:06 UTC, RoosterDragon requested changes
Shame to have to bake in timing logic to TraitDictionary, but clearly worth the perf here.

Per my comments, I would suggest embracing the fact we're making a perf tradeoff here and avoiding trying to keep things abstract - it should result in less contorted code.

2020-10-18 16:06 UTC, RoosterDragon commented on OpenRA.Game/TraitDictionary.cs
> +			{
We already bake in knowledge of `PerfTimer` directly in other places with timing code like this. You can do so here and well and avoid having to pass in obtuse parameters like `longTickThresholdInStopwatchTicks` or Actions with inscrutable signatures like `Action<long, long, Actor, T>`.

i.e. Just use `PerfTimer.LongTickThresholdInStopwatchTicks` and `PerfTimer.LogLongTick` in the method body directly and remove the parameters for those.

2020-10-18 16:06 UTC, RoosterDragon commented on OpenRA.Game/World.cs
> +			WorldUtils.DoTimed<Actor, T>(TraitDict.ApplyToActorsWithTraitTimed<T>, action, "Trait");
No need for a public helper here, I'd remove this and just call `TraitDict.ApplyToActorsWithTraitTimed` from the `Tick` and `TickRender` methods as needed.

(Also the `text` parameter was ignored here, if for some reason this makes sense to keep)

2020-10-18 16:06 UTC, RoosterDragon commented on OpenRA.Game/WorldUtils.cs
> +			Action<A, T> action, string text)
The attempt to abstract `PerfTimer` away into only this method is a bit lacking. `Action<Action<A, T>, long, Action<long, long, A, T>> func` is a bit mad, and yet still not abstract enough as I'm restricted to dealing with an `A` and `T` which sucks if I want to time something that doesn't deal with 2 items.

I'd remove this - you're baking timing logic into `TraitDictionary` to deal with the fact the current timing abstraction has too much perf overhead - let's just embrace that. It saves us having to deal with weird contortions like this.

2020-10-21 09:51 UTC, pchote reviewed
Can you please rebase this (OpenRA conventions are to avoid merge commits in PRs) and squash the fixups into the original commit ready to merge?

2020-10-21 09:51 UTC, pchote commented on OpenRA.Game/TraitDictionary.cs
> +				{
OpenRA code style is to omit braces around single line blocks.

2020-10-21 11:38 UTC, anvilvapre commented
`Primitives/MergedStream.cs(22,8): error CS8026: Feature 'readonly automatically implemented properties' is not available in C# 5. Please use language version 6 or greater. [/home/taol/source/cs/OpenRA/OpenRA.Game/OpenRA.Game.csproj]`

2020-10-21 11:41 UTC, pchote commented
That will be caused by merging instead of rebasing. You should never use `git pull`, always fetch and rebase to prevent problems like this and allow for a cleaner git history.

See https://github.com/OpenRA/OpenRA/wiki/Contributing#keeping-up-to-date-rebasing

2020-10-21 11:44 UTC, anvilvapre commented
Both times i thought i did do a rebase(?).

$ git checkout bleed
$ git pull bleed origin
$ git checkout mybranch
$ git rebase bleed
$ git push remote branch

2020-10-21 11:55 UTC, pchote commented
> Both times i thought i did do a rebase(?).

Unfortunately not: see https://github.com/OpenRA/OpenRA/pull/18357/commits which still shows several merge commits.

>  $ git push remote branch

GitHub will be rejecting this because you need to use force-push to overwrite history.
Use:
```
git checkout perf_traitdict_apply
git rebase -i upstream/bleed
# This will open an editor window, change the "pick" after your fixup commits to "fixup" to squash them into the commit above
# save and exit to start the rebase
# deal with any conflicts if they occur, resolve using git add and git rebase --continue
git push origin +perf_traitdict_apply
```

2020-10-21 12:16 UTC, pchote commented
I'm not sure how you managed it, but the final commit (the second "Changes as proposed. Pull use of PerfTimer into TraitDictionary, less…") is now trying to undo all of the changes that were merged into the repo over the last couple of months.

You can remove this by doing an interactive rebase and deleting the line for this commit in the action list that comes up. While you are there please do the pick &rarr; fixup (or squash) change like I suggested above to squash the fixup commits into the first  into the first commit.

2020-10-23 15:42 UTC, RoosterDragon approved these changes

2020-10-29 21:20 UTC, pchote approved these changes

2020-10-29 21:21 UTC, merged

2020-10-29 21:22 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/fa312b53717e490b3bdda37a17d396eb0aa8e0a2