Convert trait/missile facings and rotation speeds to WAngle
OpenRA/OpenRA pull request #18382
Opened 2020-07-09 21:11 UTC by pchote

This PR takes one of the final steps to completing the facing &rarr; WAngle conversion. Now only turrets, missiles, and a couple of other small pieces are left using the old system.

Closes #15196.

I have converted everything that ran through `WAngle.FromFacing` - it is possible that I have missed one or two things that kept everything as integers, but all the previous PRs have hopefully already removed those cases.

2020-07-09 21:25 UTC, pchote commented on OpenRA.Mods.Common/Traits/Air/Aircraft.cs
>  		[Desc("Turn speed to apply when aircraft flies in circles while idle. Defaults to TurnSpeed if negative.")]
"Defaults to TurnSpeed if undefined".

This is a trivial change, so will leave it until there are other review comments.

2020-07-09 21:27 UTC, reaperrr commented on OpenRA.Mods.Common/Traits/Air/Aircraft.cs
>  		[Desc("Turn speed to apply when aircraft flies in circles while idle. Defaults to TurnSpeed if negative.")]
Should be "Defaults to TurnSpeed if undefined." now, I guess.

2020-07-09 21:35 UTC, reaperrr commented
Looks good to me, won't have time to test it before Sunday next week at the earliest, though. Feel free to count this as +1 if it needs to be merged earlier.

2020-07-09 23:21 UTC, tovl commented on OpenRA.Mods.Common/Traits/Mobile.cs
> +		public readonly WAngle TurnSpeed = new WAngle(1023);
Anything higher than 512 is pointless, so maybe we should change the default value here?

2020-07-09 23:22 UTC, tovl commented on OpenRA.Mods.Common/Traits/Turreted.cs
> +		public readonly WAngle TurnSpeed = new WAngle(1023);
Same here.

2020-07-09 23:25 UTC, tovl commented on OpenRA.Mods.Common/Traits/Air/Aircraft.cs
> +		public readonly WAngle TurnSpeed = new WAngle(1023);
and here

2020-07-09 23:26 UTC, tovl commented
We should aim to get this merged before continuing with #18322

2020-07-10 11:46 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeploy.cs
> +			canTurn = info.Facing.HasValue && self.Info.HasTraitInfo<IFacingInfo>();
`canTurn` is now no longer used.

2020-07-10 17:02 UTC, pchote commented
Fixed and rebased.

2020-07-10 18:07 UTC, pchote commented
I missed `AttackPopupTurreted.DefaultFacing`.

2020-07-12 13:38 UTC, pchote commented
Rebased and fixed.

2020-07-12 13:47 UTC, abcdefg30 commented on mods/cnc/rules/structures.yaml
> +		TurnSpeed: 1023
This probably wants to be `512` now, too?

2020-07-12 14:07 UTC, pchote commented
Updated gwtr, atwr, msam turret speeds.

2020-07-12 17:32 UTC, abcdefg30 commented on mods/ra/rules/structures.yaml
> +		TurnSpeed: 1023
This here probably as well.

2020-07-12 17:32 UTC, abcdefg30 commented on mods/ra/rules/structures.yaml
> +		TurnSpeed: 1023
And here and above.

2020-07-12 17:32 UTC, abcdefg30 commented on OpenRA.Mods.Common/Activities/Air/FallToEarth.cs
> +			if (!info.MaximumSpinSpeed.HasValue || info.MaximumSpinSpeed.Value != WAngle.Zero)
Imho it would be better to write this as `if (acceleration != 0)`.

2020-07-12 17:51 UTC, pchote commented
Fixed and rebased on top of the TD balance changes.

2020-07-12 18:29 UTC, abcdefg30 requested changes
The voxel harvester docking looks a bit off:
![grafik](https://user-images.githubusercontent.com/7704140/87253802-3b6acd80-c47e-11ea-81e0-fff47ca84a64.png)

2020-07-12 19:04 UTC, pchote commented
Forgot to account for `TiberianSunRefinery` which inherited `DockAngle` from `Refinery`. Fixed.

2020-07-17 17:19 UTC, pchote commented
Rebased.

2020-07-17 20:46 UTC, abcdefg30 approved these changes

2020-07-19 08:40 UTC, reaperrr approved these changes

2020-07-19 08:41 UTC, merged

2020-07-19 08:42 UTC, reaperrr commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/77f3eb5d61771b06792c3e6b3b025a4856156ca4...6187f63c7eeee1b13f1d042ac4be6d63c28a1a18