Make AI Ignore HasAdequateRefineryCount if no RefineryTypes are defined.
OpenRA/OpenRA pull request #18484
Opened 2020-08-03 07:59 UTC by MustaphaTR

And unhardcode MinimumRefineryCounts for AI. I did the later with `Initial - Additional` instead of `Before - After` so we can ensure `Before <= After`.

The first one is for RV's Megawealth mode where Refineries do not exist, as such AI wasn't building anything before during this mode. I created seperate BaseBuilder and UnitBuilder traits for the gamemode so AI can at least do something with this mode.

2020-08-03 08:03 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
> +		public readonly int InititalMinimumRefinery = 1;
This (and below) should probably end with `Count`?

2020-08-03 23:33 UTC, phrohdoh requested changes

2020-08-03 23:33 UTC, Phrohdoh commented on OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
> +		public readonly int InititalMinimumRefinery = 1;
```suggestion
		public readonly int InitialMinimumRefineryCount = 1;
```

2020-08-03 23:33 UTC, Phrohdoh commented on OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
> +		[Desc("Amount of refinery to build before building a barracks.")]
```suggestion
		[Desc("Number of refineries to build before building a barracks.")]
```

2020-08-03 23:33 UTC, Phrohdoh commented on OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
> +		[Desc("Amount of refinery to build additionally after building a barracks.")]
```suggestion
		[Desc("Number of refineries to build additionally after building a barracks.")]
```

2020-08-03 23:33 UTC, Phrohdoh commented on OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
> +		public readonly int AdditionalMinimumRefinery = 1;
```suggestion
		public readonly int AdditionalMinimumRefineryCount = 1;
```

2020-08-04 11:40 UTC, MustaphaTR commented
Updated the names as suggested.

2020-08-04 12:31 UTC, phrohdoh approved these changes

2020-08-05 09:29 UTC, abcdefg30 approved these changes
This isn't too invasive, so I guess we can take it since it will be quite some time until we rework this module.

2020-08-05 09:29 UTC, merged

2020-08-05 09:31 UTC, abcdefg30 commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3a57786f931a144a3d20ed049c3b8b9747de6ea5...9f076b496583d4fc2bc102d9c8f47bbbf64279fd)