Rewrite spawn point assignment logic.
OpenRA/OpenRA pull request #18672
Opened 2020-10-03 15:18 UTC by pchote

The current spawn point code does a poor job of distinguishing between what are actually three different things:
* The spawn point selected in the lobby:
  * Only relevant for client players (humans + bots)
  * Needs a way to represent "no specific choice / random"
  * Abstract labels that do not care about a physical location
* Resolved spawn points for game init, replays, and server browser:
  * Still only relevant for client players
  * No random choice - every player is matched to a specific label
  * Abstract label, but does care about position (for the "separate team spawns" option - which I was originally going to fix properly in this PR but dropped from here to avoid mixing refactoring with behaviour changes)
 * Player "Home" position:
   * Relevant for *all* players, including scripted ones - support powers and other traits may change their behaviour based on it.
   * No random choice - every player is matched to a specific location
   * Position, not a label - and we need a way to assign this for scripted players without making things awkward for the Lobby UI.

This PR reworks the backend logic to be more sensible, accounting for the new use cases from PRs like #17578, #18425, #18111, #18238.

2020-10-03 15:48 UTC, reaperrr commented
> Traits/World/MPStartLocations.cs(108,48): error SA1001: Commas should not be preceded by whitespace. [/home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj]

2020-10-03 15:52 UTC, pchote commented
Fixed.

2020-10-09 23:21 UTC, pchote commented
Rebased.

2020-10-12 11:32 UTC, abcdefg30 commented on OpenRA.Game/Map/PlayerReference.cs
> +		/// Map players always ignore this and use SpawnLocation directly.
`SpawnLocation` -> `HomeLocation`?

2020-10-12 11:32 UTC, abcdefg30 commented on OpenRA.Game/Player.cs
> +			var assignSpawnPoints = world.WorldActor.TraitOrDefault<IAssignSpawnPoints>();
This should be moved inside the if branch since it is only used there.

2020-10-12 11:32 UTC, abcdefg30 commented on OpenRA.Mods.Common/Traits/World/MPStartLocations.cs
> +		Dictionary<int, Session.Client> occupiedSpawnPoints;
This can be made readonly since the dictionary creation itself doesn't depend on `Created`.

2020-10-12 11:41 UTC, pchote commented
Fixed.

2020-10-12 12:44 UTC, abcdefg30 commented
This immediately crashes when starting Fort Lonestar which uses the Spawn property. I assume we want to keep the C# code as is, so we need to adjust the Lua part.

2020-10-12 12:59 UTC, pchote commented
Fixed.

2020-10-13 13:59 UTC, abcdefg30 submitted a review, later dismissed

2020-10-13 18:03 UTC, teinarss requested changes

2020-10-13 18:03 UTC, teinarss commented on OpenRA.Mods.Common/Traits/World/MPStartLocations.cs
> +using OpenRA.Support;
Not needed :D

2020-10-13 18:18 UTC, pchote commented
Fixed.

2020-10-13 18:41 UTC, teinarss approved these changes

2020-10-13 18:41 UTC, merged

2020-10-13 18:45 UTC, teinarss commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f3c2409b5e1c1d494f0fca071b0e2679237c7413...d2349b342b5407061e5fb281a9f2bece3ce0ecb8