Server DispatchOrdersToClients create frame once for all clients.
OpenRA/OpenRA pull request #18806
Opened 2020-11-01 23:18 UTC by anvilvapre

Avoid creating frame data per client connection. Avoid
the allocation of a memory stream and setting frame header
and copying frame data.

2020-11-02 12:09 UTC, abcdefg30 submitted a review, later dismissed
Code changes lgtm.

2020-11-03 23:36 UTC, Leonardo-Ferreira requested changes

2020-11-03 23:36 UTC, Leonardo-Ferreira commented on OpenRA.Game/Server/Server.cs
> +			return ms.ToArray();
Do not use `ToArray` when you know that `ms.Capacity == ms.Length`, use `GetBuffer`.
Also, dispose the MemoryStream.

2020-12-24 23:43 UTC, pchote approved these changes

2020-12-24 23:43 UTC, merged

2020-12-24 23:44 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5d5e3069c9a1a0e5fbf7daa4dc5085833032dfcd