Fix RA infantry death anims playing too fast
OpenRA/OpenRA pull request #19096
Opened 2021-01-29 15:14 UTC by reaperrr

I noticed this literally years ago, but whenever it stood out to me I was to busy with testing something and forgot about it before I could file a PR.

Matches TD death anim speeds, is more consistent with most other animations and simply looks better this way.
Should be picked to prep, in my opinion.

2021-01-29 15:16 UTC, reaperrr commented on mods/ra/sequences/infantry.yaml
> +		Length: 8
Pretty sure 7 was a typo/error, so I sneaked this in as well.

2021-01-29 15:16 UTC, reaperrr commented on mods/ra/sequences/infantry.yaml
> +		Length: 8
Same here.

2021-01-29 18:10 UTC, dragunoff requested changes
This indeed looks better in-game. It should be applied to the sniper as well. Perhaps you missed it.

2021-01-30 00:57 UTC, Smittytron submitted a review, later dismissed
Looks good 👍

2021-01-30 01:13 UTC, reaperrr commented
> It should be applied to the sniper as well. Perhaps you missed it.

I had thought we didn't use the Sniper anymore, but forgot to make sure. Fixed.

2021-01-30 01:23 UTC, pchote approved these changes
> I noticed this literally years ago, but whenever it stood out to me I was to busy with testing something and forgot about it before I could file a PR.

Likewise. Thanks for finally fixing this!

2021-01-30 01:23 UTC, merged

2021-01-30 01:25 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/0d1d399a7a18acbd59e9681ed7bba124ddb7d1ec

de6a9dc8da