Added faction-specific units for colorpicker previews in TS
OpenRA/OpenRA pull request #19570
Opened 2021-07-28 10:14 UTC by penev92

Requested by @VonNah  on Discord and also showcases a feature the engine has but we don't use anywhere.

2021-07-28 19:21 UTC, abcdefg30 requested changes, later dismissed
```
OpenRA.Utility(1,1): Error: Actor harv.colorpicker is not constructible; failure: ActorInfo("harv.colorpicker") failed to initialize because of the following:
Missing:
OpenRA.Mods.Common.Traits.Render.RenderSpritesInfo 
Unresolved:
OpenRA.Mods.Common.Traits.Render.WithIdleOverlayInfo: { OpenRA.Mods.Common.Traits.Render.RenderSpritesInfo }
OpenRA.Mods.Common.Traits.Render.WithHarvestOverlayInfo: { OpenRA.Mods.Common.Traits.Render.RenderSpritesInfo }
```
etc. are failing. Also not sure if we shouldn't use the mcv instead of a harvester for "random".

2021-07-28 19:22 UTC, penev92 commented
I initially went for MCV, but that had very little player color remap area so I figured the Harvester would show the chosen color better.  🤷‍♂️

2021-07-28 19:25 UTC, pchote commented
That was indeed why this wasn't using the MCV in the first place 👍 for using the harvester.

IMO the tick tank is a bit too small compared to the titan - what if we changed that to the APC, and then scaled everything up a bit in the preview?

2021-07-28 19:27 UTC, pchote commented
I would also be okay with using the harvester for everything and not having faction-specific previews, but I realise that defeats half of the purpose of this PR.

2021-07-31 11:06 UTC, penev92 commented
I really liked the idea of having Titan vs Tick Tank since those are the "main battle tanks" of each faction.
The APC shows the color best, sure, but it is a meh unit to have.
We could also have Mobile MRLS vs Stealth Tank?
![image](https://user-images.githubusercontent.com/7137365/127737910-ba01fb76-5750-41f5-a3d2-0c2029a4c67d.png)
We can also change the facing to an angle that is more suitable to the specific units we pick.

2021-07-31 19:34 UTC, Smittytron commented
> We could also have Mobile MRLS vs Stealth Tank?

👍

2021-09-21 19:33 UTC, penev92 commented
Changed to:
Any - Harvester
GDI - Hover MLRS
Nod - Stealth Tank

Scaled up the actor previews a bit.

2021-09-25 14:55 UTC, Smittytron approved these changes, later dismissed
LGTM

2021-09-25 15:00 UTC, pchote reviewed
Just one minor nit, otherwise LGTM

2021-09-25 15:00 UTC, pchote commented on mods/ts/rules/world.yaml
> +			Random: harv.colorpicker
Better to keep `PreviewActor` available as a fallback:
```
PreviewActor: harv.colorpicker
FactionPreviewActors:
	gdi: hvr.colorpicker
	nod: stnk.colorpicker
```

2021-10-12 22:23 UTC, penev92 commented on mods/ts/rules/world.yaml
> +			Random: harv.colorpicker
I don't get it. Maps aren't allowed to add factions, so what could go wrong here to need a fallback?

2021-10-12 22:27 UTC, pchote commented on mods/ts/rules/world.yaml
> +			Random: harv.colorpicker
Well its more of a general style nit than a specific problem, the current definition is basically

```
switch
{
    case a: ...
    case b: ...
    case c: ...
}
```
whereas i'm suggesting
```
switch
{
    case a: ...
    case b: ...
    default: ...
}
```
which is hopefully more clearly robust.

2021-10-12 22:29 UTC, penev92 commented on mods/ts/rules/world.yaml
> +			Random: harv.colorpicker
In situations where you're guaranteed your cases will only ever be `a`, `b` or `c` I'm not a big fan of that but I'm not going to argue.

2021-10-12 22:31 UTC, pchote commented on mods/ts/rules/world.yaml
> +			Random: harv.colorpicker
I realize this is arguing over a trivial point, but my gut feeling is that this would otherwise become just another confusing crash for a newbie modder who wants to get started by adding a new faction to their favourite mod.

2021-10-12 22:44 UTC, penev92 commented
Updated as requested.

2021-10-13 21:56 UTC, abcdefg30 approved these changes

2021-10-13 21:59 UTC, merged