Add mediator and remove AddTextNotification from OrderManager
OpenRA/OpenRA pull request #19607
Opened 2021-08-14 15:00 UTC by teinarss

2021-08-15 16:16 UTC, pchote commented
There's a lot of overlap between `Mediator` and our `TypeDictionary`. It would be good to think about whether we can either use `TypeDictionary` as-is, otherwise what kind of changes would be needed for that to work in this case.

2021-08-30 18:49 UTC, teinarss commented
Updated with using `TypeDictionary`, 

Todo:
* Clear NotificationsCache when the game has ended?

2021-09-27 17:37 UTC, teinarss commented
Updated.

2021-12-01 18:06 UTC, Mailaender commented
Needs a rebase
> No description provided.

and some hints what is actually achieved here.

2022-07-12 14:48 UTC, Punsho commented
I could potentially use this to fix https://github.com/OpenRA/OpenRA/pull/20100#discussion_r916687431

2022-07-12 15:58 UTC, teinarss commented
rebased.

2022-07-13 08:26 UTC, PunkPun requested changes
This works ok in lobby but crashes instantly ingame when you write a message

<details closed>
<summary>Crash</summary>
Exception of type `System.InvalidOperationException`: TypeDictionary contains multiple instances of type `OpenRA.Widgets.INotificationHandler`1[OpenRA.TextNotification]`
   at OpenRA.Primitives.TypeDictionary.Get(Type t, Boolean throwsIfMissing) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Primitives/TypeDictionary.cs:line 64
   at OpenRA.Primitives.TypeDictionary.Get[T]() in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Primitives/TypeDictionary.cs:line 51
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Network/UnitOrders.cs:line 30
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Network/OrderManager.cs:line 166
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Network/Connection.cs:line 287
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Sync.cs:line 205
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Game.cs:line 624
   at OpenRA.Game.LogicTick() in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.Loop() in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Game.cs:line 804
   at OpenRA.Game.Run() in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Game.cs:line 857
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Game/Game.cs:line 296
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/gustas/Documents/GitHub/OpenRA/OpenRA.Launcher/Program.cs:line 32
</details>

ps. you didn't rebase on latest bleed but this was good enough for me

2022-07-13 08:26 UTC, PunkPun commented on OpenRA.Game/TextNotificationsManager.cs
> +		public static void Dispose()
`TextNotificationsManager` isn't `IDisposable` so the method should not be called `Dispose`

2022-07-13 15:37 UTC, teinarss commented
Updated.

2022-07-13 18:30 UTC, abcdefg30 commented on OpenRA.Game/Widgets/Widget.cs
> +				}
Missing braces on the outer `if`.

2022-07-13 18:30 UTC, abcdefg30 commented on OpenRA.Test/OpenRA.Game/MediatorTest.cs
> +﻿using NUnit.Framework;
Missing header.

2022-07-13 18:47 UTC, Punsho reviewed
LGTM, just a few suggestions

2022-07-13 18:47 UTC, Punsho commented on OpenRA.Game/Game.cs
> +			TextNotificationsManager.Clear();
Perhaps add a comment here. It feels rather out of place here. Perhaps something like this or more indepth

> Refresh TextNotificationsManager before the game starts

fwiw I'm planning to insert MutedPlayers.Clear() into the this method

2022-07-13 18:47 UTC, Punsho commented on OpenRA.Game/TextNotificationsManager.cs
> +		public static IReadOnlyList<TextNotification> Notifications => NotificationsCache;
Just a small nit, IMO there shouldn't be a space between `NotificationsCache` and `Notifications`

2022-07-14 15:40 UTC, teinarss commented
Updated

2022-07-14 15:53 UTC, Punsho submitted a review, later dismissed

2022-07-14 20:57 UTC, abcdefg30 approved these changes, later dismissed
Lgtm otherwise.

2022-07-14 20:57 UTC, abcdefg30 commented on OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameChatLogic.cs
> +		public void Handle(TextNotification notification)
Please implement these interfaces explicitly if possible:
```suggestion
		void INotificationHandler<TextNotification>.Handle(TextNotification notification)
```
(here and the two others below.)
That makes the code more readable by indicating where the `Handle` method belongs to.

2022-07-15 15:29 UTC, teinarss commented
Fixes

2022-07-15 16:19 UTC, PunkPun approved these changes

2022-07-15 16:19 UTC, merged

2022-07-15 16:22 UTC, Punsho commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8d968c292f84280c72ff57e98a2d748c9c94566f...ec33cf4e85e04f1a97c9ac024a0257d08dc104fa