Make map editor aware of dynamic map updates
OpenRA/OpenRA pull request #20123
Opened 2022-07-11 11:54 UTC by Punsho

depends on #20031

This just adds user dialog

2022-08-08 17:36 UTC, PunkPun commented
Updated the PR to also cover #14254

2022-08-13 15:23 UTC, Mailaender commented
It freezes the game when I
1. create test.oramap
2. unarchive test.oramap into folder test
3. edit test/map.yaml
4. save as test.oramap

2022-08-15 15:18 UTC, PunkPun commented
> It freezes the game when I
> 
> 1. create test.oramap
> 2. unarchive test.oramap into folder test
> 3. edit test/map.yaml
> 4. save as test.oramap

Couldn't reproduce. Rebased

2022-08-18 12:12 UTC, dragunoff commented
This doesn't seem to work properly when deleting a map and trying to create a new map with the same filename. Repro steps:
1. Create a new map test.oramap
2. Exit map editor
3. Delete the test.oramap (either from outside or from ingame)
4. Go to map editor and try to create a new map named test.oramap
Expected: The new map can be created because a map with the same name doesn't exist
Actual: A warning is displayed "By saving you will overwrite an already existing map."

2022-08-18 12:16 UTC, dragunoff commented
And another minor issue:
1. Create a new test.oramap
2. Delete map from outside
3. Try to save map from map editor
Expected: The map saves without any prompts
Actual: A warning is displayed "The map has been edited from outside the editor. By saving you may overwrite progress"

2022-08-18 12:20 UTC, dragunoff commented
Also this doesn't track any changes to `map.yaml` of unpacked maps.
1. Create an unpacked map
2. Change the map name in `map.yaml` from outside
3. Make some changes and save the map from within the editor
The map saves without warnings and overwrites the outside changes but maybe this is the expected behavior?

2022-08-18 12:35 UTC, PunkPun commented
This is weird, when a map is deleted its package should be deleted as well, thus not triggering any of the prompts

2022-08-19 14:40 UTC, PunkPun commented
I've added more checks to fix https://github.com/OpenRA/OpenRA/pull/20123#issuecomment-1219416431 and https://github.com/OpenRA/OpenRA/pull/20123#issuecomment-1219420490. I was not able to reproduce https://github.com/OpenRA/OpenRA/pull/20123#issuecomment-1219423604

I've also made the code cleaner and checks easier to understand

2022-08-25 08:50 UTC, dragunoff requested changes
My tests (https://github.com/OpenRA/OpenRA/pull/20123#issuecomment-1219416431, https://github.com/OpenRA/OpenRA/pull/20123#issuecomment-1219420490 and https://github.com/OpenRA/OpenRA/pull/20123#issuecomment-1219423604) are now passing and code changes LGTM.

I was not able to reproduce https://github.com/OpenRA/OpenRA/pull/20123#issuecomment-1214176232 but manually packing/unpacking .oramap is not advised anyway.

Just a minor wording nit and then :+1:

2022-08-25 08:50 UTC, dragunoff commented on OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
> +						text: deletedOrUnavailable ? "The map may have deleted outside the editor" : "Exit and lose all unsaved changes?",
```suggestion
						text: deletedOrUnavailable ? "The map may have been deleted outside the editor" : "Exit and lose all unsaved changes?",
```

2022-08-25 09:21 UTC, dragunoff approved these changes

2022-08-29 09:27 UTC, RoosterDragon approved these changes

2022-08-29 09:30 UTC, penev92 approved these changes
Both @dragunoff and @RoosterDragon approved.

2022-08-29 09:31 UTC, merged

2022-08-29 10:32 UTC, PunkPun commented
[Changelog](https://github.com/OpenRA/OpenRA/pull/20123)