Match input modifiers and mouse buttons to SDL ones.
OpenRA/OpenRA pull request #20138
Opened 2022-07-23 13:33 UTC by anvilvapre

Closes #17172

- Change `Modifiers` and `MouseButtons` enum values to match masks and values of SDL.
- Let SDL platform determine at startup if mapping is compatible.
- Use (trivial) faster direct mapping if possble - fall back on past conversion otherwise. 
- Remove "[flags]"  from MouseButton enum - as it was never a flag - events handled per individual button click. 
- Modifiers are a mask (i.e. Ctrl is either Left or Right control key mask).
- Log an info message if unexpectedly SDL ID/enum values do change over versions.

Implementing it this way avoids generic platform to have to reference SDL. Theoretical future other - non SDL - implementations are not negatively impacted.

2022-08-25 09:29 UTC, PunkPun commented
It would have been nice to separate independent changes into several commits

2022-08-25 09:58 UTC, PunkPun requested changes
If we add support for left vs right modifiers we also need to add UI to the user to indicate it

Left Shift + Up
Right Shift + Down

PR
<img width="213" alt="Screenshot 2022-08-25 at 12 49 46" src="https://user-images.githubusercontent.com/37534529/186634239-2eae1157-97dc-4889-a2cd-743755845f52.png">

Bleed
<img width="227" alt="Screenshot 2022-08-25 at 12 50 58" src="https://user-images.githubusercontent.com/37534529/186634241-cacd88f9-5388-4d9a-9df6-4452c268ed08.png">

We will need to update user settings.yaml with this PR. 

As all OpenRA engine mods share the same settings.yaml file, once someone launches a release / bleed with this PR, all of the other openra games without this update will crash. We need to keep backwards compatibility

2022-08-25 09:58 UTC, PunkPun commented on OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
> +			var compatible = (((int)Modifiers.Alt == (int)SDL.SDL_Keymod.KMOD_ALT)
Redundant parenthesis

2022-08-25 09:58 UTC, PunkPun commented on OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
> +			var compatible = ((int)MouseButton.Left == (int)SDL.SDL_BUTTON_LEFT
Redundant parenthesis

2022-08-25 10:35 UTC, anvilvapre commented
> If we add support for left vs right modifiers we also need to add UI to the user to indicate it
> 
> Left Shift + Up Right Shift + Down
> 
> PR <img alt="Screenshot 2022-08-25 at 12 49 46" width="213" src="https://user-images.githubusercontent.com/37534529/186634239-2eae1157-97dc-4889-a2cd-743755845f52.png">
> 
> Bleed <img alt="Screenshot 2022-08-25 at 12 50 58" width="227" src="https://user-images.githubusercontent.com/37534529/186634241-cacd88f9-5388-4d9a-9df6-4452c268ed08.png">
> 
> We will need to update user settings.yaml with this PR.
> 
> As all OpenRA engine mods share the same settings.yaml file, once someone launches a release / bleed with this PR, all of the other openra games without this update will crash. We need to keep backwards compatibility



> If we add support for left vs right modifiers we also need to add UI to the user to indicate it
> 
> Left Shift + Up Right Shift + Down
> 
> PR <img alt="Screenshot 2022-08-25 at 12 49 46" width="213" src="https://user-images.githubusercontent.com/37534529/186634239-2eae1157-97dc-4889-a2cd-743755845f52.png">
> 
> Bleed <img alt="Screenshot 2022-08-25 at 12 50 58" width="227" src="https://user-images.githubusercontent.com/37534529/186634241-cacd88f9-5388-4d9a-9df6-4452c268ed08.png">
> 
> We will need to update user settings.yaml with this PR.
> 
> As all OpenRA engine mods share the same settings.yaml file, once someone launches a release / bleed with this PR, all of the other openra games without this update will crash. We need to keep backwards compatibility

With this change the game doesn't. It does not distinguish between left or right button presses. Would also not suggest that if there is no functional use case for it. 

It only introduces that a button press can be represented by two bit values/flags.

2022-08-25 10:42 UTC, PunkPun commented
> With this change the game doesn't. It does not distinguish between left or right button presses. Would also not suggest that if there is no functional use case for it.

> It only introduces that a button press can be represented by two bit values/flags.

Well you can see clear as day that it does. My screenshots show the new hotkey generation before and after this PR, and without manually deleting those I can't access bleed or any other openra game

2022-08-25 10:52 UTC, abcdefg30 commented
Both should just be `SHIFT` and not numbers.

2022-08-25 11:03 UTC, anvilvapre commented
I guess i misses something in the key press detection. Assumed it wouldn't have been impacted.

2022-08-26 20:35 UTC, anvilvapre commented
The issue is caused by `Hotkey` calling `Modifiers.ToString("F")` to retrieve the name of an enum value and `TryParse` to parse it.

Fixing this is no issue. 

However after in `HotKeyReference.IsActiviedBy` an `KeyInput` is matched against the modifiers. To fix this SDL input can best change left and/or right shift to `Modifiers.Shift`. But this means you again do a mapping on each input. Which kind of defies the whole purpose of this commit. 

Letting HotKeyReference.IsActiviedBy` use `hasmodifiers` rather than doing an equals will make you loose support for multiple modifiers i.e. ctrl + alt. 

All in all, i think it's best to close this.

2022-08-28 15:23 UTC, abcdefg30 commented
> All in all, i think it's best to close this.

Ok.

2022-08-28 15:23 UTC, closed without merging

2022-08-28 15:25 UTC, PunkPun commented
Should this be added to the `Future` milestone?

2022-08-29 10:51 UTC, abcdefg30 commented
I don't think so.

2022-08-29 10:57 UTC, anvilvapre commented
agree. 

some would say input events do not happen often enough to have any notice impact on performance. 

simplest future fix would be for the game to do distinguish between left and right clicks.