Add truncation to FactionLabel
OpenRA/OpenRA pull request #20176
Opened 2022-08-08 16:48 UTC by PunkPun

With a more cramped UI in #20100 comes the issue of too long faction names. I've added truncation from over `WidgetUtils.BindPlayerNameAndStatus`. 

Regular names without prefixes aren't truncated, but with prefixes often are. As you can see in the images below it doesn't look the greatest as UI sizes aren't set up correctly, this is fixed in #20100 so I didn't bother here

<img width="596" alt="Screenshot 2022-08-08 at 19 37 43" src="https://user-images.githubusercontent.com/37534529/183469256-da7f4d94-462e-4f7b-b4fd-69c24ec9214d.png">

<img width="582" alt="Screenshot 2022-08-08 at 19 18 40" src="https://user-images.githubusercontent.com/37534529/183469274-ccf7d1e7-a04b-4d5f-b024-3573dda9f397.png">

2022-08-10 13:06 UTC, PunkPun commented
<img width="553" alt="Screenshot 2022-08-10 at 16 03 22" src="https://user-images.githubusercontent.com/37534529/183908445-0421ca7d-9014-4144-a56b-cf6edf9ddd71.png">

I've increased the space for faction names so that regular faction names don't get truncated. I've also moved the score a bit to the left, which doesn't look perfect now but they will in #20100

2022-08-16 06:53 UTC, dragunoff requested changes
Truncation works as promised but could you also add a tooltip? You can use `WidgetUtils.TruncateLabelToTooltip` with a `LabelWithTooltipWidget`.

2022-08-16 07:56 UTC, PunkPun commented
> Truncation works as promised but could you also add a tooltip? You can use `WidgetUtils.TruncateLabelToTooltip` with a `LabelWithTooltipWidget`.

They don't have a tooltip. If you want to add it, it should be done in a separate PR

2022-08-16 10:40 UTC, dragunoff requested changes

2022-08-16 10:40 UTC, dragunoff commented on OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoStatsLogic.cs
> +					WidgetUtils.TruncateLabelToTooltip(factionLabel, factionName);
The truncation and assignment of `GetText` is happening in `WidgetUtils.TruncateLabelToTooltip` so you can reduce this to just:
```csharp
WidgetUtils.TruncateLabelToTooltip(item.Get<LabelWithTooltipWidget>("FACTION"), factionName);
```

2022-08-16 11:01 UTC, dragunoff approved these changes
LGTM :+1:

2022-08-16 15:03 UTC, MustaphaTR approved these changes

2022-08-16 15:58 UTC, penev92 approved these changes
Since both @dragunoff and @MustaphaTR approved and yet managed to not enable the merge button 👍

2022-08-16 15:58 UTC, merged

2022-08-16 16:08 UTC, PunkPun commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed))