Disallowed Save Map without Title and Author Input
OpenRA/OpenRA pull request #20274
Opened 2022-09-08 22:27 UTC by The-Zen-Cat

Fixes #20236

When trying to save a map it is possible to do so without specifying a Title or Author. Previously, the only enforced requirement was a filename, which has been expanded to enforce both a title and author be entered prior to saving the map.

Apologies to PunkPun and abcdefg30 - I had to resubmit this to keep branches in order (I'm a newbie).  I incorporated abcdefg30's changes to not include white space as well.

2022-09-09 07:05 UTC, dragunoff reviewed
Works as promised :+1: However while we're here I think it'd be nice to focus the filename input when this dialog is opened. This is the only thing that the user needs to fill when creating a new  map.

![image](https://user-images.githubusercontent.com/1355810/189289595-8d881e18-8be7-4fb6-be5d-3146c9884266.png)

```csharp
if (string.IsNullOrEmpty(filename.Text))
{
	filename.TakeKeyboardFocus();
	filename.CursorPosition = filename.Text.Length;
}
```

2022-09-09 10:07 UTC, abcdefg30 commented
> Works as promised 👍 However while we're here I think it'd be nice to focus the filename input when this dialog is opened. This is the only thing that the user needs to fill when creating a new map.
> ```cs
> if (string.IsNullOrEmpty(filename.Text))
> {
> 	filename.TakeKeyboardFocus();
> 	filename.CursorPosition = filename.Text.Length;
> }
> ```

Should be
 ```cs
if (string.IsNullOrEmpty(filename.Text))
{
	filename.TakeKeyboardFocus();
	filename.CursorPosition = 0;
}
```
since `filename.Text` might be `null` and the position shouldn't be anything else than `0` anyway?

2022-09-09 10:19 UTC, dragunoff commented
> 
> Should be
> 
> ```cs
> if (string.IsNullOrEmpty(filename.Text))
> {
>    filename.TakeKeyboardFocus();
>    filename.CursorPosition = 0;
> }
> ```
> 
> since `filename.Text` might be `null` and the position shouldn't be anything else than `0` anyway?

It's not even needed. I added it because I was also testing the save dialog when there is a filename but I forgot to remove it. In this case (new map) it is always empty so the cursor position will be 0 regardless.

2022-09-09 10:24 UTC, PunkPun commented
so?
```cs
if (string.IsNullOrEmpty(filename.Text))
   filename.TakeKeyboardFocus();
```

2022-09-09 13:54 UTC, The-Zen-Cat commented
As long as we're improving this, would it also be nice to check to see if a user had edited the Title and Author sections from the default "Name your map here" and "Your name here"?  If they haven't, perhaps the save button is allowed given that there is text input, technically, but on press it refocuses to the Title or Author window and highlights text for change?

2022-09-09 13:57 UTC, dragunoff commented
> As long as we're improving this, would it also be nice to check to see if a user had edited the Title and Author sections from the default "Name your map here" and "Your name here"? If they haven't, perhaps the save button is allowed given that there is text input, technically, but on press it refocuses to the Title or Author window and highlights text for change?

You mean to focus the title or author if they still have the default values?

2022-09-09 13:59 UTC, The-Zen-Cat commented
> > As long as we're improving this, would it also be nice to check to see if a user had edited the Title and Author sections from the default "Name your map here" and "Your name here"? If they haven't, perhaps the save button is allowed given that there is text input, technically, but on press it refocuses to the Title or Author window and highlights text for change?
> 
> You mean to focus the title or author if they still have the default values?

But also highlight the text to make it clear what is happening.

2022-09-09 14:04 UTC, abcdefg30 commented
Imho the best idea would be to have `Your name here` and `Name your map here` grey text that is not "real" text, like the `Leave a comment` text on GitHub before you wrote anything:
![grafik](https://user-images.githubusercontent.com/7704140/189368476-0f89d531-9971-459f-98db-14d509d7d11b.png)

2022-09-09 14:08 UTC, dragunoff commented
Yeah, placeholders would be great. Anything that improves UX with forms. But let's keep this PR simple - I think it's a nice polish win. And then have a larger conversation around forms and validation.

2022-09-09 21:54 UTC, The-Zen-Cat commented on OpenRA.Mods.Common/Widgets/Logic/Editor/SaveMapLogic.cs
> -					return;
Added focus if filename is empty.  Lines 236 and 237 were redundant as the save button would be inactive if the save button is disabled.

2022-09-10 14:03 UTC, dragunoff commented on OpenRA.Mods.Common/Widgets/Logic/Editor/SaveMapLogic.cs
> +				filename.TakeKeyboardFocus();
Could you please move this closer to where `filename.Text` is populated (right after line 162)?

2022-09-13 13:59 UTC, abcdefg30 approved these changes, later dismissed

2022-09-13 14:04 UTC, PunkPun commented on OpenRA.Mods.Common/Widgets/Logic/Editor/SaveMapLogic.cs
> +				filename.TakeKeyboardFocus();
Almost there!
Style nit: we always add a newlines after an `if` statement

2022-09-13 14:06 UTC, dragunoff requested changes
@The-Zen-Cat Please clean-up the commit message as it has the same line repeated several times. Otherwise changes LGTM and the feature works :+1:

2022-09-13 14:17 UTC, The-Zen-Cat commented
> @The-Zen-Cat Please clean-up the commit message as it has the same line repeated several times. Otherwise changes LGTM and the feature works 👍

Sorry, not sure how to do this?  It seems like squashing commits together creates duplicate commit messages?

2022-09-13 14:21 UTC, dragunoff commented
> 
> Sorry, not sure how to do this? It seems like squashing commits together creates duplicate commit messages?

You can do an interactive rebase but choose the "reword" option instead of "squash". Or since this is the commit on the tip of the branch you can simply amend it by running `git commit --amend` (this will open a text editor with the commit message).

2022-09-13 15:44 UTC, The-Zen-Cat commented
Ok, I think the commit --amend worked.  There should now be only 1 commit message.  Added newline after if statement.

2022-09-13 15:48 UTC, PunkPun approved these changes

2022-09-13 15:48 UTC, merged

2022-09-13 15:51 UTC, PunkPun commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3a723f1bf98f12e0dddd840ad051b73bc9d6fd39...206dbbd52eb5f5290c16623a4c1f5022fb534f8c)