Fix the incompatible replay dialogue translations
OpenRA/OpenRA pull request #20320
Opened 2022-09-20 13:27 UTC by abcdefg30

Updates Linguini to include the changes from https://github.com/Ygg01/Linguini/pull/24, and adds some new lines to stop the text from overflowing over the dialogue borders:
![grafik](https://user-images.githubusercontent.com/7704140/191269636-09f01d7e-269b-4324-aca0-8e04d27def4e.png)
![grafik](https://user-images.githubusercontent.com/7704140/191269645-0507712b-fc18-49b9-95f6-27536890d6a0.png)
![grafik](https://user-images.githubusercontent.com/7704140/191269656-792c76ed-85ec-496f-a47b-e3067be7378c.png)
![grafik](https://user-images.githubusercontent.com/7704140/191269981-958d808d-661c-4744-8781-3154250ad5ab.png)

2022-09-21 19:39 UTC, PunkPun commented on mods/common/languages/en.ftl
> +    { $mod }.
Perhaps keep `$mod` in the same line? We use short names and it looks out of place to have them in a newline

2022-09-22 18:28 UTC, RoosterDragon approved these changes, later dismissed
Thanks for these changes, nice tidyup.

2022-09-23 14:12 UTC, dragunoff requested changes
I think it makes more sense for the button to say "OK" instead of "Cancel":
![image](https://user-images.githubusercontent.com/1355810/191976586-83723167-6351-4421-b31a-4e7eecd02053.png)

Sorry for the scope creeping but I noticed some issues around this.

2022-09-23 14:12 UTC, dragunoff commented on mods/common/languages/en.ftl
> +    { $mod }.
In these cases `$version` and `$mod` are `null` so the game crashes:
```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.TranslationExts.ToFluentType(Object value) in /home/ivaylo/code/OpenRA/OpenRA.Game/TranslationExts.cs:line 41
   at OpenRA.Translation.TryGetString(String key, String& value, IDictionary`2 arguments) in /home/ivaylo/code/OpenRA/OpenRA.Game/Translation.cs:line 100
   at OpenRA.Mods.Common.Widgets.ConfirmationDialogs.ButtonPrompt(ModData modData, String title, String text, Dictionary`2 titleArguments, Dictionary`2 textArguments, Action onConfirm, Action onCancel, Action onOther, String confirmText, String cancelText, String otherText) in /home/ivaylo/code/OpenRA/OpenRA.Mods.Common/Widgets/ConfirmationDialogs.cs:line 43
   at OpenRA.Mods.Common.Widgets.Logic.ReplayUtils.IncompatibleReplayDialog(String text, Dictionary`2 textArguments, ModData modData, Action onCancel) in /home/ivaylo/code/OpenRA/OpenRA.Mods.Common/Widgets/Logic/ReplayUtils.cs:line 78
   at OpenRA.Mods.Common.Widgets.Logic.ReplayUtils.PromptConfirmReplayCompatibility(ReplayMetadata replayMeta, ModData modData, Action onCancel) in /home/ivaylo/code/OpenRA/OpenRA.Mods.Common/Widgets/Logic/ReplayUtils.cs:line 62
   at OpenRA.Mods.Common.Widgets.Logic.ReplayBrowserLogic.WatchReplay() in /home/ivaylo/code/OpenRA/OpenRA.Mods.Common/Widgets/Logic/ReplayBrowserLogic.cs:line 771
```

We don't need to pass any arguments - the mod/version is simply unknown.

2022-09-23 14:12 UTC, dragunoff commented on mods/common/languages/en.ftl
> +    { $map }.
I wasn't able to trigger this one, the game tries to download the map from the resource center and if it fails it won't even allow the "Watch" button to be clicked.

2022-09-23 14:20 UTC, dragunoff commented on mods/common/languages/en.ftl
> +    { $map }.
Ah, I guess this is for when we load directly into a replay.

2022-09-27 12:04 UTC, abcdefg30 commented
Updated:
- Changed "Cancel" to "OK"
![grafik](https://user-images.githubusercontent.com/7704140/192519897-57573c64-e8df-4e47-bb3d-813afafb0849.png)
- Removed line breaks for mod names
![grafik](https://user-images.githubusercontent.com/7704140/192519907-fe726f96-a3b9-4b85-931f-5fef1f521415.png)
- Fixed the crash with null arguments
![grafik](https://user-images.githubusercontent.com/7704140/192520084-1ad9ee08-1372-490b-9d88-0d04ddfe28f0.png)

2022-09-29 18:51 UTC, dragunoff approved these changes

2022-09-29 20:34 UTC, PunkPun approved these changes

2022-09-29 20:34 UTC, merged

2022-09-29 20:36 UTC, PunkPun commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6cd6fa16ef828d492415130e5bafe0ae61d1957a...607e3b63393dec981f1ba65c6675029adb37ab0d)