Pathing considers reachability of source and destination cells consistently
OpenRA/OpenRA pull request #20372
Opened 2022-10-15 13:19 UTC by RoosterDragon

Previously, you could not find a path to an unreachable destination cell, however it was possible to find a path from an unreachable source cell if there was a reachable cells adjacent to it.

This led to an asymmetric behaviour which could be an issue in some use cases which perform a path search with the source and destination swapped and then reverse the resulting path. Callers that reverse a path in this fashion could be told there is a valid path to an unreachable destination cell. This would occur if before reversing the source cell was unreachable, but a path could be found from it anyway.

We unify the behaviour to treat both source and destination cells that are unreachable in the same fashion, that there is no path is either is unreachable.

----

Recommend #20367 is merged first. This PR will exacerbate the issue that PR resolves as both the local pathfinder and HPF will reject paths from the exit cell that is inaccessible as it is located within the barracks. This means where units would previously ignore a rally point >20 cells north of the barracks they will now ignore a rally point to the north regardless of how far away it is. This is because HPF kicks in at >20 cells.

2022-10-15 14:19 UTC, PunkPun commented
This might turn some bugs from immersion breaking inconveniences into game breaking bugs. For example it is possible to spawn a unit on top of another unit with crates, this PR would make both of these units unusable. 

As this PR isn't fixing a crash, but rather a tiny inconsistency I suggest pushing it to Next + 1 to avoid delaying the release over possibly massive amounts of miscellaneous gamebreaking bugs

2022-10-15 18:18 UTC, RoosterDragon commented
We're already in a buggy position, because `HPF` is already treating the units as stuck. But yes, this behaviour change would make it more prevalent.

2022-10-21 13:15 UTC, abcdefg30 requested changes
Harvesters no longer move off a newly built refinery in RA.

2022-10-21 13:17 UTC, abcdefg30 commented
To be honest I'm not sure if we should stop trying to find a path if the source cell is not accessible, since that doesn't really matter (the unit is already in the cell and doesn't need to access it any more). Moving off an unpathable cell is ok imo. So I think it would be better if we could allow searching from unpathable source cells (or towards unpathable target cells in case of a reverse search).

2022-10-25 19:41 UTC, RoosterDragon commented
This is fair. I will close this PR in favour of an approach that maintains the existing behaviour and gets HPF to align with it. See #20399.

2022-10-25 19:41 UTC, closed without merging