Add causes for TargetInvocationException in TriggerGlobal
OpenRA/OpenRA pull request #20868
Opened 2023-05-19 14:28 UTC by Mailaender

This addresses https://github.com/OpenRA/OpenRA/pull/18802#issuecomment-1542364531 where a simple typo of a player name causes a large and difficult to read stacktrace.

https://github.com/OpenRA/OpenRA/blob/0751b30d330dcd5329bbe54b0e113967abe68f0f/mods/ra/scripts/campaign.lua#L12-L15

will crash when the player is null because the function expects a certain type

https://github.com/OpenRA/OpenRA/blob/0751b30d330dcd5329bbe54b0e113967abe68f0f/OpenRA.Mods.Common/Scripting/Global/TriggerGlobal.cs#L179-L184

and the type conversion fails while the script is being loaded, which is also why we don't get line numbers for some reason. This shortens the stacktrace by throwing earlier.

2023-05-19 15:13 UTC, abcdefg30 requested changes
This breaks all script functions that want to pass `nil`. (See `allies-01` or any other usage of reinforcements for example.)

2023-05-19 17:23 UTC, Mailaender commented
It indeed breaks in allies-01 with the second helicopter. My next approach throws even more 

```
 ---> System.NullReferenceException: actor
   at OpenRA.Mods.Common.Scripting.TriggerGlobal.OnKilled(Actor actor, LuaFunction func) in OpenRA/OpenRA.Mods.Common/Scripting/Global/TriggerGlobal.cs:line 88
```

but adds the method signature to the exception.

2023-05-20 09:05 UTC, abcdefg30 approved these changes, later dismissed
Ok.

2023-05-21 15:05 UTC, PunkPun reviewed
OnAllKilled is missing a null check. Also this should get rebased for easier testing

2023-05-23 14:29 UTC, PunkPun approved these changes

2023-05-23 14:30 UTC, merged

2023-05-23 14:32 UTC, PunkPun commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/93d474bfdde7732dd07065f52394e042f9432e90...885ac4f61c3a881a37c4be14abf87edf9ec3b3c2)