Bytes -> Hex conversion update
OpenRA/OpenRA pull request #21065
Opened 2023-09-18 15:56 UTC by rudzen

# Bytes -> Hex conversion update

Hi!

I've updated the functionality which converts a byte array to a lower case hex string.

The performance is improved while still being compatible with the previous version.
For good measure I've added a few unit tests for SHA-1 hashing which uses the wiki examples.

## Changes

- Added new byte-to-hex compute functionality
- Added sha-1 unit tests which computes hashes from wiki hash examples

## Affects

Anything that computes a SHA1 hash through CryptoUtil.

## Benchmarks

To get an idea of the scaling, I cooked up a little benchmark to test the changes when hashing with SHA-1.

Runs with data sizes of 32, 128, 4096 and 1048576.

~~~text
BenchmarkDotNet v0.13.8, Windows 11 (10.0.22621.2283/22H2/2022Update/SunValley2)
Intel Core i7-8086K CPU 4.00GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK 7.0.401
  [Host]     : .NET 6.0.22 (6.0.2223.42425), X64 RyuJIT AVX2
  DefaultJob : .NET 6.0.22 (6.0.2223.42425), X64 RyuJIT AVX2

| Method | source        | Mean           | Error        | StdDev       | Ratio    | RatioSD | Gen0   | Allocated | Alloc Ratio |
|------- |-------------- |---------------:|-------------:|-------------:|---------:|--------:|-------:|----------:|------------:|
| New    | Byte[32]      |       516.3 ns |      2.90 ns |      2.72 ns |     1.00 |    0.00 | 0.0515 |     328 B |        1.00 |
| New    | Byte[128]     |       719.5 ns |      2.39 ns |      1.99 ns |     1.39 |    0.01 | 0.0515 |     328 B |        1.00 |
| Old    | Byte[32]      |     1,892.2 ns |      6.90 ns |      5.76 ns |     3.66 |    0.02 | 0.3357 |    2120 B |        6.46 |
| Old    | Byte[128]     |     2,083.2 ns |     25.25 ns |     23.62 ns |     4.03 |    0.05 | 0.3357 |    2120 B |        6.46 |
| New    | Byte[4096]    |     6,178.7 ns |     59.15 ns |     52.44 ns |    11.96 |    0.12 | 0.0458 |     328 B |        1.00 |
| Old    | Byte[4096]    |     7,641.6 ns |     28.97 ns |     27.10 ns |    14.80 |    0.11 | 0.3357 |    2120 B |        6.46 |
| New    | Byte[1048576] | 1,446,723.0 ns | 15,953.62 ns | 14,142.47 ns | 2,801.10 |   27.77 |      - |     329 B |        1.00 |
| Old    | Byte[1048576] | 1,455,390.5 ns | 10,615.80 ns |  9,930.03 ns | 2,818.90 |   22.72 |      - |    2121 B |        6.47 |
~~~

2023-09-18 17:25 UTC, PunkPun commented
👋 

it seems that this solution is incompatible with the mono build

> OpenRA.Game/CryptoUtil.cs(283,40): error CS0117: 'MemoryMarshal' does not contain a definition for 'GetArrayDataReference'

2023-09-18 17:50 UTC, RoosterDragon commented
You can guard with `#if NET6_0_OR_GREATER` and keep the previous implementation around for mono. Alternatively, implementing the loop without any unsafe might sidestep the problem and still be faster.

How does this method compare to [Convert.ToHexString](https://learn.microsoft.com/en-us/dotnet/api/system.convert.tohexstring?view=net-7.0) (which would need `#if NET5_0_OR_GREATER`) followed by a lowercase?

2023-09-18 19:38 UTC, rudzen commented
> You can guard with `#if NET6_0_OR_GREATER` and keep the previous implementation around for mono. Alternatively, implementing the loop without any unsafe might sidestep the problem and still be faster.
> 
> How does this method compare to [Convert.ToHexString](https://learn.microsoft.com/en-us/dotnet/api/system.convert.tohexstring?view=net-7.0) (which would need `#if NET5_0_OR_GREATER`) followed by a lowercase?

Added an alternate implementation for mono using `#if NET5_0_OR_GREATER`, hopefully that should work.
I tried out some other variations, including the Convert.ToHexString() and also BitConverter.ToString() but they seem pretty cumbersome in comparison because of the lowercase and/or '-' removal.

Did not know I could bump to the `#if NET6_0_OR_GREATER`. Will keep that in mind :)

2023-09-19 18:55 UTC, RoosterDragon requested changes
This reduces time spent in SHA1 hashing during initial load from ~1.4% to 1.2%, which is nice incremental win.

The downside for me is the maintenace burden here. We've added a fair bit of extra code, had to deal with an alternative implementation for mono and added unsafe code. For some larger overall gains I'd say that is worthwhile, but a fraction of a percent in the project overall doesn't sell it for me. Not your fault by any means, if the project was doing like 10-100x more hashing it'd be more tempting.

In this particular case I think you can get a more favourable balance by investigating `Convert.ToHexString` or `BitConverter.ToString`. Since they'd be no more complex than the current code, it'd be an easy sell even if the performance win isn't quite as good.

2023-09-19 19:13 UTC, PunkPun commented
The only other place where we use `x2` format is in color code. But it's not hotly used as well

2023-09-20 18:16 UTC, rudzen commented
> This reduces time spent in SHA1 hashing during initial load from ~1.4% to 1.2%, which is nice incremental win.
> 
> The downside for me is the maintenace burden here. We've added a fair bit of extra code, had to deal with an alternative implementation for mono and added unsafe code. For some larger overall gains I'd say that is worthwhile, but a fraction of a percent in the project overall doesn't sell it for me. Not your fault by any means, if the project was doing like 10-100x more hashing it'd be more tempting.
> 
> In this particular case I think you can get a more favourable balance by investigating `Convert.ToHexString` or `BitConverter.ToString`. Since they'd be no more complex than the current code, it'd be an easy sell even if the performance win isn't quite as good.

Using `Convert.ToHexString` yields almost the same result (see updated benchmark table) and should hardly be noticeable 😄.

2023-09-20 18:44 UTC, PunkPun commented
> OpenRA/OpenRA.Game/CryptoUtil.cs(269,19): error CS0117: 'Convert' does not contain a definition for 'ToHexString' 

it seems it's incompatible with mono 😩

2023-09-20 20:55 UTC, rudzen commented
> > OpenRA/OpenRA.Game/CryptoUtil.cs(269,19): error CS0117: 'Convert' does not contain a definition for 'ToHexString'
> 
> it seems it's incompatible with mono 😩

It would seem mono doesn't like me that much 😢.
Updated it anyways with a simple none-pre processor version that should work just fine.

2023-09-21 18:10 UTC, RoosterDragon approved these changes

2023-09-21 18:15 UTC, PunkPun commented
LGTM, could you squash the commits?

2023-09-22 19:03 UTC, rudzen commented
> LGTM, could you squash the commits?

👍🏻

2023-09-23 07:14 UTC, PunkPun approved these changes

2023-09-23 07:14 UTC, merged

2023-09-23 07:16 UTC, PunkPun commented
[Chanelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/95d790f2b1ecee303cfbbabe51ccbabe7b8998fb...935c54aefa934098404da16e6903da6a2a3445d9)