Fix crashing when transports are loaded via lua
OpenRA/OpenRA pull request #21076
Opened 2023-09-27 07:17 UTC by PunkPun

Regression from #20825

Crash:
> Eluant.LuaException: LoadPassenger requires the passenger to be idle.

This PR entails that aircraft will no longer automatically take-off when placed on the map, restoring the legacy behaviour

An alternative and possibly easier to debug crashes with solution would be to never call GetCreationActivity if actor is not to be added to world. Or perhaps instead pass that info down to the GetCreationActivity activity

2023-10-27 10:43 UTC, PunkPun commented
https://github.com/OpenRA/OpenRA/assets/37534529/340e1577-b4c9-42a3-b07a-0d900cdb66aa

D2K shellmap

2023-10-28 19:01 UTC, pchote commented
Crashes when building a vehicle in RA:
```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Traits.Render.WithProductionDoorOverlay.OpenRA.Traits.ITick.Tick(Actor self) in /Users/paul/src/OpenRA/OpenRA.Mods.Common/Traits/Render/WithProductionDoorOverlay.cs:line 70
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text) in /Users/paul/src/OpenRA/OpenRA.Game/TraitDictionary.cs:line 312
   at OpenRA.World.Tick() in /Users/paul/src/OpenRA/OpenRA.Game/World.cs:line 445
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /Users/paul/src/OpenRA/OpenRA.Game/Game.cs:line 632
   at OpenRA.Game.LogicTick() in /Users/paul/src/OpenRA/OpenRA.Game/Game.cs:line 647
   at OpenRA.Game.Loop() in /Users/paul/src/OpenRA/OpenRA.Game/Game.cs:line 814
   at OpenRA.Game.Run() in /Users/paul/src/OpenRA/OpenRA.Game/Game.cs:line 864
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/paul/src/OpenRA/OpenRA.Game/Game.cs:line 305
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/paul/src/OpenRA/OpenRA.Launcher/Program.cs:line 32
```

2023-10-28 19:08 UTC, PunkPun commented
Fixed, weird that I didn't catch it when initially testing

2023-10-29 10:33 UTC, pchote submitted a review, later dismissed
LGTM and didn't notice any other issues ingame in TD/RA/D2k.

2023-11-04 22:41 UTC, PunkPun commented
Added a commit that reinforces carryalls on d2k shellmap instead of spawning them

2023-11-04 23:39 UTC, abcdefg30 requested changes, later dismissed
Aircraft are completely broken now. It is no longer possible to give any orders to Yaks in RA!

2023-11-04 23:46 UTC, abcdefg30 commented
Fwiw, setting a rallypoint "fixes" that behaviour.

2023-11-05 10:57 UTC, PunkPun commented
the switch to queueing activities as children accidentally made them uninterruptible

2023-11-14 22:02 UTC, penev92 approved these changes, later dismissed

2023-12-03 17:22 UTC, pchote submitted a review, later dismissed

2023-12-03 17:23 UTC, pchote commented
Needs a rebase, then go ahead and merge.

2023-12-03 17:24 UTC, PunkPun commented
Rebased

2023-12-03 19:26 UTC, pchote approved these changes

2023-12-03 19:27 UTC, merged

2023-12-03 19:28 UTC, pchote commented
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8b2de66fce1622d1230254b14db068fdfc337300