Introduce integer vertex attributes
OpenRA/OpenRA pull request #21146
Opened 2023-10-22 21:33 UTC by pchote

With GL 2.1 out of the picture, we are finally able to use integers and bitwise operations in shaders. This PR replaces the legacy workaround simulating a bitfield with a float to a real bitfield. This allows us to use the full 32 bits of storage, which I use to pack the palette row (as a 16 bit int) to shave 4 bytes off the vertex size.

I expect this should give a minor performance boost, but the focus is on shader readability and maintability.

2023-10-22 21:39 UTC, pchote commented
A future PR could make additional, more invasive, optimisations to reduce the vertex size further: Replace the two (float x, float y) texture coordinates with a single (uint xy) coordinate (saves 8 bytes). The color renderer could then use the first integer to encode the colour (it currently needs all 4 floats), which would allow mods that don't need the second sprite channel to save an additional 4 bytes.

2023-10-23 07:58 UTC, pchote commented
Added some additional improvements.

2023-10-23 11:19 UTC, PunkPun requested changes
this PR is running ra shellmap at 3FPS, where as on bleed I'm getting 200+

2023-10-23 11:19 UTC, PunkPun commented on glsl/postprocess_flash.frag
> +	float lum = 0.5 * (min(c.r, min(c.g, c.b)) + max(c.r, max(c.g, c.b)));
unused variable?

2023-10-23 13:34 UTC, pchote commented
RA shellmap is ~340 FPS for me, compared to ~340 FPS on bleed. Can you have a poke around and try to identify what is causing your perf regression?

2023-10-23 13:38 UTC, PunkPun commented
It seems to be caused by the first commit

2023-10-23 13:40 UTC, PunkPun commented
within the render loop

2023-10-23 15:14 UTC, dnqbob commented
@PunkPun 

Windowed or full screen?

2023-10-23 16:41 UTC, pchote commented
@PunkPun can you please try again on the updated version?

2023-10-23 17:31 UTC, PunkPun commented on OpenRA.Platforms.Default/Shader.cs
> +					OpenGL.glVertexAttribPointer(i, attribute.Components, (int)attribute.Type, false, bindings.Stride, new IntPtr(attribute.Offset));
```suggestion
					OpenGL.glVertexAttribPointer(i, attribute.Components, OpenGL.GL_FLOAT, false, bindings.Stride, new IntPtr(attribute.Offset));
```

this change can be undone. We know that it's a float

2023-10-23 19:42 UTC, PunkPun approved these changes
LGTM, this is a massive performance and shader readability improvement

2023-10-23 19:42 UTC, merged

2023-10-23 19:44 UTC, PunkPun commented
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/eb5eaf5edf05029a445e137a78e49f496236a078...2b88a05accf60c9b7574788e1f5a1793ad064257)